// File generator class for creating TypeScript files
import fs from 'fs';
import path from 'path';
import prettier from 'prettier';

import { OUTPUT_FILES } from '../config/generator.config';
import type { GeneratorOptions, RouteInfo } from '../types/route-generator.types';

export class FileGenerator {
  private outputDir: string;
  private routes: Record<string, RouteInfo>;

  constructor(private options: GeneratorOptions) {
    this.outputDir = options.outputDir;
    this.routes = options.routes;
  }

  /**
   * Generate all files
   */
  async generateFiles(): Promise<void> {
    this.ensureOutputDirectory();

    const configPath = await this.writeConfigFile();
    const typePath = await this.writeTypeFile();
    const utilPath = await this.writeUtilFile();

    this.logResults([configPath, typePath, utilPath]);
  }

  /**
   * Format generated content with project Prettier config
   */
  private async formatContent(content: string, filePath: string): Promise<string> {
    const prettierConfig = await prettier.resolveConfig(filePath);
    return prettier.format(content, {
      ...prettierConfig,
      filepath: filePath,
    });
  }

  /**
   * Ensure output directory exists
   */
  private ensureOutputDirectory(): void {
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }
  }

  /**
   * Generate routes configuration content
   */
  private generateConfigContent(): string {
    const routeEntries = Object.entries(this.routes);

    let content = `// Auto-generated routes configuration
// Do not edit this file manually

export const routes = {\n`;

    routeEntries.forEach(([key, route]) => {
      content += `  '${key}': {\n`;
      content += `    router: ${route.router},\n`;
      content += `    filePath: '${route.filePath}',\n`;
      content += `    pattern: '${route.pattern}',\n`;
      content += `    private: ${route.private},\n`;
      content += `  },\n`;
    });

    content += `} as const;\n\n`;

    content += `// List of all route keys\n`;
    content += `export const routeKeys = [\n`;
    routeEntries.forEach(([key]) => {
      content += `  '${key}',\n`;
    });
    content += `] as const;\n\n`;

    content += `// List of all route patterns\n`;
    content += `export const routePatterns = [\n`;
    routeEntries.forEach(([, route]) => {
      content += `  '${route.pattern}',\n`;
    });
    content += `] as const;\n`;

    return content;
  }

  /**
   * Generate types content
   */
  private generateTypeContent(): string {
    return `// Auto-generated route types
// Do not edit this file manually

import type { routes, routeKeys, routePatterns } from './routes.config';

export type RouteKey = (typeof routeKeys)[number];

export type RoutePattern = (typeof routePatterns)[number];

export type RouteConfig = {
  router: string | ((...args: (string | number)[]) => string);
  filePath: string;
  pattern: string;
  private: boolean | undefined;
};

// Router function types for type safety
export type RouterFunction<T extends RouteKey> = typeof routes[T]['router'];

// Extract parameter types from router functions
export type RouteParams<T extends RouteKey> = RouterFunction<T> extends (...args: infer P) => string ? P : [];

// Helper type to check if route requires parameters
export type RouteRequiresParams<T extends RouteKey> = RouterFunction<T> extends string ? false : true;
`;
  }

  /**
   * Generate utilities content
   */
  private generateUtilContent(): string {
    return `// Auto-generated route utilities
// Do not edit this file manually

import { routes, routeKeys } from './routes.config';
import type { RouteKey, RoutePattern, RouteConfig, RouterFunction } from './routes.type';

type QueryParams = Record<string, string | number | boolean | null | undefined>;

/**
 * Get route configuration by key
 */
export function getRoute(key: RouteKey): RouteConfig {
  return routes[key];
}

/**
 * Navigate to a route with type-safe parameters
 * 
 * @example
 * // Static route
 * navigate('/home') // '/home'
 * 
 * // Dynamic route with parameters
 * navigate('/user/[id]', 123) // '/user/123'
 * 
 * // Catch-all route
 * navigate('/blog/[...slug]', 'category', 'post-title') // '/blog/category/post-title'
 *
 * // Route with query params
 * navigate('/users', { name: 'Henry' }) // '/users?name=Henry'
 */
export function navigate<T extends RouteKey>(
  key: T,
  ...params: [...(RouterFunction<T> extends (...args: infer P) => string ? P : []), QueryParams?]
): string {
  const route = routes[key] as RouteConfig;
  const maybeQuery = params.at(-1);
  const queryParams = typeof maybeQuery === 'object' && maybeQuery !== null && !Array.isArray(maybeQuery)
    ? (params.pop() as QueryParams)
    : undefined;

  const basePath = typeof route.router === 'function'
    ? (route.router as (...args: (string | number)[]) => string)(...(params as (string | number)[]))
    : (route.router as string);

  if (!queryParams) {
    return basePath;
  }

  const queryString = new URLSearchParams(
    Object.entries(queryParams)
      .filter(([, value]) => value !== undefined && value !== null)
      .map(([queryKey, value]) => [queryKey, String(value)])
  ).toString();

  if (!queryString) {
    return basePath;
  }

  return \`\${basePath}?\${queryString}\`;
}

/**
 * Check if a route is private
 */
export function isPrivateRoute(key: RouteKey): boolean {
  const route = routes[key] as RouteConfig;
  return route.private === true;
}

/**
 * Check if a route is public
 */
export function isPublicRoute(key: RouteKey): boolean {
  const route = routes[key] as RouteConfig;
  return route.private === false;
}

/**
 * Check if a route is shared
 */
export function isSharedRoute(key: RouteKey): boolean {
  const route = routes[key] as RouteConfig;
  return route.private === undefined;
}

/**
 * Get all routes by type
 */
export function getRoutesByType(type: 'private' | 'public' | 'shared'): RouteKey[] {
  const targetValue = type === 'private' ? true : type === 'public' ? false : undefined;
  return Object.keys(routes).filter(key => {
    const route = routes[key as RouteKey] as RouteConfig;
    return route.private === targetValue;
  }) as RouteKey[];
}

/**
 * Get route pattern for matching
 */
export function getRoutePattern(key: RouteKey): RoutePattern {
  return routes[key].pattern as RoutePattern;
}

/**
 * Get route file path
 */
export function getRouteFilePath(key: RouteKey): string {
  return routes[key].filePath;
}

/**
 * Generate a regex for a route pattern
 */
export function generateRouteRegex(key: RouteKey): RegExp {
  return new RegExp('^' + getRoutePattern(key).replace(/:[^/]+/g, '[^/]+') + '$');
}


/**
 * Check if a route pattern matches a path
 */
export function checkRoutePattern(key: RouteKey, path: string): boolean {
  const routeRegex = generateRouteRegex(key);
  return routeRegex.test(path);
}

/**
 * Find a route pattern by path
 */
export function findPatternByPath(path: string): RoutePattern | undefined {
  const key = routeKeys.find((key) => {
    return generateRouteRegex(key).test(path);
  }) as RouteKey | undefined;
  return key ? getRoutePattern(key) : undefined;
}
`;
  }

  /**
   * Write configuration file
   */
  private async writeConfigFile(): Promise<string> {
    const filePath = path.join(this.outputDir, OUTPUT_FILES.CONFIG);
    const content = await this.formatContent(this.generateConfigContent(), filePath);
    fs.writeFileSync(filePath, content, 'utf8');
    return filePath;
  }

  /**
   * Write types file
   */
  private async writeTypeFile(): Promise<string> {
    const filePath = path.join(this.outputDir, OUTPUT_FILES.TYPES);
    const content = await this.formatContent(this.generateTypeContent(), filePath);
    fs.writeFileSync(filePath, content, 'utf8');
    return filePath;
  }

  /**
   * Write utilities file
   */
  private async writeUtilFile(): Promise<string> {
    const filePath = path.join(this.outputDir, OUTPUT_FILES.UTILS);
    const content = await this.formatContent(this.generateUtilContent(), filePath);
    fs.writeFileSync(filePath, content, 'utf8');
    return filePath;
  }

  /**
   * Log generation results
   */
  private logResults(filePaths: string[]): void {
    console.log(`✅ Routes generated successfully!`);
    console.log(`📁 Output directory: ${path.relative(process.cwd(), this.outputDir)}`);
    console.log(`📄 Files created:`);

    filePaths.forEach((filePath) => {
      console.log(`   - ${path.relative(process.cwd(), filePath)}`);
    });

    console.log(`📊 Total routes: ${Object.keys(this.routes).length}`);
  }
}
