import type {
  ArticleCategory,
  ArticleCategoryMapping,
} from '@/app/api/_schemas/article-category.schema';

export const UNCLASSIFIED_CATEGORY_ID = 'CAT-000';

export const SEED_ARTICLE_CATEGORY_ROWS: ArticleCategory[] = [
  {
    id: 'CAT-000',
    name: '未分類',
    description: '削除されたカテゴリの記事が一時的に割り当てられる特別カテゴリ',
    type: 'notice',
    brand_enum: 'joyfit',
    order: 0,
    is_public: false,
  },
  {
    id: 'CAT-001',
    name: 'キャンペーン・イベント',
    description: '入会キャンペーンや店舗イベント情報',
    type: 'notice',
    brand_enum: 'joyfit',
    order: 1,
    is_public: true,
  },
  {
    id: 'CAT-002',
    name: '施設・設備情報',
    description: '施設リニューアルや設備更新に関するお知らせ',
    type: 'notice',
    brand_enum: 'joyfit',
    order: 2,
    is_public: true,
  },
  {
    id: 'CAT-003',
    name: 'システム・メンテナンス',
    description: 'システムメンテナンスや障害情報',
    type: 'notice',
    brand_enum: 'joyfit24',
    order: 3,
    is_public: true,
  },
  {
    id: 'CAT-010',
    name: 'FIT365限定情報',
    description: 'FIT365ブランド向けのお知らせ',
    type: 'notice',
    brand_enum: 'fit365',
    order: 4,
    is_public: false,
  },
  {
    id: 'CAT-004',
    name: 'トレーニング',
    description: '筋トレ・有酸素運動など一般的なトレーニング記事',
    type: 'blog',
    brand_enum: 'joyfit_yoga',
    order: 1,
    is_public: true,
  },
  {
    id: 'CAT-005',
    name: 'ヨガ・ピラティス',
    description: 'ヨガやピラティスに関する記事',
    type: 'blog',
    brand_enum: 'joyfit_yoga',
    order: 2,
    is_public: true,
  },
  {
    id: 'CAT-006',
    name: 'ダイエット・ボディメイク',
    description: 'ダイエットやボディメイクに関する記事',
    type: 'blog',
    brand_enum: 'joyfit_plus',
    order: 3,
    is_public: true,
  },
  {
    id: 'CAT-007',
    name: '栄養・食事',
    description: '栄養や食事管理に関する記事',
    type: 'blog',
    brand_enum: 'joyfit24',
    order: 4,
    is_public: true,
  },
  {
    id: 'CAT-008',
    name: 'スタッフ紹介',
    description: 'スタッフやトレーナー紹介記事',
    type: 'blog',
    brand_enum: 'joyfit_plus',
    order: 5,
    is_public: true,
  },
  {
    id: 'CAT-009',
    name: '健康・ライフスタイル',
    description: '健康的なライフスタイルに関する記事',
    type: 'blog',
    brand_enum: 'joyfit',
    order: 6,
    is_public: true,
  },
  {
    id: 'CAT-011',
    name: '季節限定企画',
    description: '季節ごとの特集記事（準備中、記事紐づけなし）',
    type: 'blog',
    brand_enum: 'joyfit24',
    order: 7,
    is_public: true,
  },
  {
    id: 'CAT-012',
    name: '会員特典・優待情報',
    description: '提携店舗の優待やポイント特典に関するお知らせ',
    type: 'notice',
    brand_enum: 'joyfit_yoga',
    order: 5,
    is_public: true,
  },
  {
    id: 'CAT-013',
    name: '店舗休業案内',
    description: '臨時休業や営業時間変更のお知らせ',
    type: 'notice',
    brand_enum: 'joyfit',
    order: 6,
    is_public: true,
  },
  {
    id: 'CAT-014',
    name: '料金改定のお知らせ',
    description: '月会費・オプション料金の改定情報',
    type: 'notice',
    brand_enum: 'joyfit_plus',
    order: 7,
    is_public: false,
  },
  {
    id: 'CAT-015',
    name: '個人情報保護方針改定',
    description: 'プライバシーポリシー改定のお知らせ',
    type: 'notice',
    brand_enum: 'fit365',
    order: 8,
    is_public: true,
  },
  {
    id: 'CAT-016',
    name: 'スタッフ退職・異動のお知らせ',
    description: '担当トレーナーの退職・異動情報',
    type: 'notice',
    brand_enum: 'joyfit24',
    order: 9,
    is_public: true,
  },
  {
    id: 'CAT-017',
    name: '災害・緊急時対応',
    description: '台風・地震等の緊急時における店舗対応情報',
    type: 'notice',
    brand_enum: 'joyfit_plus',
    order: 10,
    is_public: true,
  },
  {
    id: 'CAT-018',
    name: 'アプリメンテナンス情報',
    description: '公式アプリのメンテナンス・障害情報（準備中、記事紐づけなし）',
    type: 'notice',
    brand_enum: 'fit365',
    order: 11,
    is_public: true,
  },
  {
    id: 'CAT-019',
    name: '法人向けお知らせ',
    description: '法人契約・福利厚生プランに関する案内',
    type: 'notice',
    brand_enum: 'joyfit',
    order: 12,
    is_public: false,
  },
  {
    id: 'CAT-020',
    name: '筋トレ初心者ガイド',
    description: 'これから筋トレを始める人向けの入門記事',
    type: 'blog',
    brand_enum: 'joyfit',
    order: 8,
    is_public: true,
  },
  {
    id: 'CAT-021',
    name: '有酸素運動特集',
    description: 'ランニング・サイクリングなど有酸素運動の記事',
    type: 'blog',
    brand_enum: 'joyfit24',
    order: 9,
    is_public: true,
  },
  {
    id: 'CAT-022',
    name: 'ストレッチ・柔軟性',
    description: '柔軟性向上やケガ予防のためのストレッチ記事',
    type: 'blog',
    brand_enum: 'joyfit_yoga',
    order: 10,
    is_public: true,
  },
  {
    id: 'CAT-023',
    name: 'プロテイン・サプリメント',
    description: 'プロテインやサプリメントの選び方・活用法',
    type: 'blog',
    brand_enum: 'joyfit_plus',
    order: 11,
    is_public: true,
  },
  {
    id: 'CAT-024',
    name: '女性向けフィットネス',
    description: '女性の体づくりや美容に関するフィットネス記事',
    type: 'blog',
    brand_enum: 'joyfit24',
    order: 12,
    is_public: true,
  },
  {
    id: 'CAT-025',
    name: 'シニア向けトレーニング',
    description: '高齢者向けの安全なトレーニング方法の紹介',
    type: 'blog',
    brand_enum: 'fit365',
    order: 13,
    is_public: true,
  },
  {
    id: 'CAT-026',
    name: '姿勢改善・骨盤矯正',
    description: '姿勢や骨盤の歪みを改善するエクササイズ記事',
    type: 'blog',
    brand_enum: 'joyfit',
    order: 14,
    is_public: true,
  },
  {
    id: 'CAT-027',
    name: '睡眠・リカバリー',
    description: '睡眠の質向上やトレーニング後の回復方法',
    type: 'blog',
    brand_enum: 'fit365',
    order: 15,
    is_public: true,
  },
  {
    id: 'CAT-028',
    name: 'メンタルヘルス',
    description: '運動とメンタルヘルスの関係に関する記事',
    type: 'blog',
    brand_enum: 'joyfit_yoga',
    order: 16,
    is_public: false,
  },
  {
    id: 'CAT-029',
    name: '会員インタビュー',
    description: '会員の体験談やビフォーアフターインタビュー',
    type: 'blog',
    brand_enum: 'joyfit',
    order: 17,
    is_public: true,
  },
];

function buildMappings(counts: Record<string, number>): ArticleCategoryMapping[] {
  const rows: ArticleCategoryMapping[] = [];
  let n = 1;
  for (const [categoryId, count] of Object.entries(counts)) {
    for (let i = 0; i < count; i++) {
      rows.push({ article_id: `ART-${String(n++).padStart(4, '0')}`, category_id: categoryId });
    }
  }
  return rows;
}

export const SEED_ARTICLE_CATEGORY_MAPPINGS: ArticleCategoryMapping[] = buildMappings({
  'CAT-001': 12,
  'CAT-002': 8,
  'CAT-003': 5,
  'CAT-004': 24,
  'CAT-005': 18,
  'CAT-006': 15,
  'CAT-007': 11,
  'CAT-008': 7,
  'CAT-009': 9,
  'CAT-010': 3,
  'CAT-011': 0,
  'CAT-012': 6,
  'CAT-013': 2,
  'CAT-014': 14,
  'CAT-015': 4,
  'CAT-016': 1,
  'CAT-017': 20,
  'CAT-018': 0,
  'CAT-019': 3,
  'CAT-020': 17,
  'CAT-021': 10,
  'CAT-022': 6,
  'CAT-023': 13,
  'CAT-024': 22,
  'CAT-025': 5,
  'CAT-026': 8,
  'CAT-027': 16,
  'CAT-028': 2,
  'CAT-029': 9,
  'CAT-000': 0,
});
