import type { Banner, BannerBrandMapEntry } from '@/app/api/_schemas/banner.schema';

export const SEED_BANNERS: Banner[] = [
  {
    id: 'BN-001',
    order: 1,
    image_url: 'https://picsum.photos/seed/banner1/120/60',
    title: 'JOYFIT春キャンペーン2026',
    link_url: 'https://www.joyfit.jp/campaign/spring2026',
    period_start: '2026/04/01',
    period_end: '2026/04/30',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-002',
    order: 2,
    image_url: 'https://picsum.photos/seed/banner2/120/60',
    title: 'FIT365夏割キャンペーン',
    link_url: 'https://www.fit365.jp/summer',
    period_start: '2026/04/05',
    period_end: '2026/06/30',
    web_enabled: true,
    mobile_enabled: false,
  },
  {
    id: 'BN-003',
    order: 3,
    image_url: 'https://picsum.photos/seed/banner3/120/60',
    title: '新マシン導入告知',
    link_url: 'https://www.joyfit.jp/news/new-machine',
    period_start: '2026/05/01',
    period_end: '2026/05/31',
    web_enabled: false,
    mobile_enabled: true,
  },
  {
    id: 'BN-004',
    order: 4,
    image_url: 'https://picsum.photos/seed/banner4/120/60',
    title: 'JOYFITヨガ体験キャンペーン',
    link_url: 'https://www.joyfit.jp/yoga/trial',
    period_start: '2025/12/01',
    period_end: '2026/02/28',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-005',
    order: 5,
    image_url: 'https://picsum.photos/seed/banner5/120/60',
    title: 'JOYFIT+プレミアム会員募集',
    link_url: null,
    period_start: '2026/03/15',
    period_end: '2026/07/31',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-006',
    order: 6,
    image_url: 'https://picsum.photos/seed/banner6/120/60',
    title: 'アプリリニューアルのお知らせ',
    link_url: 'https://www.joyfit.jp/app',
    period_start: '2026/06/01',
    period_end: '2026/08/31',
    web_enabled: false,
    mobile_enabled: true,
  },
  {
    id: 'BN-007',
    order: 7,
    image_url: 'https://picsum.photos/seed/banner7/120/60',
    title: 'JOYFITスタジオプログラム新企画',
    link_url: 'https://www.joyfit.jp/studio',
    period_start: '2026/04/15',
    period_end: '2026/06/15',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-008',
    order: 8,
    image_url: 'https://picsum.photos/seed/banner8/120/60',
    title: 'FIT365冬の入会キャンペーン',
    link_url: 'https://www.fit365.jp/winter',
    period_start: '2025/12/01',
    period_end: '2026/01/31',
    web_enabled: true,
    mobile_enabled: false,
  },
  {
    id: 'BN-009',
    order: 9,
    image_url: 'https://picsum.photos/seed/banner9/120/60',
    title: '24時間ジム限定プランのご案内',
    link_url: null,
    period_start: '2026/05/01',
    period_end: '2026/09/30',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-010',
    order: 10,
    image_url: 'https://picsum.photos/seed/banner10/120/60',
    title: 'JOYFIT YOGA無料体験実施中',
    link_url: 'https://www.joyfit.jp/yoga/free-trial',
    period_start: '2026/03/01',
    period_end: '2026/05/31',
    web_enabled: false,
    mobile_enabled: true,
  },
  {
    id: 'BN-011',
    order: 11,
    image_url: 'https://picsum.photos/seed/banner11/120/60',
    title: 'JOYFIT+デジタル会員特典',
    link_url: 'https://www.joyfit.jp/plus/benefits',
    period_start: '2026/07/01',
    period_end: '2026/09/30',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-012',
    order: 12,
    image_url: 'https://picsum.photos/seed/banner12/120/60',
    title: 'ゴールデンウィーク特別キャンペーン',
    link_url: 'https://www.joyfit.jp/gw2026',
    period_start: '2026/04/25',
    period_end: '2026/05/10',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-013',
    order: 13,
    image_url: 'https://picsum.photos/seed/banner13/120/60',
    title: 'FIT365ペア入会割引',
    link_url: 'https://www.fit365.jp/pair',
    period_start: '2026/06/01',
    period_end: '2026/08/31',
    web_enabled: true,
    mobile_enabled: false,
  },
  {
    id: 'BN-014',
    order: 14,
    image_url: 'https://picsum.photos/seed/banner14/120/60',
    title: 'JOYFIT24会員限定イベント',
    link_url: 'https://www.joyfit24.jp/event',
    period_start: '2026/08/01',
    period_end: '2026/08/31',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-015',
    order: 15,
    image_url: 'https://picsum.photos/seed/banner15/120/60',
    title: 'ヨガマットプレゼントキャンペーン',
    link_url: 'https://www.joyfit.jp/yoga/mat-campaign',
    period_start: '2026/02/01',
    period_end: '2026/03/31',
    web_enabled: false,
    mobile_enabled: true,
  },
  {
    id: 'BN-016',
    order: 16,
    image_url: 'https://picsum.photos/seed/banner16/120/60',
    title: 'JOYFIT+プレミアムプラン紹介',
    link_url: 'https://www.joyfit.jp/plus/premium',
    period_start: '2026/09/01',
    period_end: '2026/12/31',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-017',
    order: 17,
    image_url: 'https://picsum.photos/seed/banner17/120/60',
    title: 'JOYFIT夏のキッズプログラム',
    link_url: 'https://www.joyfit.jp/kids-summer',
    period_start: '2026/07/01',
    period_end: '2026/08/31',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-018',
    order: 18,
    image_url: 'https://picsum.photos/seed/banner18/120/60',
    title: 'FIT365学生割引キャンペーン',
    link_url: 'https://www.fit365.jp/student',
    period_start: '2026/03/01',
    period_end: '2026/05/31',
    web_enabled: true,
    mobile_enabled: false,
  },
  {
    id: 'BN-019',
    order: 19,
    image_url: 'https://picsum.photos/seed/banner19/120/60',
    title: 'JOYFIT24新店舗オープン記念',
    link_url: 'https://www.joyfit24.jp/new-open',
    period_start: '2026/10/01',
    period_end: '2026/11/30',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-020',
    order: 20,
    image_url: 'https://picsum.photos/seed/banner20/120/60',
    title: 'JOYFIT YOGAオンラインレッスン',
    link_url: null,
    period_start: '2026/04/01',
    period_end: '2026/06/30',
    web_enabled: false,
    mobile_enabled: true,
  },
  {
    id: 'BN-021',
    order: 21,
    image_url: 'https://picsum.photos/seed/banner21/120/60',
    title: 'JOYFIT+夏のチャレンジ企画',
    link_url: 'https://www.joyfit.jp/plus/summer-challenge',
    period_start: '2026/06/15',
    period_end: '2026/09/15',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-022',
    order: 22,
    image_url: 'https://picsum.photos/seed/banner22/120/60',
    title: 'JOYFIT秋の入会キャンペーン',
    link_url: 'https://www.joyfit.jp/autumn2026',
    period_start: '2026/09/01',
    period_end: '2026/10/31',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-023',
    order: 23,
    image_url: 'https://picsum.photos/seed/banner23/120/60',
    title: 'FIT365友達紹介キャンペーン',
    link_url: 'https://www.fit365.jp/referral',
    period_start: '2026/05/01',
    period_end: '2026/07/31',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-024',
    order: 24,
    image_url: 'https://picsum.photos/seed/banner24/120/60',
    title: 'JOYFIT24パーソナルトレーニング',
    link_url: 'https://www.joyfit24.jp/pt',
    period_start: '2026/11/01',
    period_end: '2026/12/31',
    web_enabled: true,
    mobile_enabled: false,
  },
  {
    id: 'BN-025',
    order: 25,
    image_url: 'https://picsum.photos/seed/banner25/120/60',
    title: 'ホットヨガ冬の体験ウィーク',
    link_url: 'https://www.joyfit.jp/yoga/hot-yoga',
    period_start: '2025/11/01',
    period_end: '2025/12/31',
    web_enabled: false,
    mobile_enabled: true,
  },
  {
    id: 'BN-026',
    order: 26,
    image_url: 'https://picsum.photos/seed/banner26/120/60',
    title: 'JOYFIT+年額プランお得キャンペーン',
    link_url: null,
    period_start: '2026/01/01',
    period_end: '2026/03/31',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-027',
    order: 27,
    image_url: 'https://picsum.photos/seed/banner27/120/60',
    title: 'JOYFITグループレッスン新種目',
    link_url: 'https://www.joyfit.jp/lessons/new',
    period_start: '2026/07/15',
    period_end: '2026/09/30',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-028',
    order: 28,
    image_url: 'https://picsum.photos/seed/banner28/120/60',
    title: 'FIT365シルバー会員割引',
    link_url: 'https://www.fit365.jp/senior',
    period_start: '2026/04/01',
    period_end: '2026/06/30',
    web_enabled: false,
    mobile_enabled: false,
  },
  {
    id: 'BN-029',
    order: 29,
    image_url: 'https://picsum.photos/seed/banner29/120/60',
    title: 'JOYFIT24コンビニ会員特典',
    link_url: 'https://www.joyfit24.jp/conveni',
    period_start: '2026/02/01',
    period_end: '2026/04/30',
    web_enabled: true,
    mobile_enabled: true,
  },
  {
    id: 'BN-030',
    order: 30,
    image_url: 'https://picsum.photos/seed/banner30/120/60',
    title: '年末年始特別営業のお知らせ',
    link_url: 'https://www.joyfit.jp/holiday',
    period_start: '2026/12/25',
    period_end: '2027/01/05',
    web_enabled: true,
    mobile_enabled: true,
  },
];

export const BANNER_BRANDS_MAPPING: BannerBrandMapEntry[] = [
  { banner_id: 'BN-001', brand_enum: 'joyfit' },
  { banner_id: 'BN-002', brand_enum: 'fit365' },
  { banner_id: 'BN-002', brand_enum: 'joyfit24' },
  { banner_id: 'BN-003', brand_enum: 'joyfit_yoga' },
  { banner_id: 'BN-004', brand_enum: 'joyfit24' },
  { banner_id: 'BN-005', brand_enum: 'fit365' },
  { banner_id: 'BN-006', brand_enum: 'joyfit_plus' },
  { banner_id: 'BN-007', brand_enum: 'joyfit' },
  { banner_id: 'BN-008', brand_enum: 'fit365' },
  { banner_id: 'BN-009', brand_enum: 'joyfit24' },
  { banner_id: 'BN-010', brand_enum: 'joyfit_yoga' },
  { banner_id: 'BN-011', brand_enum: 'joyfit_plus' },
  { banner_id: 'BN-012', brand_enum: 'joyfit' },
  { banner_id: 'BN-013', brand_enum: 'fit365' },
  { banner_id: 'BN-014', brand_enum: 'joyfit24' },
  { banner_id: 'BN-015', brand_enum: 'joyfit_yoga' },
  { banner_id: 'BN-016', brand_enum: 'joyfit_plus' },
  { banner_id: 'BN-017', brand_enum: 'joyfit' },
  { banner_id: 'BN-018', brand_enum: 'fit365' },
  { banner_id: 'BN-019', brand_enum: 'joyfit24' },
  { banner_id: 'BN-020', brand_enum: 'joyfit_yoga' },
  { banner_id: 'BN-021', brand_enum: 'joyfit_plus' },
  { banner_id: 'BN-022', brand_enum: 'joyfit' },
  { banner_id: 'BN-023', brand_enum: 'fit365' },
  { banner_id: 'BN-024', brand_enum: 'joyfit24' },
  { banner_id: 'BN-025', brand_enum: 'joyfit_yoga' },
  { banner_id: 'BN-026', brand_enum: 'joyfit_plus' },
  { banner_id: 'BN-027', brand_enum: 'joyfit' },
  { banner_id: 'BN-028', brand_enum: 'fit365' },
  { banner_id: 'BN-029', brand_enum: 'joyfit24' },
  { banner_id: 'BN-030', brand_enum: 'joyfit' },
];
