/**
 * G-03 キャンペーン管理 / G-06 プロモーションコード管理のシード。
 *
 * 内容は V0 プロトタイプ (`campaign-list.tsx` / `campaign-detail.tsx` / `data/campaigns.ts`)
 * に合わせている。プロモーションコードの有効期間だけは、4種のステータス
 * (有効 / 期限切れ / 上限到達 / 無効) がすべて画面に現れるよう現在日付に対して相対配置する。
 */
import type {
  CampaignChangeHistoryItem,
  CampaignRow,
  StoreCampaignLinkRow,
} from '@/app/api/_schemas/campaign.schema';
import type { PromoCodeRow } from '@/app/api/_schemas/promo-code.schema';

/** 既定の操作者。変更履歴の生成時にも使うため table 側からも参照する。 */
export const HQ_ACTOR = '本部管理者';

type CampaignSeedSpec = Partial<CampaignRow> &
  Pick<
    CampaignRow,
    'id' | 'name' | 'brand_enum' | 'plan_id' | 'recruitment_start' | 'recruitment_end'
  >;

/** シードの冗長さを避けるため、既定値を埋めて完全な行にする。 */
function buildCampaignRow(spec: CampaignSeedSpec): CampaignRow {
  return {
    campaign_code: null,
    remarks: null,
    is_accepting: true,
    usage_start: null,
    usage_end: null,
    apply_start_month: null,
    apply_start_specific_n: null,
    apply_duration_months: null,
    plan_discount_month1: false,
    plan_discount_month1_type: null,
    plan_discount_month1_value: null,
    plan_discount_month2: false,
    plan_discount_month2_type: null,
    plan_discount_month2_value: null,
    option_discounts: [],
    auto_options: [],
    entry_cap: null,
    lock_in_months: null,
    publish_scope: 'all_stores',
    publish_store_ids: [],
    condition_option_ids: [],
    referral: {
      enabled: false,
      points: null,
      tieredIncrease: false,
      tierThreshold: null,
      tierPoints: null,
      annualReset: true,
    },
    active_contract_count: 0,
    pending_application_count: 0,
    monthly_new_application_count: 0,
    channel_mobile_count: 0,
    channel_manual_count: 0,
    channel_referral_count: 0,
    created_by: HQ_ACTOR,
    updated_by: HQ_ACTOR,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
    deleted_at: null,
    ...spec,
  };
}

/** 今日を基準に n 日ずらした YYYY-MM-DD を返す。 */
function dayOffset(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
}

export function buildCampaignSeed(): {
  campaigns: CampaignRow[];
  changeHistory: Record<string, CampaignChangeHistoryItem[]>;
  storeCampaignLinks: StoreCampaignLinkRow[];
  promoCodes: PromoCodeRow[];
} {
  const campaigns: CampaignRow[] = [
    buildCampaignRow({
      id: 'CP001',
      name: '春の入会キャンペーン',
      campaign_code: 'STR01-A1B2C',
      brand_enum: 'fit365',
      remarks:
        '春の入会促進として3月〜4月限定で実施。レギュラー・デイタイム会員向け。広告施策（Google/SNS）と連動予定。',
      is_accepting: true,
      recruitment_start: '2026-03-01',
      recruitment_end: '2026-04-30',
      usage_start: '2026-03-01',
      usage_end: '2026-04-30',
      apply_start_month: 'first_month',
      apply_duration_months: 2,
      plan_id: 'MC001',
      plan_discount_month1: true,
      plan_discount_month1_type: 'percentage',
      plan_discount_month1_value: 50,
      option_discounts: [
        {
          optionId: 'OP001',
          discountMonth1: true,
          discountMonth1Type: 'fixed_amount',
          discountMonth1Value: 500,
          discountMonth2: false,
          discountMonth2Type: null,
          discountMonth2Value: null,
        },
      ],
      auto_options: [
        { optionId: 'OP001', targetSexes: ['male', 'female'] },
        { optionId: 'OP002', targetSexes: ['male', 'female'] },
      ],
      entry_cap: 200,
      lock_in_months: 6,
      publish_scope: 'all_stores',
      condition_option_ids: ['OP001', 'OP006'],
      referral: {
        enabled: true,
        points: 1000,
        tieredIncrease: true,
        tierThreshold: 3,
        tierPoints: 2000,
        annualReset: true,
      },
      active_contract_count: 128,
      pending_application_count: 142,
      monthly_new_application_count: 23,
      channel_mobile_count: 79,
      channel_manual_count: 34,
      channel_referral_count: 15,
      created_by: '田中 花子',
      updated_by: '田中 花子',
      created_at: '2026-02-15T10:30:00.000Z',
      updated_at: '2026-03-10T14:20:00.000Z',
    }),
    buildCampaignRow({
      id: 'CP002',
      name: '友達紹介キャンペーン',
      campaign_code: 'ALL2026',
      brand_enum: 'fit365',
      remarks: '紹介経由の新規会員獲得キャンペーン。通年実施。',
      recruitment_start: '2026-01-01',
      recruitment_end: '2026-12-31',
      usage_start: '2026-01-01',
      usage_end: '2026-12-31',
      apply_start_month: 'first_month',
      apply_duration_months: 3,
      plan_id: 'MC001',
      plan_discount_month1: true,
      plan_discount_month1_type: 'fixed_amount',
      plan_discount_month1_value: 1000,
      plan_discount_month2: true,
      plan_discount_month2_type: 'fixed_amount',
      plan_discount_month2_value: 1000,
      referral: {
        enabled: true,
        points: 1000,
        tieredIncrease: false,
        tierThreshold: null,
        tierPoints: null,
        annualReset: true,
      },
      active_contract_count: 45,
      pending_application_count: 18,
      monthly_new_application_count: 6,
      channel_mobile_count: 30,
      channel_manual_count: 4,
      channel_referral_count: 11,
      created_at: '2026-01-01T08:00:00.000Z',
      updated_at: '2026-05-20T11:10:00.000Z',
    }),
    buildCampaignRow({
      id: 'CP003',
      name: '法人割引キャンペーン',
      campaign_code: 'STR02-E5F6G',
      brand_enum: 'fit365',
      remarks: '提携法人向けの月額割引。',
      recruitment_start: '2026-04-01',
      recruitment_end: '2026-09-30',
      usage_start: '2026-04-01',
      usage_end: '2026-10-31',
      apply_start_month: 'next_month',
      apply_duration_months: 12,
      plan_id: 'MC007',
      plan_discount_month1: true,
      plan_discount_month1_type: 'percentage',
      plan_discount_month1_value: 10,
      plan_discount_month2: true,
      plan_discount_month2_type: 'percentage',
      plan_discount_month2_value: 10,
      publish_scope: 'specific_stores',
      publish_store_ids: ['store-002', 'store-003'],
      created_at: '2026-03-15T09:00:00.000Z',
      updated_at: '2026-05-12T10:05:00.000Z',
    }),
    buildCampaignRow({
      id: 'CP004',
      name: '新店オープン記念',
      campaign_code: 'OPEN2025',
      brand_enum: 'joyfit',
      remarks: '新店オープン記念の店舗独自キャンペーン。',
      is_accepting: false,
      recruitment_start: '2025-10-01',
      recruitment_end: '2025-12-31',
      usage_start: '2025-10-01',
      usage_end: '2026-01-31',
      apply_start_month: 'first_month',
      apply_duration_months: 2,
      plan_id: 'MC001',
      plan_discount_month1: true,
      plan_discount_month1_type: 'fixed_amount',
      plan_discount_month1_value: 2000,
      plan_discount_month2: true,
      plan_discount_month2_type: 'fixed_amount',
      plan_discount_month2_value: 2000,
      lock_in_months: 12,
      publish_scope: 'specific_stores',
      publish_store_ids: ['store-004'],
      active_contract_count: 210,
      pending_application_count: 0,
      channel_mobile_count: 150,
      channel_manual_count: 60,
      created_at: '2025-09-01T10:00:00.000Z',
      updated_at: '2025-12-20T17:30:00.000Z',
    }),
    buildCampaignRow({
      id: 'CP005',
      name: '夏のボディメイクキャンペーン',
      campaign_code: 'SUMMER26',
      brand_enum: 'fit365',
      remarks: 'パーソナルトレーニング体験を含む夏季施策。先着50名。',
      recruitment_start: '2026-06-01',
      recruitment_end: '2026-08-31',
      usage_start: '2026-06-01',
      usage_end: '2026-09-30',
      apply_start_month: 'first_month',
      apply_duration_months: 3,
      plan_id: 'MC009',
      auto_options: [{ optionId: 'OP011', targetSexes: null }],
      entry_cap: 50,
      active_contract_count: 50,
      pending_application_count: 50,
      monthly_new_application_count: 12,
      channel_mobile_count: 38,
      channel_manual_count: 12,
      created_at: '2026-05-01T09:00:00.000Z',
      updated_at: '2026-06-20T15:00:00.000Z',
    }),
    buildCampaignRow({
      id: 'CP006',
      name: '年末特別割引',
      campaign_code: 'STR01-K1L2M',
      brand_enum: 'fit365',
      remarks: '12月入会で1月分無料。',
      is_accepting: false,
      recruitment_start: '2025-12-01',
      recruitment_end: '2025-12-31',
      usage_start: '2025-12-01',
      usage_end: '2026-01-31',
      apply_start_month: 'next_month',
      apply_duration_months: 1,
      plan_id: 'MC001',
      plan_discount_month2: true,
      plan_discount_month2_type: 'percentage',
      plan_discount_month2_value: 100,
      active_contract_count: 85,
      channel_mobile_count: 55,
      channel_manual_count: 30,
      created_at: '2025-11-01T13:15:00.000Z',
      updated_at: '2025-12-05T11:40:00.000Z',
    }),
    buildCampaignRow({
      id: 'CP007',
      name: '秋の入会準備キャンペーン',
      campaign_code: 'STR01-Q7R8S',
      brand_enum: 'fit365',
      remarks: '入会金半額。特定店舗限定で先行実施。',
      recruitment_start: '2026-09-01',
      recruitment_end: '2026-11-30',
      usage_start: '2026-09-01',
      usage_end: '2026-12-31',
      apply_start_month: 'specific_month',
      apply_start_specific_n: 3,
      apply_duration_months: 2,
      plan_id: 'MC001',
      plan_discount_month1: true,
      plan_discount_month1_type: 'percentage',
      plan_discount_month1_value: 50,
      lock_in_months: 3,
      publish_scope: 'specific_stores',
      publish_store_ids: ['store-001'],
      created_at: '2026-06-15T10:00:00.000Z',
      updated_at: '2026-06-15T10:00:00.000Z',
    }),
  ];

  // V0 `HistoryTab` のモックをそのまま再現 (PAR163〜PAR169)
  const changeHistory: Record<string, CampaignChangeHistoryItem[]> = {
    CP001: [
      {
        date: '2026-03-10T14:20:00.000Z',
        user: '田中 花子',
        field: '月額割引',
        from: '初月30%OFF',
        to: '初月50%OFF',
      },
      {
        date: '2026-03-05T09:15:00.000Z',
        user: '田中 花子',
        field: '対象契約',
        from: 'レギュラー会員のみ',
        to: 'レギュラー会員, デイタイム会員',
      },
      {
        date: '2026-02-20T16:45:00.000Z',
        user: '山田 太郎',
        field: '入会金割引',
        from: '50%免除',
        to: '100%免除',
      },
      {
        date: '2026-02-15T10:30:00.000Z',
        user: '田中 花子',
        field: null,
        from: null,
        to: '新規作成',
      },
    ],
    CP002: [
      {
        date: '2026-05-20T11:10:00.000Z',
        user: HQ_ACTOR,
        field: '備考',
        from: '紹介経由の施策',
        to: '紹介経由の新規会員獲得キャンペーン',
      },
      {
        date: '2026-01-01T08:00:00.000Z',
        user: HQ_ACTOR,
        field: null,
        from: null,
        to: '新規作成',
      },
    ],
    CP003: [
      {
        date: '2026-05-12T10:05:00.000Z',
        user: '田中 花子',
        field: '適用主契約',
        from: '一般会員',
        to: '法人会員',
      },
      {
        date: '2026-03-15T09:00:00.000Z',
        user: '田中 花子',
        field: null,
        from: null,
        to: '新規作成',
      },
    ],
    CP004: [
      {
        date: '2025-12-20T17:30:00.000Z',
        user: '店舗開店準備室',
        field: '受付可否',
        from: '受付中',
        to: '受付停止',
      },
    ],
    CP005: [],
    CP006: [
      {
        date: '2025-12-05T11:40:00.000Z',
        user: HQ_ACTOR,
        field: '受付可否',
        from: '受付中',
        to: '受付停止',
      },
    ],
    CP007: [],
  };

  // V0 `data/store-campaign-bindings.ts` 相当。八潮店 (store-001) を現在店舗と見なす。
  const storeCampaignLinks: StoreCampaignLinkRow[] = [
    {
      store_id: 'store-001',
      campaign_id: 'CP001',
      linked_at: '2026-02-20',
      linked_by: HQ_ACTOR,
      created_at: '2026-02-20T00:00:00.000Z',
    },
    {
      store_id: 'store-001',
      campaign_id: 'CP005',
      linked_at: '2026-05-28',
      linked_by: HQ_ACTOR,
      created_at: '2026-05-28T00:00:00.000Z',
    },
    {
      store_id: 'store-001',
      campaign_id: 'CP006',
      linked_at: '2025-11-20',
      linked_by: HQ_ACTOR,
      created_at: '2025-11-20T00:00:00.000Z',
    },
    {
      store_id: 'store-002',
      campaign_id: 'CP003',
      linked_at: '2026-04-01',
      linked_by: HQ_ACTOR,
      created_at: '2026-04-01T00:00:00.000Z',
    },
  ];

  // V0 `PROMO_CODES` を再現。有効期間だけは 4 ステータスがすべて現れるよう現在日基準に配置する。
  const promoCodes: PromoCodeRow[] = [
    {
      id: 'PC001',
      code: 'SPRING2026',
      campaign_id: 'CP001',
      brand_enum: 'fit365',
      scope_type: 'brand_all',
      issued_store_id: null,
      generation_method: 'manual',
      description: 'Google広告用',
      valid_from: dayOffset(-30),
      valid_to: dayOffset(60),
      max_uses: null,
      used_count: 45,
      status: 'active',
      disabled_reason: null,
      created_by: 'staff-hq-001',
      created_by_name: '本部',
      created_at: '2026-02-20T09:00:00.000Z',
      updated_at: '2026-02-20T09:00:00.000Z',
    },
    {
      id: 'PC002',
      code: 'SNS-SPRING',
      campaign_id: 'CP001',
      brand_enum: 'fit365',
      scope_type: 'brand_all',
      issued_store_id: null,
      generation_method: 'manual',
      description: 'Instagram・X用',
      valid_from: dayOffset(-20),
      valid_to: dayOffset(40),
      max_uses: 100,
      used_count: 100,
      status: 'active',
      disabled_reason: null,
      created_by: 'staff-hq-001',
      created_by_name: '本部',
      created_at: '2026-02-20T09:30:00.000Z',
      updated_at: '2026-02-20T09:30:00.000Z',
    },
    {
      id: 'PC003',
      code: 'FLYER-SPR26',
      campaign_id: 'CP001',
      brand_enum: 'fit365',
      scope_type: 'issuer_store_only',
      issued_store_id: 'store-001',
      generation_method: 'auto',
      description: '店頭配布チラシ',
      valid_from: '2026-03-01',
      valid_to: '2026-03-31',
      max_uses: 200,
      used_count: 32,
      status: 'active',
      disabled_reason: null,
      created_by: 'staff-store-001',
      created_by_name: '店舗スタッフ',
      created_at: '2026-02-25T11:00:00.000Z',
      updated_at: '2026-02-25T11:00:00.000Z',
    },
    {
      id: 'PC004',
      code: 'MAIL-VIP',
      campaign_id: 'CP001',
      brand_enum: 'fit365',
      scope_type: 'issuer_store_only',
      issued_store_id: 'store-001',
      generation_method: 'manual',
      description: '既存会員向けDM',
      valid_from: dayOffset(7),
      valid_to: dayOffset(37),
      max_uses: 50,
      used_count: 13,
      status: 'active',
      disabled_reason: null,
      created_by: 'staff-store-001',
      created_by_name: '店舗スタッフ',
      created_at: '2026-03-01T10:00:00.000Z',
      updated_at: '2026-03-01T10:00:00.000Z',
    },
    {
      id: 'PC005',
      code: 'TEST-SPRING',
      campaign_id: 'CP001',
      brand_enum: 'fit365',
      scope_type: 'issuer_store_only',
      issued_store_id: 'store-001',
      generation_method: 'auto',
      description: '内部テスト用',
      valid_from: dayOffset(-60),
      valid_to: dayOffset(30),
      max_uses: 5,
      used_count: 2,
      status: 'disabled',
      disabled_reason: '内部テスト完了のため無効化',
      created_by: 'staff-store-001',
      created_by_name: '店舗スタッフ',
      created_at: '2026-02-15T14:00:00.000Z',
      updated_at: '2026-02-28T09:00:00.000Z',
    },
    {
      id: 'PC006',
      code: 'OGF-X9Y8Z',
      campaign_id: 'CP002',
      brand_enum: 'fit365',
      scope_type: 'ogf_only',
      issued_store_id: null,
      generation_method: 'manual',
      description: 'OGF会員向け通年コード',
      valid_from: '2026-01-01',
      valid_to: '2026-12-31',
      max_uses: null,
      used_count: 27,
      status: 'active',
      disabled_reason: null,
      created_by: 'staff-hq-001',
      created_by_name: '本部',
      created_at: '2026-01-01T08:00:00.000Z',
      updated_at: '2026-01-01T08:00:00.000Z',
    },
  ];

  return { campaigns, changeHistory, storeCampaignLinks, promoCodes };
}
