import type {
  ChangeHistory,
  LessonContentDetail,
  ScheduleSummary,
} from '@/app/api/_schemas/lesson-content-detail.schema';
import type { LessonContentItem, PersonalPlanItem } from '@/app/api/_schemas/lesson-content.schema';
import type {
  AttendanceStatus,
  CancelType,
  Reservation,
  ReservationStatus,
  SessionMemo,
  StudioSpaceGridResponse,
} from '@/app/api/_schemas/lesson-reservation.schema';
import type { LessonScheduleListItem } from '@/app/api/_schemas/lesson-schedule.schema';

import {
  GetStudioDetailResponse,
  type StudioChangeHistoryEntry,
} from '../../_schemas/studio-detail.schema';

export const LESSON_SCHEDULE_STORE_AREAS: Record<string, string> = {
  ST001: '埼玉',
  ST002: '東京',
  ST003: '東京',
  ST004: '東京',
  ST005: '東京',
  ST006: '埼玉',
  ST007: '北海道',
};

type LessonScheduleSeedSpec = {
  store_id: string;
  store_name: string;
  start: string;
  end: string;
  lesson_name: string;
  studio_name: string | null;
  lesson_type: 'studio' | 'personal';
  instructor_id: string;
  instructor_name: string;
  capacity: number;
  booked_count: number;
  waiting_count?: number;
  status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
  payment_status: 'paid' | 'unpaid' | 'partial';
  is_alert?: boolean;
  booked_members?: Array<{ member_id: string; name: string }>;
};

function lsFormatDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function lsWeekStart(from = new Date()): Date {
  const d = new Date(from);
  const diff = (d.getDay() + 6) % 7;
  d.setDate(d.getDate() - diff);
  return d;
}

function lsToIso(dateStr: string, time: string): string {
  const [h, m = '00'] = time.split(':');
  return `${dateStr}T${h.padStart(2, '0')}:${m.padStart(2, '0')}:00+09:00`;
}

function getLessonScheduleDayTemplates(): LessonScheduleSeedSpec[] {
  return [
    {
      store_id: 'ST001',
      store_name: 'FIT365八潮店',
      start: '9:00',
      end: '10:00',
      lesson_name: 'ヨガ基礎クラス',
      studio_name: 'Zumbaスタジオ',
      lesson_type: 'studio',
      instructor_id: 'U-004',
      instructor_name: 'タムタ タム',
      capacity: 16,
      booked_count: 14,
      status: 'completed',
      payment_status: 'paid',
      booked_members: [
        { member_id: 'M101', name: '田中 花子' },
        { member_id: 'M102', name: '佐藤 一郎' },
        { member_id: 'M103', name: '山田 太郎' },
      ],
    },
    {
      store_id: 'ST001',
      store_name: 'FIT365八潮店',
      start: '10:30',
      end: '11:30',
      lesson_name: 'ホットヨガ リフレッシュ',
      studio_name: 'ホットヨガスタジオA',
      lesson_type: 'studio',
      instructor_id: 'S002',
      instructor_name: '鈴木 美咲',
      capacity: 35,
      booked_count: 35,
      waiting_count: 4,
      status: 'completed',
      payment_status: 'paid',
      is_alert: true,
    },
    {
      store_id: 'ST001',
      store_name: 'FIT365八潮店',
      start: '13:00',
      end: '14:00',
      lesson_name: 'ボディコンバット',
      studio_name: 'メインスタジオ',
      lesson_type: 'studio',
      instructor_id: 'S003',
      instructor_name: '高橋 咲',
      capacity: 17,
      booked_count: 10,
      status: 'in_progress',
      payment_status: 'paid',
      is_alert: true,
    },
    {
      store_id: 'ST001',
      store_name: 'FIT365八潮店',
      start: '14:00',
      end: '15:00',
      lesson_name: 'パーソナル：渡辺様',
      studio_name: 'パーソナルブースA',
      lesson_type: 'personal',
      instructor_id: 'S004',
      instructor_name: '山田 太郎',
      capacity: 1,
      booked_count: 1,
      status: 'scheduled',
      payment_status: 'paid',
    },
    {
      store_id: 'ST001',
      store_name: 'FIT365八潮店',
      start: '16:00',
      end: '17:00',
      lesson_name: 'パーソナル：中村様',
      studio_name: 'パーソナルブースB',
      lesson_type: 'personal',
      instructor_id: 'S005',
      instructor_name: '佐藤 健太',
      capacity: 1,
      booked_count: 1,
      status: 'scheduled',
      payment_status: 'unpaid',
    },
    {
      store_id: 'ST001',
      store_name: 'FIT365八潮店',
      start: '18:00',
      end: '19:00',
      lesson_name: 'リラックスストレッチ',
      studio_name: 'Zumbaスタジオ',
      lesson_type: 'studio',
      instructor_id: 'U-004',
      instructor_name: 'タムタ タム',
      capacity: 16,
      booked_count: 5,
      status: 'scheduled',
      payment_status: 'paid',
      is_alert: true,
      booked_members: [
        { member_id: 'M104', name: '木村 拓也' },
        { member_id: 'M105', name: '森田 健一' },
        { member_id: 'M106', name: '藤井 優' },
      ],
    },
    {
      store_id: 'ST002',
      store_name: 'JOYFIT渋谷店',
      start: '8:00',
      end: '9:00',
      lesson_name: 'モーニングヨガ',
      studio_name: 'スタジオA',
      lesson_type: 'studio',
      instructor_id: 'S003',
      instructor_name: '高橋 咲',
      capacity: 18,
      booked_count: 16,
      status: 'completed',
      payment_status: 'paid',
    },
    {
      store_id: 'ST002',
      store_name: 'JOYFIT渋谷店',
      start: '10:00',
      end: '11:00',
      lesson_name: 'ピラティス入門',
      studio_name: 'スタジオB',
      lesson_type: 'studio',
      instructor_id: 'S002',
      instructor_name: '鈴木 美咲',
      capacity: 20,
      booked_count: 18,
      status: 'completed',
      payment_status: 'paid',
    },
    {
      store_id: 'ST002',
      store_name: 'JOYFIT渋谷店',
      start: '11:30',
      end: '12:30',
      lesson_name: 'ZUMBA エナジー',
      studio_name: 'スタジオA',
      lesson_type: 'studio',
      instructor_id: 'U-004',
      instructor_name: 'タムタ タム',
      capacity: 24,
      booked_count: 22,
      status: 'completed',
      payment_status: 'paid',
    },
    {
      store_id: 'ST002',
      store_name: 'JOYFIT渋谷店',
      start: '13:30',
      end: '14:30',
      lesson_name: 'ヨガフロー',
      studio_name: 'スタジオB',
      lesson_type: 'studio',
      instructor_id: 'S002',
      instructor_name: '鈴木 美咲',
      capacity: 20,
      booked_count: 19,
      status: 'in_progress',
      payment_status: 'paid',
    },
    {
      store_id: 'ST002',
      store_name: 'JOYFIT渋谷店',
      start: '15:00',
      end: '16:00',
      lesson_name: 'パーソナル：佐々木様',
      studio_name: 'PTルーム1',
      lesson_type: 'personal',
      instructor_id: 'S006',
      instructor_name: '田中 優太',
      capacity: 1,
      booked_count: 1,
      status: 'scheduled',
      payment_status: 'paid',
    },
    {
      store_id: 'ST002',
      store_name: 'JOYFIT渋谷店',
      start: '17:00',
      end: '18:00',
      lesson_name: 'ボディコンバット',
      studio_name: 'スタジオA',
      lesson_type: 'studio',
      instructor_id: 'S003',
      instructor_name: '高橋 咲',
      capacity: 24,
      booked_count: 20,
      status: 'scheduled',
      payment_status: 'paid',
    },
    {
      store_id: 'ST002',
      store_name: 'JOYFIT渋谷店',
      start: '19:00',
      end: '20:00',
      lesson_name: 'ナイトピラティス',
      studio_name: 'スタジオB',
      lesson_type: 'studio',
      instructor_id: 'S002',
      instructor_name: '鈴木 美咲',
      capacity: 20,
      booked_count: 18,
      status: 'scheduled',
      payment_status: 'paid',
    },
    {
      store_id: 'ST002',
      store_name: 'JOYFIT渋谷店',
      start: '20:30',
      end: '21:30',
      lesson_name: 'パーソナル：木村様',
      studio_name: 'PTルーム2',
      lesson_type: 'personal',
      instructor_id: 'S006',
      instructor_name: '田中 優太',
      capacity: 1,
      booked_count: 1,
      status: 'scheduled',
      payment_status: 'unpaid',
    },
    {
      store_id: 'ST003',
      store_name: 'JOYFIT新宿店',
      start: '10:00',
      end: '11:00',
      lesson_name: 'ヨガ基礎クラス',
      studio_name: 'スタジオA',
      lesson_type: 'studio',
      instructor_id: 'S007',
      instructor_name: '佐藤 花',
      capacity: 18,
      booked_count: 11,
      status: 'completed',
      payment_status: 'paid',
    },
    {
      store_id: 'ST003',
      store_name: 'JOYFIT新宿店',
      start: '12:00',
      end: '13:00',
      lesson_name: 'パワーヨガ',
      studio_name: 'スタジオB',
      lesson_type: 'studio',
      instructor_id: 'S007',
      instructor_name: '佐藤 花',
      capacity: 20,
      booked_count: 14,
      status: 'completed',
      payment_status: 'paid',
      is_alert: true,
    },
    {
      store_id: 'ST003',
      store_name: 'JOYFIT新宿店',
      start: '15:00',
      end: '16:00',
      lesson_name: 'パーソナル：藤井様',
      studio_name: 'PTルーム',
      lesson_type: 'personal',
      instructor_id: 'S008',
      instructor_name: '伊藤 麻衣',
      capacity: 1,
      booked_count: 1,
      status: 'scheduled',
      payment_status: 'paid',
    },
    {
      store_id: 'ST003',
      store_name: 'JOYFIT新宿店',
      start: '17:30',
      end: '18:30',
      lesson_name: 'ストレッチ',
      studio_name: 'スタジオA',
      lesson_type: 'studio',
      instructor_id: 'S007',
      instructor_name: '佐藤 花',
      capacity: 18,
      booked_count: 12,
      status: 'scheduled',
      payment_status: 'partial',
    },
    {
      store_id: 'ST003',
      store_name: 'JOYFIT新宿店',
      start: '19:00',
      end: '20:00',
      lesson_name: 'ZUMBA フィットネス',
      studio_name: 'スタジオB',
      lesson_type: 'studio',
      instructor_id: 'S007',
      instructor_name: '佐藤 花',
      capacity: 20,
      booked_count: 16,
      status: 'scheduled',
      payment_status: 'paid',
    },
    {
      store_id: 'ST004',
      store_name: 'JOYFIT24六本木店',
      start: '9:00',
      end: '10:00',
      lesson_name: 'ピラティス基礎',
      studio_name: 'メインスタジオ',
      lesson_type: 'studio',
      instructor_id: 'S009',
      instructor_name: '小林 真理',
      capacity: 12,
      booked_count: 8,
      status: 'completed',
      payment_status: 'paid',
    },
    {
      store_id: 'ST004',
      store_name: 'JOYFIT24六本木店',
      start: '13:00',
      end: '14:00',
      lesson_name: 'ピラティス',
      studio_name: 'メインスタジオ',
      lesson_type: 'studio',
      instructor_id: 'S009',
      instructor_name: '小林 真理',
      capacity: 12,
      booked_count: 9,
      status: 'in_progress',
      payment_status: 'paid',
    },
    {
      store_id: 'ST004',
      store_name: 'JOYFIT24六本木店',
      start: '16:00',
      end: '17:00',
      lesson_name: 'パーソナル：田村様',
      studio_name: 'PTルーム',
      lesson_type: 'personal',
      instructor_id: 'S010',
      instructor_name: '渡辺 大輝',
      capacity: 1,
      booked_count: 1,
      status: 'scheduled',
      payment_status: 'paid',
    },
    {
      store_id: 'ST004',
      store_name: 'JOYFIT24六本木店',
      start: '18:30',
      end: '19:30',
      lesson_name: 'リラックスヨガ',
      studio_name: 'メインスタジオ',
      lesson_type: 'studio',
      instructor_id: 'S009',
      instructor_name: '小林 真理',
      capacity: 12,
      booked_count: 6,
      status: 'scheduled',
      payment_status: 'paid',
    },
    {
      store_id: 'ST005',
      store_name: 'FIT365吉祥寺店',
      start: '9:30',
      end: '10:30',
      lesson_name: 'ヨガ基礎',
      studio_name: 'スタジオA',
      lesson_type: 'studio',
      instructor_id: 'U-004',
      instructor_name: 'タムタ タム',
      capacity: 18,
      booked_count: 15,
      status: 'completed',
      payment_status: 'paid',
      is_alert: true,
    },
    {
      store_id: 'ST005',
      store_name: 'FIT365吉祥寺店',
      start: '11:00',
      end: '12:00',
      lesson_name: 'ホットヨガ',
      studio_name: 'ホットスタジオ',
      lesson_type: 'studio',
      instructor_id: 'S002',
      instructor_name: '鈴木 美咲',
      capacity: 30,
      booked_count: 28,
      status: 'completed',
      payment_status: 'paid',
      is_alert: true,
    },
    {
      store_id: 'ST005',
      store_name: 'FIT365吉祥寺店',
      start: '13:00',
      end: '14:00',
      lesson_name: 'ZUMBA',
      studio_name: 'スタジオA',
      lesson_type: 'studio',
      instructor_id: 'U-004',
      instructor_name: 'タムタ タム',
      capacity: 20,
      booked_count: 17,
      status: 'completed',
      payment_status: 'paid',
    },
    {
      store_id: 'ST005',
      store_name: 'FIT365吉祥寺店',
      start: '14:30',
      end: '15:30',
      lesson_name: 'パーソナル：高田様',
      studio_name: 'PTルーム1',
      lesson_type: 'personal',
      instructor_id: 'S006',
      instructor_name: '田中 優太',
      capacity: 1,
      booked_count: 1,
      status: 'scheduled',
      payment_status: 'unpaid',
    },
    {
      store_id: 'ST005',
      store_name: 'FIT365吉祥寺店',
      start: '16:00',
      end: '17:00',
      lesson_name: 'ピラティス',
      studio_name: 'スタジオB',
      lesson_type: 'studio',
      instructor_id: 'S002',
      instructor_name: '鈴木 美咲',
      capacity: 20,
      booked_count: 18,
      status: 'scheduled',
      payment_status: 'paid',
      is_alert: true,
    },
    {
      store_id: 'ST005',
      store_name: 'FIT365吉祥寺店',
      start: '18:00',
      end: '19:00',
      lesson_name: 'ボディコンバット',
      studio_name: 'スタジオA',
      lesson_type: 'studio',
      instructor_id: 'S003',
      instructor_name: '高橋 咲',
      capacity: 18,
      booked_count: 14,
      status: 'scheduled',
      payment_status: 'paid',
    },
    {
      store_id: 'ST005',
      store_name: 'FIT365吉祥寺店',
      start: '20:00',
      end: '21:00',
      lesson_name: 'ナイトストレッチ',
      studio_name: 'スタジオB',
      lesson_type: 'studio',
      instructor_id: 'S002',
      instructor_name: '鈴木 美咲',
      capacity: 20,
      booked_count: 10,
      status: 'scheduled',
      payment_status: 'paid',
    },
    {
      store_id: 'ST006',
      store_name: 'FIT365大宮店',
      start: '10:00',
      end: '11:00',
      lesson_name: '朝ヨガ',
      studio_name: 'スタジオA',
      lesson_type: 'studio',
      instructor_id: 'S007',
      instructor_name: '佐藤 花',
      capacity: 18,
      booked_count: 10,
      status: 'completed',
      payment_status: 'paid',
    },
    {
      store_id: 'ST006',
      store_name: 'FIT365大宮店',
      start: '13:15',
      end: '14:15',
      lesson_name: 'ZUMBA',
      studio_name: 'スタジオA',
      lesson_type: 'studio',
      instructor_id: 'S007',
      instructor_name: '佐藤 花',
      capacity: 20,
      booked_count: 8,
      status: 'in_progress',
      payment_status: 'paid',
    },
    {
      store_id: 'ST006',
      store_name: 'FIT365大宮店',
      start: '18:00',
      end: '19:00',
      lesson_name: 'パーソナル：松本様',
      studio_name: 'PTルーム',
      lesson_type: 'personal',
      instructor_id: 'S008',
      instructor_name: '伊藤 麻衣',
      capacity: 1,
      booked_count: 1,
      status: 'scheduled',
      payment_status: 'paid',
    },
    {
      store_id: 'ST007',
      store_name: '旭川アモール',
      start: '14:00',
      end: '15:00',
      lesson_name: 'パーソナル：渡辺様',
      studio_name: 'パーソナルブースA',
      lesson_type: 'personal',
      instructor_id: 'U-004',
      instructor_name: 'タムタ タム',
      capacity: 1,
      booked_count: 1,
      status: 'scheduled',
      payment_status: 'paid',
      booked_members: [{ member_id: 'M107', name: '渡辺 直美' }],
    },
    {
      store_id: 'ST001',
      store_name: 'FIT365八潮店',
      start: '20:00',
      end: '21:00',
      lesson_name: 'ナイトヨガ',
      studio_name: 'Zumbaスタジオ',
      lesson_type: 'studio',
      instructor_id: 'S002',
      instructor_name: '鈴木 美咲',
      capacity: 16,
      booked_count: 0,
      status: 'scheduled',
      payment_status: 'paid',
      is_alert: true,
    },
    {
      store_id: 'ST003',
      store_name: 'JOYFIT新宿店',
      start: '21:00',
      end: '22:00',
      lesson_name: 'ナイトヨガ',
      studio_name: 'スタジオA',
      lesson_type: 'studio',
      instructor_id: 'S007',
      instructor_name: '佐藤 花',
      capacity: 18,
      booked_count: 6,
      status: 'cancelled',
      payment_status: 'paid',
    },
  ];
}

function lessonSeedToRow(
  spec: LessonScheduleSeedSpec,
  dateStr: string,
  id: number,
  statusOverride?: LessonScheduleSeedSpec['status'],
): LessonScheduleListItem {
  const status = statusOverride ?? spec.status;
  return {
    id: `LS${String(id).padStart(4, '0')}`,
    lesson_name: spec.lesson_name,
    lesson_type: spec.lesson_type,
    studio_name: spec.studio_name,
    instructor_id: spec.instructor_id,
    instructor_name: spec.instructor_name,
    store_id: spec.store_id,
    store_name: spec.store_name,
    start_time: lsToIso(dateStr, spec.start),
    end_time: lsToIso(dateStr, spec.end),
    capacity: spec.capacity,
    booked_count: status === 'cancelled' ? 0 : spec.booked_count,
    waiting_count: spec.waiting_count ?? 0,
    payment_status: spec.payment_status,
    status,
    is_alert: spec.is_alert ?? false,
    booked_members: spec.booked_members,
  };
}

function makeLessonSchedules(): LessonScheduleListItem[] {
  const schedules: LessonScheduleListItem[] = [];
  let id = 1;
  const today = new Date();
  const todayStr = lsFormatDate(today);
  const weekStart = lsWeekStart(today);
  const dayTemplates = getLessonScheduleDayTemplates();

  dayTemplates.forEach((spec) => {
    schedules.push(lessonSeedToRow(spec, todayStr, id++));
  });

  for (let dayOffset = 0; dayOffset < 7; dayOffset++) {
    const date = new Date(weekStart);
    date.setDate(date.getDate() + dayOffset);
    const dateStr = lsFormatDate(date);
    if (dateStr === todayStr) continue;

    dayTemplates
      .filter((spec) => spec.status !== 'cancelled')
      .slice(0, 12)
      .forEach((spec, idx) => {
        schedules.push(
          lessonSeedToRow(
            {
              ...spec,
              booked_count: Math.max(1, spec.booked_count - (idx % 3)),
              is_alert: false,
              booked_members: undefined,
            },
            dateStr,
            id++,
            'scheduled',
          ),
        );
      });
  }

  return schedules;
}

export const SEED_LESSON_SCHEDULES: LessonScheduleListItem[] = makeLessonSchedules();

export const SEED_RESERVATION_INSTRUCTORS: Array<{
  instructor_id: string;
  instructor_name: string;
  store_id: string;
}> = [
  { instructor_id: 'U-004', instructor_name: 'タムタ タム', store_id: 'ST001' },
  { instructor_id: 'S002', instructor_name: '鈴木 美咲', store_id: 'ST001' },
  { instructor_id: 'S003', instructor_name: '高橋 咲', store_id: 'ST001' },
  { instructor_id: 'S004', instructor_name: '山田 太郎', store_id: 'ST001' },
  { instructor_id: 'S005', instructor_name: '佐藤 健太', store_id: 'ST001' },
  { instructor_id: 'S006', instructor_name: '田中 優太', store_id: 'ST002' },
  { instructor_id: 'S007', instructor_name: '佐藤 花', store_id: 'ST003' },
  { instructor_id: 'S008', instructor_name: '伊藤 麻衣', store_id: 'ST003' },
  { instructor_id: 'S009', instructor_name: '小林 真理', store_id: 'ST004' },
  { instructor_id: 'S010', instructor_name: '渡辺 大輝', store_id: 'ST004' },
];

export const SEED_LESSONS: Array<{
  id: string;
  name: string;
  lesson_type: 'studio' | 'personal';
  duration: number;
}> = [
  { id: 'LSN-001', name: 'ヨガ入門', lesson_type: 'studio', duration: 60 },
  { id: 'LSN-002', name: 'ヨガ中級', lesson_type: 'studio', duration: 60 },
  { id: 'LSN-003', name: 'ピラティス', lesson_type: 'studio', duration: 50 },
  { id: 'LSN-004', name: 'ズンバ', lesson_type: 'studio', duration: 45 },
  { id: 'LSN-005', name: 'エアロビクス', lesson_type: 'studio', duration: 60 },
  { id: 'LSN-006', name: 'バレトン', lesson_type: 'studio', duration: 60 },
  {
    id: 'LSN-007',
    name: 'ボクサーサイズ',
    lesson_type: 'studio',
    duration: 45,
  },
  {
    id: 'LSN-008',
    name: 'インターバルトレーニング',
    lesson_type: 'studio',
    duration: 30,
  },
  {
    id: 'LSN-101',
    name: 'パーソナルトレーニング 30分',
    lesson_type: 'personal',
    duration: 30,
  },
  {
    id: 'LSN-102',
    name: 'パーソナルトレーニング 60分',
    lesson_type: 'personal',
    duration: 60,
  },
  {
    id: 'LSN-103',
    name: '体験パーソナル',
    lesson_type: 'personal',
    duration: 30,
  },
];

export const SEED_LESSON_CONTENTS: LessonContentItem[] = [
  {
    id: 'LSN-0001',
    name: 'ヨガベーシック',
    kind: 'studio',
    brand: 'joyfit',
    duration: 60,
    pricing_type: 'included',
    status: 'active',
    gender_restriction: 'none',
    lesson_category: 'スタジオレッスン',
    category: 'ヨガ',
    store_id: 'store-001',
    is_deleted: false,
    reservation_count: 14,
    max_reservation_count: 16,
  },
  {
    id: 'LSN-0002',
    name: 'パワーエアロビクス60',
    kind: 'studio',
    brand: 'fit365',
    duration: 60,
    pricing_type: 'included',
    status: 'active',
    gender_restriction: 'none',
    lesson_category: 'スタジオレッスン',
    category: 'エアロビクス',
    store_id: 'store-001',
    is_deleted: false,
    reservation_count: 15,
    max_reservation_count: 17,
  },
  {
    id: 'LSN-0003',
    name: 'ホットヨガ リフレッシュ',
    kind: 'studio',
    brand: 'fit365',
    duration: 60,
    pricing_type: 'paid',
    status: 'active',
    gender_restriction: 'female',
    lesson_category: 'スタジオレッスン',
    category: 'ヨガ',
    store_id: 'store-002',
    is_deleted: false,
    reservation_count: 35,
    max_reservation_count: 35,
  },
  {
    id: 'LSN-0004',
    name: 'ボディコンバット',
    kind: 'studio',
    brand: 'fit365',
    duration: 60,
    pricing_type: 'included',
    status: 'inactive',
    gender_restriction: 'none',
    lesson_category: 'スタジオレッスン',
    category: 'エアロビクス',
    store_id: 'store-001',
    is_deleted: false,
    reservation_count: 0,
    max_reservation_count: 17,
  },
  {
    id: 'LSN-0005',
    name: 'ズンバフィットネス',
    kind: 'studio',
    brand: 'joyfit',
    duration: 45,
    pricing_type: 'included',
    status: 'active',
    gender_restriction: 'none',
    lesson_category: 'スタジオレッスン',
    category: 'ダンス',
    store_id: 'store-002',
    is_deleted: false,
    reservation_count: 14,
    max_reservation_count: 16,
  },
  {
    id: 'LSN-0006',
    name: 'リラックスストレッチ',
    kind: 'studio',
    brand: 'joyfit',
    duration: 45,
    pricing_type: 'included',
    status: 'active',
    gender_restriction: 'none',
    lesson_category: 'スタジオレッスン',
    category: 'ストレッチ',
    store_id: 'store-003',
    is_deleted: false,
    reservation_count: 5,
    max_reservation_count: 16,
  },
  {
    id: 'LSN-0007',
    name: 'ピラティス入門',
    kind: 'studio',
    brand: 'fit365',
    duration: 45,
    pricing_type: 'included',
    status: 'active',
    gender_restriction: 'none',
    lesson_category: 'スタジオレッスン',
    category: 'ピラティス',
    store_id: 'store-003',
    is_deleted: false,
    reservation_count: 8,
    max_reservation_count: 17,
  },
  {
    id: 'LSN-0008',
    name: 'シニアヨガ',
    kind: 'studio',
    brand: 'joyfit',
    duration: 45,
    pricing_type: 'included',
    status: 'inactive',
    gender_restriction: 'none',
    lesson_category: 'スタジオレッスン',
    category: 'ヨガ',
    store_id: 'store-002',
    is_deleted: true,
    reservation_count: 0,
    max_reservation_count: 15,
  },
  {
    id: 'BDC-0001',
    name: 'アロマリラクゼーション',
    kind: 'bodycare',
    brand: 'fit365',
    duration: 60,
    pricing_type: 'paid',
    status: 'active',
    gender_restriction: 'none',
    lesson_category: 'ボディケア',
    category: 'ボディケア',
    store_id: 'store-001',
    is_deleted: false,
    reservation_count: 3,
    max_reservation_count: 4,
  },
  {
    id: 'BDC-0002',
    name: 'ドライヘッドスパ',
    kind: 'bodycare',
    brand: 'fit365',
    duration: 45,
    pricing_type: 'paid',
    status: 'active',
    gender_restriction: 'none',
    lesson_category: 'ボディケア',
    category: 'ボディケア',
    store_id: 'store-002',
    is_deleted: false,
    reservation_count: 4,
    max_reservation_count: 5,
  },
  {
    id: 'BDC-0003',
    name: 'ストレッチ＆マッサージ',
    kind: 'bodycare',
    brand: 'joyfit',
    duration: 30,
    pricing_type: 'paid',
    status: 'inactive',
    gender_restriction: 'none',
    lesson_category: 'ボディケア',
    category: 'ボディケア',
    store_id: 'store-003',
    is_deleted: false,
    reservation_count: 0,
    max_reservation_count: 1,
  },
];

export const SEED_PERSONAL_PLANS: PersonalPlanItem[] = [
  {
    id: 'PLN-0001',
    name: 'ダイエットプログラム 基本',
    description: '体脂肪率低下を目指す基本プログラム',
    category: 'ダイエット',
    duration: 60,
    price: 5500,
    reservations: 8,
    max_reservations: 10,
    brand: 'fit365',
    status: 'active',
    store_id: 'store-001',
    is_deleted: false,
  },
  {
    id: 'PLN-0002',
    name: '筋力アップ集中コース',
    description: '短期間での筋力向上を目指すプログラム',
    category: '筋力アップ',
    duration: 90,
    price: 7700,
    reservations: 6,
    max_reservations: 8,
    brand: 'fit365',
    status: 'active',
    store_id: 'store-001',
    is_deleted: false,
  },
  {
    id: 'PLN-0003',
    name: '姿勢改善プログラム',
    description: 'デスクワーカー向け姿勢矯正',
    category: '姿勢改善',
    duration: 45,
    price: 4400,
    reservations: 12,
    max_reservations: 15,
    brand: 'joyfit',
    status: 'active',
    store_id: 'store-002',
    is_deleted: false,
  },
  {
    id: 'PLN-0004',
    name: '体力づくりベーシック',
    description: 'シニア向け基礎体力向上',
    category: '体力づくり',
    duration: 60,
    price: 5500,
    reservations: 3,
    max_reservations: 5,
    brand: 'joyfit',
    status: 'active',
    store_id: 'store-003',
    is_deleted: false,
  },
  {
    id: 'PLN-0005',
    name: 'リハビリサポート',
    description: '怪我や手術後のリハビリプログラム',
    category: 'リハビリ',
    duration: 45,
    price: 6600,
    reservations: 2,
    max_reservations: 4,
    brand: 'joyfit',
    status: 'inactive',
    store_id: 'store-002',
    is_deleted: false,
  },
  {
    id: 'PLN-0006',
    name: 'ボディメイク上級',
    description: 'コンテスト出場者向けの本格プログラム',
    category: '筋力アップ',
    duration: 90,
    price: 8800,
    reservations: 5,
    max_reservations: 5,
    brand: 'fit365',
    status: 'active',
    store_id: 'store-001',
    is_deleted: false,
  },
  {
    id: 'PLN-0007',
    name: '産後ダイエットプラン',
    description: '産後の体型回復を目的としたプログラム',
    category: 'ダイエット',
    duration: 45,
    price: 4400,
    reservations: 4,
    max_reservations: 6,
    brand: 'fit365',
    status: 'inactive',
    store_id: 'store-003',
    is_deleted: true,
  },
];

export const LESSON_IMAGE_POOL = [
  'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&h=533&fit=crop',
  'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=533&fit=crop',
  'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&h=533&fit=crop',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800&h=533&fit=crop',
  'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=800&h=533&fit=crop',
  'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=533&fit=crop',
];

export const PERSONAL_IMAGE_POOL = [
  'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=533&fit=crop',
  'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&h=533&fit=crop',
  'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&h=533&fit=crop',
  'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=800&h=533&fit=crop',
];

export type LessonDetailOverride = {
  imageCount?: number;
  images?: { order: number; url: string }[];
  description?: string;
  internal_memo?: string;
  restricted_main_contracts?: string[];
  restricted_option_contracts?: string[];
  per_use_fee?: number;
  usage_count?: number;
};

export const LESSON_DETAIL_OVERRIDES: Record<string, LessonDetailOverride> = {
  'LSN-0001': {
    imageCount: 4,
    description:
      '初心者向けのベーシックヨガです。呼吸法と基本ポーズを中心に、心身のリラックスと柔軟性向上を目指します。',
    internal_memo: 'マットは各自持参を案内。開始5分前に入室締切。',
    restricted_main_contracts: ['プレミアム会員'],
    usage_count: 3,
  },
  'LSN-0002': {
    imageCount: 3,
    description: '全身を使う有酸素エアロビクスです。脂肪燃焼と体力づくりに最適です。',
    internal_memo: '特記事項なし',
    usage_count: 0,
  },
  'LSN-0003': {
    imageCount: 5,
    description: '高温多湿のスタジオで行うホットヨガです。大量の発汗でリフレッシュできます。',
    internal_memo: '水分補給を必ず案内。タオル貸出あり。',
    restricted_main_contracts: ['プレミアム会員', 'レディース会員'],
    restricted_option_contracts: ['ホットスタジオオプション'],
    per_use_fee: 550,
    usage_count: 6,
  },
  'LSN-0004': {
    imageCount: 1,
    description: '格闘技の動きを取り入れた高強度プログラムです。',
    internal_memo: '現在休止中。再開時は要レイアウト確認。',
    usage_count: 0,
  },
  'BDC-0001': {
    imageCount: 2,
    description: 'アロマオイルを使った全身リラクゼーションです。',
    internal_memo: '施術者は資格保有スタッフのみ。',
    per_use_fee: 3300,
    usage_count: 2,
  },
  'PLN-0001': {
    imageCount: 3,
    description:
      'お客様一人ひとりの目標に合わせたオーダーメイドのダイエットプログラムです。食事指導も含みます。',
    internal_memo:
      '初回はカウンセリング（30分）を含みます。体組成測定の結果に基づきメニューを作成。',
    restricted_main_contracts: ['FIT365プレミアム会員'],
    restricted_option_contracts: ['パーソナルトレーニングオプション'],
    per_use_fee: 5500,
    usage_count: 5,
  },
};

export function buildLessonImages(pool: string[], count: number) {
  const safeCount = Math.max(1, Math.min(count, pool.length));
  return pool.slice(0, safeCount).map((url, index) => ({ order: index + 1, url }));
}

export function normalizeLessonImages(images: { order: number; url: string }[]) {
  return [...images]
    .sort((a, b) => a.order - b.order)
    .map((image, index) => ({ order: index + 1, url: image.url }));
}

export const LESSON_CONTENT_SCHEDULES: Record<string, ScheduleSummary> = {
  'LSN-0001': {
    recurring_patterns: [
      {
        id: 'RPT-0001',
        days: ['月', '水', '金'],
        time: '10:00–11:00',
        studio: 'スタジオA',
        period: '2026/04–2026/09',
        instructors: [
          { instructor_id: 'INS-001', name: '山田 花子' },
          { instructor_id: 'INS-002', name: '佐藤 太郎' },
        ],
      },
      {
        id: 'RPT-0002',
        days: ['土'],
        time: '14:00–15:00',
        studio: 'メインスタジオ',
        period: '2026/04–2026/09',
        instructors: [{ instructor_id: 'INS-001', name: '山田 花子' }],
      },
    ],
    sessions: [
      {
        id: 'SCH-1001',
        date: '2026-06-28',
        time: '10:00–11:00',
        studio: 'スタジオA',
        booked: 16,
        capacity: 16,
      },
      {
        id: 'SCH-1002',
        date: '2026-06-30',
        time: '10:00–11:00',
        studio: 'スタジオA',
        booked: 14,
        capacity: 16,
      },
      {
        id: 'SCH-1003',
        date: '2026-07-02',
        time: '10:00–11:00',
        studio: 'スタジオA',
        booked: 9,
        capacity: 16,
      },
      {
        id: 'SCH-1004',
        date: '2026-07-04',
        time: '14:00–15:00',
        studio: 'メインスタジオ',
        booked: 0,
        capacity: 20,
      },
      {
        id: 'SCH-1005',
        date: '2026-07-05',
        time: '10:00–11:00',
        studio: 'スタジオA',
        booked: 3,
        capacity: 16,
      },
    ],
    total: 12,
  },
  'LSN-0003': {
    recurring_patterns: [
      {
        id: 'RPT-0003',
        days: ['火', '木'],
        time: '19:00–20:00',
        studio: 'ホットスタジオ',
        period: '2026/04–2026/12',
        instructors: [{ instructor_id: 'INS-003', name: '高橋 咲' }],
      },
    ],
    sessions: [
      {
        id: 'SCH-2001',
        date: '2026-06-27',
        time: '19:00–20:00',
        studio: 'ホットスタジオ',
        booked: 12,
        capacity: 12,
      },
      {
        id: 'SCH-2002',
        date: '2026-06-29',
        time: '19:00–20:00',
        studio: 'ホットスタジオ',
        booked: 8,
        capacity: 12,
      },
      {
        id: 'SCH-2003',
        date: '2026-07-01',
        time: '19:00–20:00',
        studio: 'ホットスタジオ',
        booked: 2,
        capacity: 12,
      },
    ],
    total: 8,
  },
  'PLN-0001': {
    recurring_patterns: [
      {
        id: 'RPT-0004',
        days: ['月', '木'],
        time: '18:00–19:00',
        studio: 'パーソナルルーム1',
        period: '2026/04–2026/09',
        instructors: [
          { instructor_id: 'INS-004', name: '中村 健' },
          { instructor_id: 'INS-005', name: '小林 美咲' },
        ],
      },
    ],
    sessions: [
      {
        id: 'SCH-3001',
        date: '2026-06-28',
        time: '18:00–19:00',
        studio: 'パーソナルルーム1',
        booked: 1,
        capacity: 1,
      },
      {
        id: 'SCH-3002',
        date: '2026-07-01',
        time: '18:00–19:00',
        studio: 'パーソナルルーム1',
        booked: 1,
        capacity: 1,
      },
      {
        id: 'SCH-3003',
        date: '2026-07-04',
        time: '18:00–19:00',
        studio: 'パーソナルルーム1',
        booked: 0,
        capacity: 1,
      },
    ],
    total: 6,
  },
};

export const LESSON_CONTENT_HISTORY: Record<string, ChangeHistory> = {
  'LSN-0001': {
    entries: [
      {
        id: 'HIS-1003',
        timestamp: '2026-05-02T09:30:00.000Z',
        operator: '本部 山田 花子',
        action: '編集',
        detail: '実施時間: 45分 → 60分',
      },
      {
        id: 'HIS-1002',
        timestamp: '2026-02-10T16:42:00.000Z',
        operator: '本部 鈴木 健',
        action: '有効化',
        detail: '春季キャンペーンに合わせて再開',
      },
      {
        id: 'HIS-1001',
        timestamp: '2026-01-10T00:00:00.000Z',
        operator: '本部 田中 太郎',
        action: '作成',
        detail: null,
      },
    ],
    total: 3,
  },
  'LSN-0004': {
    entries: [
      {
        id: 'HIS-2002',
        timestamp: '2026-04-01T11:08:00.000Z',
        operator: '本部 鈴木 健',
        action: '無効化',
        detail: '提供休止のため無効化',
      },
      {
        id: 'HIS-2001',
        timestamp: '2025-12-20T00:00:00.000Z',
        operator: '本部 田中 太郎',
        action: '作成',
        detail: null,
      },
    ],
    total: 2,
  },
  'PLN-0001': {
    entries: [
      {
        id: 'HIS-3002',
        timestamp: '2026-05-15T10:00:00.000Z',
        operator: '本部 山田 花子',
        action: '編集',
        detail: '都度利用料金: ¥5,000 → ¥5,500',
      },
      {
        id: 'HIS-3001',
        timestamp: '2026-01-10T00:00:00.000Z',
        operator: '本部 田中 太郎',
        action: '作成',
        detail: null,
      },
    ],
    total: 2,
  },
};

export const SEED_STUDIOS: Array<{
  id: string;
  name: string;
  physical_capacity: number;
  store_id: string;
}> = [
  {
    id: 'STU-001',
    name: 'Zumbaスタジオ',
    physical_capacity: 16,
    store_id: 'ST001',
  },
  {
    id: 'STU-002',
    name: 'ヨガスタジオ',
    physical_capacity: 20,
    store_id: 'ST001',
  },
  {
    id: 'STU-003',
    name: 'ピラティスルーム',
    physical_capacity: 12,
    store_id: 'ST001',
  },
  {
    id: 'STU-004',
    name: 'エアロスタジオ',
    physical_capacity: 25,
    store_id: 'ST002',
  },
  {
    id: 'STU-005',
    name: 'ダンススタジオ',
    physical_capacity: 18,
    store_id: 'ST002',
  },
  {
    id: 'STU-006',
    name: 'マルチスタジオ',
    physical_capacity: 30,
    store_id: 'ST003',
  },
  {
    id: 'STU-007',
    name: 'バイクスタジオ',
    physical_capacity: 20,
    store_id: 'ST003',
  },
  {
    id: 'STU-008',
    name: 'グループエクササイズルーム',
    physical_capacity: 20,
    store_id: 'ST004',
  },
  {
    id: 'STU-009',
    name: 'スタジオA',
    physical_capacity: 15,
    store_id: 'ST005',
  },
  {
    id: 'STU-010',
    name: 'スタジオB',
    physical_capacity: 10,
    store_id: 'ST006',
  },
];

// ─── FR-001: Studio List seed data (full CRM data) ──────────────────────

export interface StudioListSeed {
  id: string;
  name: string;
  store_id: string;
  store_name: string;
  studio_type: 'studio-lesson' | 'pt' | 'body-care';
  capacity: number;
  available_hours: string;
  brand: 'joyfit' | 'joyfit24' | 'joyfit_yoga' | 'joyfit_plus' | 'fit365';
  status: 'active' | 'inactive';
}

export const SEED_STUDIO_LIST: StudioListSeed[] = [
  // store-001 (FIT365八潮店) — 3 studios
  {
    id: 'STU-101',
    name: 'Zumbaスタジオ',
    store_id: 'store-001',
    store_name: 'FIT365八潮店',
    studio_type: 'studio-lesson',
    capacity: 16,
    available_hours: '9:00-22:00',
    brand: 'joyfit',
    status: 'active',
  },
  {
    id: 'STU-102',
    name: 'ホットヨガスタジオ',
    store_id: 'store-001',
    store_name: 'FIT365八潮店',
    studio_type: 'studio-lesson',
    capacity: 35,
    available_hours: '10:00-21:00',
    brand: 'fit365',
    status: 'active',
  },
  {
    id: 'STU-103',
    name: 'パーソナルトレーニングルーム',
    store_id: 'store-001',
    store_name: 'FIT365八潮店',
    studio_type: 'pt',
    capacity: 6,
    available_hours: '8:00-22:00',
    brand: 'fit365',
    status: 'active',
  },
  // store-002 (FIT365新宿店) — 3 studios
  {
    id: 'STU-104',
    name: 'メインスタジオ',
    store_id: 'store-002',
    store_name: 'FIT365新宿店',
    studio_type: 'studio-lesson',
    capacity: 30,
    available_hours: '9:00-21:00',
    brand: 'fit365',
    status: 'active',
  },
  {
    id: 'STU-105',
    name: 'ボディケアルーム',
    store_id: 'store-002',
    store_name: 'FIT365新宿店',
    studio_type: 'body-care',
    capacity: 10,
    available_hours: '10:00-20:00',
    brand: 'fit365',
    status: 'active',
  },
  {
    id: 'STU-106',
    name: 'リラックスヨガスタジオ',
    store_id: 'store-002',
    store_name: 'FIT365新宿店',
    studio_type: 'studio-lesson',
    capacity: 20,
    available_hours: '9:00-20:00',
    brand: 'fit365',
    status: 'inactive',
  },
  // store-003 (FIT365渋谷店) — 3 studios
  {
    id: 'STU-107',
    name: 'スタジオA',
    store_id: 'store-003',
    store_name: 'FIT365渋谷店',
    studio_type: 'studio-lesson',
    capacity: 25,
    available_hours: '8:00-23:00',
    brand: 'fit365',
    status: 'active',
  },
  {
    id: 'STU-108',
    name: 'PT専用スタジオ',
    store_id: 'store-003',
    store_name: 'FIT365渋谷店',
    studio_type: 'pt',
    capacity: 8,
    available_hours: '10:00-21:00',
    brand: 'fit365',
    status: 'active',
  },
  {
    id: 'STU-109',
    name: 'スタジオB',
    store_id: 'store-003',
    store_name: 'FIT365渋谷店',
    studio_type: 'studio-lesson',
    capacity: 15,
    available_hours: '9:00-22:00',
    brand: 'fit365',
    status: 'inactive',
  },
  // store-004 (JOYFIT池袋店) — 3 studios (JOYFIT brand)
  {
    id: 'STU-110',
    name: 'ヨガルーム',
    store_id: 'store-004',
    store_name: 'JOYFIT池袋店',
    studio_type: 'studio-lesson',
    capacity: 20,
    available_hours: '9:00-21:00',
    brand: 'joyfit',
    status: 'active',
  },
  {
    id: 'STU-111',
    name: 'ピラティススタジオ',
    store_id: 'store-004',
    store_name: 'JOYFIT池袋店',
    studio_type: 'body-care',
    capacity: 12,
    available_hours: '10:00-20:00',
    brand: 'joyfit',
    status: 'active',
  },
  {
    id: 'STU-112',
    name: 'グループエクササイズルーム',
    store_id: 'store-004',
    store_name: 'JOYFIT池袋店',
    studio_type: 'studio-lesson',
    capacity: 30,
    available_hours: '8:00-22:00',
    brand: 'joyfit24',
    status: 'active',
  },
];

export const SEED_STUDIO_DETAILS: Record<string, GetStudioDetailResponse> = {
  'STU-101': {
    data: {
      id: 'STU-101',
      name: 'Zumbaスタジオ',
      studio_type: 'studio-lesson',
      status: 'active',
      capacity: 16,
      buffer_value: 2,
      usage_hours: '9:00-22:00',
      store_id: 'store-001',
      store_name: 'FIT365八潮店',
      equipment_notes: 'ミラー、スピーカーシステム完備',
      internal_notes: null,
      created_at: '2026-01-15T00:00:00.000Z',
      updated_at: '2026-06-01T00:00:00.000Z',
      assigned_lesson_count: 3,
      change_history_enabled: true,
    },
    linked_lessons: [
      {
        lesson_id: 'LSN-0001',
        lesson_name: 'Zumba基礎',
        category: 'ダンス',
        schedule_text: '月/水 19:00',
        reservation_rate: 82,
        reservation_tier: 'success',
      },
      {
        lesson_id: 'LSN-0002',
        lesson_name: 'Zumbaアドバンス',
        category: 'ダンス',
        schedule_text: '金 20:00',
        reservation_rate: 65,
        reservation_tier: 'warning',
      },
      {
        lesson_id: 'LSN-0003',
        lesson_name: 'ラテンダンス',
        category: 'ダンス',
        schedule_text: '日 18:00',
        reservation_rate: 45,
        reservation_tier: 'default',
      },
    ],
    images: [
      {
        image_id: 'IMG-001',
        url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=400&fit=crop',
        alt: 'Zumbaスタジオ メイン',
        sort_order: 0,
      },
      {
        image_id: 'IMG-002',
        url: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&h=400&fit=crop',
        alt: 'Zumbaスタジオ サイド',
        sort_order: 1,
      },
    ],
    layout: {
      state: 'configured',
      rows: 4,
      columns: 6,
      cells: [
        { x: 0, y: 0, kind: 'normal_seat' },
        { x: 1, y: 0, kind: 'normal_seat' },
        { x: 2, y: 0, kind: 'normal_seat' },
        { x: 3, y: 0, kind: 'normal_seat' },
        { x: 0, y: 1, kind: 'normal_seat' },
        { x: 1, y: 1, kind: 'normal_seat' },
        { x: 2, y: 1, kind: 'equipment_seat' },
        { x: 3, y: 1, kind: 'normal_seat' },
        { x: 0, y: 2, kind: 'normal_seat' },
        { x: 1, y: 2, kind: 'normal_seat' },
        { x: 2, y: 2, kind: 'normal_seat' },
        { x: 3, y: 2, kind: 'normal_seat' },
        { x: 0, y: 3, kind: 'fixed_object' },
        { x: 1, y: 3, kind: 'normal_seat' },
        { x: 2, y: 3, kind: 'normal_seat' },
        { x: 3, y: 3, kind: 'normal_seat' },
      ],
      configure_path: '/studios/STU-101/edit',
    },
    utilization: {
      day_rate: 71,
      week_rate: 68,
      month_rate: 64,
      trend: 'up',
    },
  },
  'STU-102': {
    data: {
      id: 'STU-102',
      name: 'ホットヨガスタジオ',
      studio_type: 'studio-lesson',
      status: 'active',
      capacity: 35,
      buffer_value: 3,
      usage_hours: '10:00-21:00',
      store_id: 'store-001',
      store_name: 'FIT365八潮店',
      equipment_notes: 'ホット機能（40℃、湿度60%）、ヨガマット完備',
      internal_notes: null,
      created_at: '2026-02-01T00:00:00.000Z',
      updated_at: '2026-05-15T00:00:00.000Z',
      assigned_lesson_count: 5,
      change_history_enabled: true,
    },
    linked_lessons: [
      {
        lesson_id: 'LSN-0010',
        lesson_name: 'ホットヨガ入門',
        category: 'ヨガ',
        schedule_text: '月/木 10:00',
        reservation_rate: 88,
        reservation_tier: 'success',
      },
      {
        lesson_id: 'LSN-0011',
        lesson_name: 'ホットヨガ中級',
        category: 'ヨガ',
        schedule_text: '火/金 18:00',
        reservation_rate: 75,
        reservation_tier: 'warning',
      },
    ],
    images: [
      {
        image_id: 'IMG-010',
        url: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&h=400&fit=crop',
        alt: 'ホットヨガスタジオ',
        sort_order: 0,
      },
    ],
    layout: {
      state: 'not_configured',
      rows: null,
      columns: null,
      cells: null,
      configure_path: '/studios/STU-102/edit',
    },
    utilization: {
      day_rate: 85,
      week_rate: 82,
      month_rate: 78,
      trend: 'up',
    },
  },
  'STU-103': {
    data: {
      id: 'STU-103',
      name: 'リハビリスタジオ',
      studio_type: 'studio-lesson',
      status: 'active',
      capacity: 20,
      buffer_value: 2,
      usage_hours: '9:00-19:00',
      store_id: 'store-001',
      store_name: 'FIT365八潮店',
      equipment_notes: 'リハビリ機器、バランスボール完備',
      internal_notes: '高齢者向けクラス専用',
      created_at: '2026-01-20T00:00:00.000Z',
      updated_at: '2026-05-20T00:00:00.000Z',
      assigned_lesson_count: 4,
      change_history_enabled: false,
    },
    linked_lessons: [
      {
        lesson_id: 'LSN-0100',
        lesson_name: 'リハビリエアロビクス',
        category: 'リハビリ',
        schedule_text: '月/水 14:00',
        reservation_rate: 78,
        reservation_tier: 'warning',
      },
      {
        lesson_id: 'LSN-0101',
        lesson_name: 'バランストレーニング',
        category: 'トレーニング',
        schedule_text: '火/木 15:00',
        reservation_rate: 62,
        reservation_tier: 'warning',
      },
      {
        lesson_id: 'LSN-0102',
        lesson_name: 'ストレッチ&リラックス',
        category: 'ストレッチ',
        schedule_text: '土 10:00',
        reservation_rate: 52,
        reservation_tier: 'default',
      },
      {
        lesson_id: 'LSN-0103',
        lesson_name: 'シニア向けヨガ',
        category: 'ヨガ',
        schedule_text: '日 11:00',
        reservation_rate: 85,
        reservation_tier: 'success',
      },
    ],
    images: [
      {
        image_id: 'IMG-030',
        url: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=600&h=400&fit=crop',
        alt: 'リハビリスタジオ',
        sort_order: 0,
      },
    ],
    layout: {
      state: 'configured',
      rows: 3,
      columns: 6,
      cells: [
        { x: 0, y: 0, kind: 'normal_seat' },
        { x: 1, y: 0, kind: 'normal_seat' },
        { x: 2, y: 0, kind: 'normal_seat' },
        { x: 3, y: 0, kind: 'normal_seat' },
        { x: 0, y: 1, kind: 'normal_seat' },
        { x: 1, y: 1, kind: 'equipment_seat' },
        { x: 2, y: 1, kind: 'equipment_seat' },
        { x: 3, y: 1, kind: 'normal_seat' },
        { x: 0, y: 2, kind: 'normal_seat' },
        { x: 1, y: 2, kind: 'normal_seat' },
        { x: 2, y: 2, kind: 'normal_seat' },
        { x: 3, y: 2, kind: 'normal_seat' },
      ],
      configure_path: '/studios/STU-103/edit',
    },
    utilization: {
      day_rate: 70,
      week_rate: 68,
      month_rate: 72,
      trend: 'flat',
    },
  },
  'STU-107': {
    data: {
      id: 'STU-107',
      name: 'スタジオA',
      studio_type: 'studio-lesson',
      status: 'active',
      capacity: 25,
      buffer_value: 2,
      usage_hours: '8:00-23:00',
      store_id: 'store-003',
      store_name: 'FIT365渋谷店',
      equipment_notes: 'ミラー、プロジェクター、サウンドシステム',
      internal_notes: null,
      created_at: '2026-03-10T00:00:00.000Z',
      updated_at: '2026-06-01T00:00:00.000Z',
      assigned_lesson_count: 0,
      change_history_enabled: false,
    },
    linked_lessons: [],
    images: [
      {
        image_id: 'IMG-020',
        url: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=600&h=400&fit=crop',
        alt: 'スタジオA',
        sort_order: 0,
      },
    ],
    layout: {
      state: 'configured',
      rows: 5,
      columns: 5,
      cells: Array.from({ length: 25 }, (_, i) => ({
        x: i % 5,
        y: Math.floor(i / 5),
        kind: i === 12 ? 'fixed_object' : 'normal_seat',
      })),
      configure_path: '/studios/STU-107/edit',
    },
    utilization: {
      day_rate: 60,
      week_rate: 55,
      month_rate: 50,
      trend: 'down',
    },
  },
};

export const SEED_STUDIO_SPACES: Record<string, StudioSpaceGridResponse> = {
  LS0001: {
    studio_name: 'Zumbaスタジオ',
    total_capacity: 16,
    grid_rows: 2,
    grid_cols: 8,
    spaces: Array.from({ length: 16 }, (_, i) => ({
      id: `SP${String(i + 1).padStart(2, '0')}`,
      space_number: `S${String(i + 1).padStart(2, '0')}`,
      row: Math.floor(i / 8),
      col: i % 8,
      type: (i < 14 ? 'available' : 'reserved') as 'available' | 'reserved',
      reservation_id: i < 14 ? null : `RD${String(i - 13).padStart(3, '0')}`,
      member_name: i < 14 ? null : '予約済み',
    })),
  },
  LS0006: {
    studio_name: 'Zumbaスタジオ',
    total_capacity: 16,
    grid_rows: 2,
    grid_cols: 8,
    spaces: Array.from({ length: 16 }, (_, i) => ({
      id: `SP${String(i + 17).padStart(2, '0')}`,
      space_number: `S${String(i + 1).padStart(2, '0')}`,
      row: Math.floor(i / 8),
      col: i % 8,
      type: (i < 5 ? 'reserved' : 'available') as 'reserved' | 'available',
      reservation_id: i < 5 ? `RD${String(i + 100).padStart(3, '0')}` : null,
      member_name: i < 5 ? '予約済み' : null,
    })),
  },
  LS0007: {
    studio_name: 'スタジオA',
    total_capacity: 16,
    grid_rows: 2,
    grid_cols: 8,
    spaces: Array.from({ length: 16 }, (_, i) => ({
      id: `SP${String(i + 33).padStart(2, '0')}`,
      space_number: `S${String(i + 1).padStart(2, '0')}`,
      row: Math.floor(i / 8),
      col: i % 8,
      type: (i < 14 ? 'available' : 'equipment') as 'available' | 'equipment',
      reservation_id: null,
      member_name: null,
    })),
  },
};

export const SEED_SESSION_MEMOS: SessionMemo[] = [
  {
    id: 'MEMO001',
    schedule_id: 'LS0001',
    content: '本日のヨガ基礎クラスは beginner 向けに調整してください。',
    author_id: 'ST001',
    author_name: '田中 花子',
    created_at: '2026-06-23T08:30:00+09:00',
    updated_at: null,
  },
  {
    id: 'MEMO002',
    schedule_id: 'LS0001',
    content: '参加者に膝の怪我をされている方がいます。注意して指導をお願いします。',
    author_id: 'ST002',
    author_name: '佐藤 一郎',
    created_at: '2026-06-23T08:45:00+09:00',
    updated_at: '2026-06-23T09:00:00+09:00',
  },
  {
    id: 'MEMO003',
    schedule_id: 'LS0003',
    content: 'ボディコンバットのBGMリストを今週から新しいものに変更します。',
    author_id: 'ST003',
    author_name: '山田 太郎',
    created_at: '2026-06-23T12:00:00+09:00',
    updated_at: null,
  },
  {
    id: 'MEMO004',
    schedule_id: 'LS0007',
    content: 'モーニングヨガ：室温設定をいつもより2度低めに設定してください。',
    author_id: 'ST001',
    author_name: '田中 花子',
    created_at: '2026-06-23T07:00:00+09:00',
    updated_at: null,
  },
  {
    id: 'MEMO005',
    schedule_id: 'LS0010',
    content: 'ピラティス入門：本日新しいマットを使用します。準備をお願いします。',
    author_id: 'ST004',
    author_name: '木村 拓也',
    created_at: '2026-06-23T09:30:00+09:00',
    updated_at: '2026-06-23T09:45:00+09:00',
  },
];

export const SEED_RESERVATIONS: Reservation[] = [
  ...Array.from({ length: 10 }, (_, i) => ({
    id: `R${String(i + 1).padStart(3, '0')}`,
    schedule_id: 'LS0001',
    member_id: `M${101 + i}`,
    member_name: [
      '田中 花子',
      '佐藤 一郎',
      '山田 太郎',
      '木村 拓也',
      '森田 健一',
      '藤井 優',
      '斉藤 美紀',
      '伊藤 誠',
      '渡辺 直美',
      '中村 博',
    ][i]!,
    plan_type: '月額8回',
    space_number: `S${String(i + 1).padStart(2, '0')}`,
    reservation_date: '2026-06-23',
    reservation_time: '08:45',
    status: 'confirmed' as ReservationStatus,
    attendance_status: 'unconfirmed' as AttendanceStatus,
    cancel_type: null,
    penalty_active: false,
    penalty_end_date: null,
    remaining_sessions: 3,
    sent_notification: true,
  })),
  {
    id: 'R011',
    schedule_id: 'LS0001',
    member_id: 'M111',
    member_name: '小林 真一',
    plan_type: '月額4回',
    space_number: 'S11',
    reservation_date: '2026-06-23',
    reservation_time: '08:50',
    status: 'tentative',
    attendance_status: 'unconfirmed',
    cancel_type: null,
    penalty_active: false,
    penalty_end_date: null,
    remaining_sessions: 2,
    sent_notification: true,
  },
  {
    id: 'R012',
    schedule_id: 'LS0001',
    member_id: 'M112',
    member_name: '加藤 由美',
    plan_type: '月額8回',
    space_number: 'S12',
    reservation_date: '2026-06-23',
    reservation_time: '08:55',
    status: 'cancelled',
    attendance_status: 'unconfirmed',
    cancel_type: 'member',
    penalty_active: true,
    penalty_end_date: '2026-07-07',
    remaining_sessions: 5,
    sent_notification: true,
  },
  {
    id: 'R013',
    schedule_id: 'LS0001',
    member_id: 'M113',
    member_name: '松本 隆',
    plan_type: '都次',
    space_number: 'S13',
    reservation_date: '2026-06-23',
    reservation_time: '08:40',
    status: 'confirmed',
    attendance_status: 'unconfirmed',
    cancel_type: null,
    penalty_active: false,
    penalty_end_date: null,
    remaining_sessions: 0,
    sent_notification: false,
  },
  {
    id: 'R014',
    schedule_id: 'LS0001',
    member_id: 'M114',
    member_name: '井上 香織',
    plan_type: '月額8回',
    space_number: 'S14',
    reservation_date: '2026-06-23',
    reservation_time: '08:30',
    status: 'confirmed',
    attendance_status: 'unconfirmed',
    cancel_type: null,
    penalty_active: true,
    penalty_end_date: '2026-07-14',
    remaining_sessions: 0,
    sent_notification: true,
  },
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `R${15 + i}`,
    schedule_id: 'LS0002',
    member_id: `M${201 + i}`,
    member_name: [
      '吉田 沙織',
      '石川 圭',
      '山口 優子',
      '橋本 悟',
      '長谷川 愛',
      '本田 圭佑',
      '武田 倫子',
      '岡田 翔太',
    ][i]!,
    plan_type: '月額8回',
    space_number: null,
    reservation_date: '2026-06-23',
    reservation_time: '10:00',
    status: 'confirmed' as ReservationStatus,
    attendance_status: 'unconfirmed' as AttendanceStatus,
    cancel_type: null,
    penalty_active: false,
    penalty_end_date: null,
    remaining_sessions: 4 - i,
    sent_notification: true,
  })),
  ...Array.from({ length: 5 }, (_, i) => ({
    id: `R${23 + i}`,
    schedule_id: 'LS0003',
    member_id: `M${301 + i}`,
    member_name: ['小川 茜', '斎藤 拓', '近藤 麻衣', '福田 大輔', '西村 真理'][i]!,
    plan_type: i === 0 ? '都次' : '月額8回',
    space_number: null,
    reservation_date: '2026-06-23',
    reservation_time: '12:30',
    status: i === 4 ? ('cancelled' as ReservationStatus) : ('confirmed' as ReservationStatus),
    attendance_status: 'unconfirmed' as AttendanceStatus,
    cancel_type: i === 4 ? ('staff' as CancelType) : null,
    penalty_active: false,
    penalty_end_date: null,
    remaining_sessions: i === 3 ? 0 : 6 - i,
    sent_notification: true,
  })),
  ...Array.from({ length: 5 }, (_, i) => ({
    id: `R${28 + i}`,
    schedule_id: 'LS0006',
    member_id: `M${401 + i}`,
    member_name: ['安藤 なつみ', '大野 智', '杉山 佳代', '野村 周平', '横山 美穂'][i]!,
    plan_type: '月額4回',
    space_number: null,
    reservation_date: '2026-06-23',
    reservation_time: '17:30',
    status: i === 3 ? ('attended' as ReservationStatus) : ('confirmed' as ReservationStatus),
    attendance_status:
      i === 3 ? ('confirmed' as AttendanceStatus) : ('unconfirmed' as AttendanceStatus),
    cancel_type: null,
    penalty_active: false,
    penalty_end_date: null,
    remaining_sessions: 1,
    sent_notification: i !== 4,
  })),
  {
    id: 'R033',
    schedule_id: 'LS0004',
    member_id: 'M115',
    member_name: '渡辺 誠',
    plan_type: '都次',
    space_number: 'S01',
    reservation_date: '2026-06-23',
    reservation_time: '13:30',
    status: 'confirmed',
    attendance_status: 'unconfirmed',
    cancel_type: null,
    penalty_active: false,
    penalty_end_date: null,
    remaining_sessions: 0,
    sent_notification: true,
  },
  {
    id: 'R034',
    schedule_id: 'LS0005',
    member_id: 'M116',
    member_name: '中村 浩',
    plan_type: '月額8回',
    space_number: 'S01',
    reservation_date: '2026-06-23',
    reservation_time: '15:30',
    status: 'confirmed',
    attendance_status: 'unconfirmed',
    cancel_type: null,
    penalty_active: false,
    penalty_end_date: null,
    remaining_sessions: 3,
    sent_notification: true,
  },
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `R${35 + i}`,
    schedule_id: 'LS0007',
    member_id: `M${501 + i}`,
    member_name: [
      '田辺 歩',
      '嶋田 聡',
      '川村 真由',
      '高原 大介',
      '片山 由紀',
      '黒田 誠',
      '松永 千尋',
      '丹羽 敦',
    ][i]!,
    plan_type: '月額8回',
    space_number: null,
    reservation_date: '2026-06-23',
    reservation_time: '07:30',
    status: i < 6 ? ('confirmed' as ReservationStatus) : ('tentative' as ReservationStatus),
    attendance_status: 'unconfirmed' as AttendanceStatus,
    cancel_type: null,
    penalty_active: false,
    penalty_end_date: null,
    remaining_sessions: 4,
    sent_notification: true,
  })),
  ...Array.from({ length: 5 }, (_, i) => ({
    id: `R${43 + i}`,
    schedule_id: 'LS0010',
    member_id: `M${601 + i}`,
    member_name: ['村上 春樹', '吉岡 秀隆', '坂本 龍一', '松田 翔太', '綾瀬 はるか'][i]!,
    plan_type: '月額4回',
    space_number: null,
    reservation_date: '2026-06-23',
    reservation_time: '09:30',
    status: i === 4 ? ('no_show' as ReservationStatus) : ('confirmed' as ReservationStatus),
    attendance_status:
      i === 4 ? ('no_show' as AttendanceStatus) : ('unconfirmed' as AttendanceStatus),
    cancel_type: null,
    penalty_active: i === 4,
    penalty_end_date: i === 4 ? '2026-07-07' : null,
    remaining_sessions: i === 4 ? 0 : 2,
    sent_notification: true,
  })),
];

export function lessonContentRowToDetail(
  row: LessonContentItem,
  LESSON_CONTENT_SCHEDULES_MAP: Record<string, ScheduleSummary>,
): LessonContentDetail {
  const override = LESSON_DETAIL_OVERRIDES[row.id] ?? {};
  const isPaid = row.pricing_type === 'paid';
  const perUseFee = isPaid ? (override.per_use_fee ?? 550) : null;
  const usageCount =
    override.usage_count ?? (row.reservation_count && row.reservation_count > 0 ? 2 : 0);
  const schedule = LESSON_CONTENT_SCHEDULES_MAP[row.id];
  return {
    id: row.id,
    name: row.name,
    lesson_type: row.kind,
    brand: row.brand,
    status: row.status,
    duration: row.duration,
    pricing_type: row.pricing_type,
    per_use_fee: perUseFee,
    images: override.images ?? buildLessonImages(LESSON_IMAGE_POOL, override.imageCount ?? 3),
    description: override.description ?? `${row.name}の詳細説明です。`,
    internal_memo: override.internal_memo ?? '特記事項なし',
    restriction: {
      restricted_main_contracts: override.restricted_main_contracts ?? [],
      restricted_option_contracts: override.restricted_option_contracts ?? [],
      per_use_fee: perUseFee,
    },
    usage_count: usageCount,
    schedule_total: schedule?.total ?? 0,
    store_id: row.store_id,
    created_at: '2026-01-10T00:00:00.000Z',
    updated_at: '2026-05-02T00:00:00.000Z',
  };
}

export function personalPlanRowToDetail(
  row: PersonalPlanItem,
  LESSON_CONTENT_SCHEDULES_MAP: Record<string, ScheduleSummary>,
): LessonContentDetail {
  const override = LESSON_DETAIL_OVERRIDES[row.id] ?? {};
  const usageCount = override.usage_count ?? (row.reservations > 0 ? 2 : 0);
  const schedule = LESSON_CONTENT_SCHEDULES_MAP[row.id];
  return {
    id: row.id,
    name: row.name,
    lesson_type: 'personal',
    brand: row.brand,
    status: row.status,
    duration: row.duration,
    pricing_type: 'paid',
    per_use_fee: override.per_use_fee ?? row.price,
    images: override.images ?? buildLessonImages(PERSONAL_IMAGE_POOL, override.imageCount ?? 3),
    description: override.description ?? row.description ?? `${row.name}の詳細説明です。`,
    internal_memo: override.internal_memo ?? '特記事項なし',
    restriction: {
      restricted_main_contracts: override.restricted_main_contracts ?? [],
      restricted_option_contracts: override.restricted_option_contracts ?? [],
      per_use_fee: override.per_use_fee ?? row.price,
    },
    usage_count: usageCount,
    schedule_total: schedule?.total ?? 0,
    store_id: row.store_id,
    created_at: '2026-01-10T00:00:00.000Z',
    updated_at: '2026-05-02T00:00:00.000Z',
  };
}

/** D-03 FR-003 — Studio change history seed (read-only) */
export const SEED_STUDIO_HISTORY: Record<string, StudioChangeHistoryEntry[]> = {
  'STU-101': [
    {
      timestamp: '2026-03-01T14:22:00.000Z',
      user: '管理者',
      action: '更新',
      diffs: [
        {
          field: '備考',
          before: '（空欄）',
          after: '土日は利用者が多いため、清掃スケジュールを追加',
        },
      ],
    },
    {
      timestamp: '2026-02-14T10:05:00.000Z',
      user: '管理者',
      action: '更新',
      diffs: [
        { field: 'スペースレイアウト', before: '4x4', after: '4x5' },
        { field: '定員', before: '12名', after: '16名' },
      ],
    },
    {
      timestamp: '2026-01-20T09:30:00.000Z',
      user: '管理者',
      action: '更新',
      diffs: [
        {
          field: '設備・備品',
          before: 'ヨガマット15枚',
          after: 'ヨガマット20枚、ミラー壁面、音響設備、空調完備',
        },
      ],
    },
    {
      timestamp: '2025-02-10T11:00:00.000Z',
      user: '管理者',
      action: '作成',
      note: 'Zumbaスタジオを新規登録',
    },
  ],
  'STU-102': [
    {
      timestamp: '2026-02-01T10:00:00.000Z',
      user: '管理者',
      action: '作成',
      note: 'ホットヨガスタジオを新規登録',
    },
  ],
};
