import type { TermsConsentRow, TermsRow } from '../types/terms.type';

const TERMS_FILE_SIZE_MAP: Record<string, string> = {
  'contract_terms_v1.3.pdf': '420 KB',
  'contract_terms_v1.2.pdf': '380 KB',
  'contract_terms_v1.1.pdf': '360 KB',
  'contract_terms_v1.0.pdf': '340 KB',
  'fit365_terms_v1.0.1.pdf': '410 KB',
  'joyfit_plus_terms_v1.1.pdf': '395 KB',
  'joyfit_terms_v1.0.1.pdf': '390 KB',
  'joyfit_terms_draft_v1.1.pdf': '405 KB',
  'service_yoga_terms_v1.0.1.pdf': '280 KB',
  'contract_24h_v2.0.pdf': '365 KB',
  'fit365_terms_v2.1.pdf': '430 KB',
  'yoga_special_terms_v1.0.pdf': '250 KB',
  'fit365_terms_v1.0.pdf': '400 KB',
  'withdrawal_terms_v1.0.pdf': '220 KB',
  'suspension_terms_v1.0.pdf': '220 KB',
};

export function buildTermsPdfUrl(pdfS3Key: string): string {
  return `https://cdn.mock.example.com/${pdfS3Key.replace(/^\/+/, '')}`;
}

export function getSeedTermsPdfFileSize(fileName: string): string {
  return TERMS_FILE_SIZE_MAP[fileName] ?? 'PDF';
}

function buildSeedTermsBody(title: string): string {
  return `第1条（総則）
本規約は、${title}に関する利用条件を定めるものです。会員は本規約に同意の上、サービスを利用するものとします。

第2条（適用範囲）
対象ブランドの会員および利用者は、本規約に従って各種サービスを利用します。

第3条（変更）
運営会社は、必要に応じて本規約を改定できます。改定後の内容は、適用開始日以降の利用に適用されます。

第4条（補足）
詳細な条項および原本は、添付PDFを正式文書として管理します。`;
}

export function createSeedTermsRows(): TermsRow[] {
  return [
    {
      id: '1',
      parentTermsId: '11',
      prevTermsId: '13',
      termsType: 'membership',
      brandEnum: 'JOYFIT',
      title: '会員規約',
      version: 'v1.2',
      effectiveFrom: '2025-04-01',
      effectiveTo: '2025-09-30',
      displayOrder: '1',
      requiresConsent: true,
      remarks: '全条項の見直し',
      bodyText: buildSeedTermsBody('会員規約 v1.2'),
      pdfS3Key: 'document/01TERM001.pdf',
      pdfUrl: buildTermsPdfUrl('document/01TERM001.pdf'),
      pdfFileName: 'contract_terms_v1.2.pdf',
      createdAt: '2025-04-01T00:00:00.000Z',
      createdBy: '管理者',
      updatedAt: '2025-09-30T00:00:00.000Z',
      updatedBy: '管理者',
      deletedAt: null,
    },
    {
      id: '2',
      parentTermsId: '11',
      prevTermsId: '1',
      termsType: 'membership',
      brandEnum: 'JOYFIT',
      title: '会員規約',
      version: 'v1.3',
      effectiveFrom: '2025-10-01',
      effectiveTo: null,
      displayOrder: '1',
      requiresConsent: true,
      remarks: '第3条（契約期間）の変更、第5条（解約）の追記',
      bodyText: `第1条（総則）
本規約は、株式会社JOYFITが提供するフィットネスサービスの利用条件を定めるものです。会員は本規約に同意の上、サービスを利用するものとします。

第2条（会員資格）
本規約を承諾し、所定の入会手続きを行った方を会員とします。

第3条（契約期間）
契約期間は、入会日から1年間とします。期間満了の1ヶ月前までに解約の申し出がない場合、自動的に1年間更新されるものとします。

第4条（会費）
会員は、契約期間中、当社所定の会費を支払うものとします。

第5条（解約）
会員は、解約希望月の前月10日までに当社所定の方法で解約の申し出を行うことができます。`,
      pdfS3Key: 'document/01TERM002.pdf',
      pdfUrl: buildTermsPdfUrl('document/01TERM002.pdf'),
      pdfFileName: 'contract_terms_v1.3.pdf',
      createdAt: '2024-10-01T09:00:00.000Z',
      createdBy: '管理者',
      updatedAt: '2025-10-01T10:30:00.000Z',
      updatedBy: '管理者',
      deletedAt: null,
    },
    {
      id: '3',
      parentTermsId: null,
      prevTermsId: null,
      termsType: 'privacy',
      brandEnum: 'FIT365',
      title: 'プライバシーポリシー',
      version: 'v1.0.1',
      effectiveFrom: '2025-06-15',
      effectiveTo: null,
      displayOrder: '3',
      requiresConsent: true,
      remarks: '個人情報の取扱範囲を整理',
      bodyText: buildSeedTermsBody('プライバシーポリシー'),
      pdfS3Key: 'document/01TERM003.pdf',
      pdfUrl: buildTermsPdfUrl('document/01TERM003.pdf'),
      pdfFileName: 'fit365_terms_v1.0.1.pdf',
      createdAt: '2025-06-15T00:00:00.000Z',
      createdBy: '管理者',
      updatedAt: '2025-06-15T00:00:00.000Z',
      updatedBy: '管理者',
      deletedAt: null,
    },
    {
      id: '4',
      parentTermsId: null,
      prevTermsId: null,
      termsType: 'privacy',
      brandEnum: 'JOYFIT',
      title: 'プライバシーポリシー（JOYFIT+）',
      version: 'v1.1',
      effectiveFrom: '2025-08-01',
      effectiveTo: null,
      displayOrder: '4',
      requiresConsent: true,
      remarks: 'JOYFIT+向けの個人情報取扱条項を追加',
      bodyText: buildSeedTermsBody('プライバシーポリシー（JOYFIT+）'),
      pdfS3Key: 'document/01TERM004.pdf',
      pdfUrl: buildTermsPdfUrl('document/01TERM004.pdf'),
      pdfFileName: 'joyfit_plus_terms_v1.1.pdf',
      createdAt: '2025-08-01T00:00:00.000Z',
      createdBy: '管理者',
      updatedAt: '2025-08-01T00:00:00.000Z',
      updatedBy: '管理者',
      deletedAt: null,
    },
    {
      id: '5',
      parentTermsId: null,
      prevTermsId: null,
      termsType: 'payment',
      brandEnum: 'JOYFIT',
      title: '決済規約',
      version: 'v1.0.1',
      effectiveFrom: '2025-03-01',
      effectiveTo: null,
      displayOrder: '5',
      requiresConsent: true,
      remarks: '決済方法と請求タイミングを明文化',
      bodyText: buildSeedTermsBody('決済規約'),
      pdfS3Key: 'document/01TERM005.pdf',
      pdfUrl: buildTermsPdfUrl('document/01TERM005.pdf'),
      pdfFileName: 'joyfit_terms_v1.0.1.pdf',
      createdAt: '2025-03-01T00:00:00.000Z',
      createdBy: '管理者',
      updatedAt: '2025-03-01T00:00:00.000Z',
      updatedBy: '管理者',
      deletedAt: null,
    },
    {
      id: '6',
      parentTermsId: null,
      prevTermsId: null,
      termsType: 'payment',
      brandEnum: 'JOYFIT',
      title: '決済規約（下書き）',
      version: 'v1.1',
      effectiveFrom: '2026-01-01',
      effectiveTo: null,
      displayOrder: '6',
      requiresConsent: true,
      remarks: '次回改定予定の下書き',
      bodyText: buildSeedTermsBody('決済規約（下書き）'),
      pdfS3Key: 'document/01TERM006.pdf',
      pdfUrl: buildTermsPdfUrl('document/01TERM006.pdf'),
      pdfFileName: 'joyfit_terms_draft_v1.1.pdf',
      createdAt: '2025-10-20T00:00:00.000Z',
      createdBy: '管理者',
      updatedAt: '2025-10-20T00:00:00.000Z',
      updatedBy: '管理者',
      deletedAt: null,
    },
    {
      id: '7',
      parentTermsId: null,
      prevTermsId: null,
      termsType: 'companion',
      brandEnum: 'JOYFIT',
      title: '同伴規約',
      version: 'v1.0.1',
      effectiveFrom: '2025-07-01',
      effectiveTo: null,
      displayOrder: '7',
      requiresConsent: false,
      remarks: '同伴利用時の注意事項を定義',
      bodyText: buildSeedTermsBody('同伴規約'),
      pdfS3Key: 'document/01TERM007.pdf',
      pdfUrl: buildTermsPdfUrl('document/01TERM007.pdf'),
      pdfFileName: 'service_yoga_terms_v1.0.1.pdf',
      createdAt: '2025-07-01T00:00:00.000Z',
      createdBy: '管理者',
      updatedAt: '2025-07-01T00:00:00.000Z',
      updatedBy: '管理者',
      deletedAt: null,
    },
    {
      id: '8',
      parentTermsId: null,
      prevTermsId: null,
      termsType: 'withdrawal',
      brandEnum: 'JOYFIT',
      title: '退会規約',
      version: 'v2.0',
      effectiveFrom: '2025-09-01',
      effectiveTo: null,
      displayOrder: '8',
      requiresConsent: true,
      remarks: '退会申請時に表示する規約',
      bodyText: buildSeedTermsBody('退会規約'),
      pdfS3Key: 'document/01TERM008.pdf',
      pdfUrl: buildTermsPdfUrl('document/01TERM008.pdf'),
      pdfFileName: 'contract_24h_v2.0.pdf',
      createdAt: '2025-09-01T00:00:00.000Z',
      createdBy: '管理者',
      updatedAt: '2025-09-01T00:00:00.000Z',
      updatedBy: '管理者',
      deletedAt: null,
    },
    {
      id: '9',
      parentTermsId: null,
      prevTermsId: null,
      termsType: 'privacy',
      brandEnum: 'FIT365',
      title: 'プライバシーポリシー（FIT365）',
      version: 'v2.1',
      effectiveFrom: '2025-12-01',
      effectiveTo: null,
      displayOrder: '9',
      requiresConsent: true,
      remarks: 'FIT365向けプライバシーポリシー改定案',
      bodyText: buildSeedTermsBody('プライバシーポリシー（FIT365）'),
      pdfS3Key: 'document/01TERM009.pdf',
      pdfUrl: buildTermsPdfUrl('document/01TERM009.pdf'),
      pdfFileName: 'fit365_terms_v2.1.pdf',
      createdAt: '2025-10-25T00:00:00.000Z',
      createdBy: '管理者',
      updatedAt: '2025-10-25T00:00:00.000Z',
      updatedBy: '管理者',
      deletedAt: null,
    },
    {
      id: '10',
      parentTermsId: null,
      prevTermsId: null,
      termsType: 'suspension',
      brandEnum: 'JOYFIT',
      title: '休会規約',
      version: 'v1.0',
      effectiveFrom: '2025-11-01',
      effectiveTo: null,
      displayOrder: '10',
      requiresConsent: true,
      remarks: '休会手続き向けの適用規約',
      bodyText: buildSeedTermsBody('休会規約'),
      pdfS3Key: 'document/01TERM010.pdf',
      pdfUrl: buildTermsPdfUrl('document/01TERM010.pdf'),
      pdfFileName: 'yoga_special_terms_v1.0.pdf',
      createdAt: '2025-11-01T00:00:00.000Z',
      createdBy: '管理者',
      updatedAt: '2025-11-01T00:00:00.000Z',
      updatedBy: '管理者',
      deletedAt: null,
    },
    {
      id: '11',
      parentTermsId: null,
      prevTermsId: null,
      termsType: 'membership',
      brandEnum: 'JOYFIT',
      title: '会員規約（旧版）',
      version: 'v1.0',
      effectiveFrom: '2024-04-01',
      effectiveTo: '2025-03-31',
      displayOrder: '11',
      requiresConsent: true,
      remarks: '初版作成（オリジナル規約）',
      bodyText: buildSeedTermsBody('会員規約 v1.0'),
      pdfS3Key: 'document/01TERM011.pdf',
      pdfUrl: buildTermsPdfUrl('document/01TERM011.pdf'),
      pdfFileName: 'contract_terms_v1.0.pdf',
      createdAt: '2024-04-01T09:00:00.000Z',
      createdBy: '管理者',
      updatedAt: '2025-03-31T00:00:00.000Z',
      updatedBy: '管理者',
      deletedAt: null,
    },
    {
      id: '13',
      parentTermsId: '11',
      prevTermsId: '11',
      termsType: 'membership',
      brandEnum: 'JOYFIT',
      title: '会員規約',
      version: 'v1.1',
      effectiveFrom: '2025-01-15',
      effectiveTo: '2025-03-31',
      displayOrder: '1',
      requiresConsent: true,
      remarks: '誤字修正、表現の統一',
      bodyText: buildSeedTermsBody('会員規約 v1.1'),
      pdfS3Key: 'document/01TERM013.pdf',
      pdfUrl: buildTermsPdfUrl('document/01TERM013.pdf'),
      pdfFileName: 'contract_terms_v1.1.pdf',
      createdAt: '2025-01-15T09:00:00.000Z',
      createdBy: '管理者',
      updatedAt: '2025-01-15T09:00:00.000Z',
      updatedBy: '管理者',
      deletedAt: null,
    },
    {
      id: '12',
      parentTermsId: null,
      prevTermsId: null,
      termsType: 'privacy',
      brandEnum: 'FIT365',
      title: 'プライバシーポリシー（旧版）',
      version: 'v1.0',
      effectiveFrom: '2024-10-01',
      effectiveTo: '2025-05-31',
      displayOrder: '12',
      requiresConsent: true,
      remarks: 'FIT365旧版ポリシー',
      bodyText: buildSeedTermsBody('プライバシーポリシー（旧版）'),
      pdfS3Key: 'document/01TERM012.pdf',
      pdfUrl: buildTermsPdfUrl('document/01TERM012.pdf'),
      pdfFileName: 'fit365_terms_v1.0.pdf',
      createdAt: '2024-10-01T00:00:00.000Z',
      createdBy: '管理者',
      updatedAt: '2025-05-31T00:00:00.000Z',
      updatedBy: '管理者',
      deletedAt: '2026-02-01T00:00:00.000Z',
    },
  ];
}

export function createSeedTermsConsents(): TermsConsentRow[] {
  return [
    {
      consentId: 'TC001',
      memberId: 'M-10001',
      termsId: '1',
      source: 'revision_reaccept',
      consentedAt: '2025-10-05T09:00:00.000Z',
    },
  ];
}
