import type { VisitExperienceDetail } from '@/app/api/_schemas/visit-experience.schema';

export function makeVeDate(offsetDays: number, hour: number, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString().replace('Z', '+00:00');
}

export const SEED_VISIT_EXPERIENCES: VisitExperienceDetail[] = [
  {
    id: 'VE-001',
    customer_name: '山田 太郎',
    customer_name_kana: 'ヤマダ タロウ',
    birth_date: '1990/04/15',
    phone: '090-1234-5678',
    email: 'yamada.taro@example.com',
    address: '東京都渋谷区渋谷1-1-1',
    status: 'visiting',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT',
    store_name: 'JOYFIT渋谷店',
    reserved_at: makeVeDate(0, 9, 0),
    visit_start_at: makeVeDate(0, 9, 5),
    visit_end_scheduled_at: makeVeDate(0, 9, 35),
    visit_end_actual_at: null,
    id_document_type: '運転免許証',
    id_document_verified: true,
    permit_issued_at: makeVeDate(0, 9, 3),
    b01_auth_method: '顔認証',
    b01_gate: 'メインエントランス',
    b01_entry_at: makeVeDate(0, 9, 5),
    b01_exit_at: null,
    timeline: [
      {
        timestamp: makeVeDate(0, 9, 5),
        operator: 'システム',
        content: '施設入館（顔認証）— 30分見学開始',
      },
      {
        timestamp: makeVeDate(0, 9, 3),
        operator: '管理者A',
        content: '見学許可を発行（30分間の時間制限入館）',
      },
      {
        timestamp: makeVeDate(0, 9, 1),
        operator: 'システム',
        content: '個人情報・顔写真の登録確認完了',
      },
      {
        timestamp: makeVeDate(0, 9, 0),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-002',
    customer_name: '鈴木 花子',
    customer_name_kana: 'スズキ ハナコ',
    birth_date: '1995/08/22',
    phone: '080-9876-5432',
    email: 'suzuki.hanako@example.com',
    address: '東京都新宿区新宿3-2-1',
    status: 'application_received',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT',
    store_name: 'JOYFIT渋谷店',
    reserved_at: makeVeDate(0, 11, 0),
    visit_start_at: null,
    visit_end_scheduled_at: makeVeDate(0, 11, 30),
    visit_end_actual_at: null,
    id_document_type: 'マイナンバーカード',
    id_document_verified: true,
    permit_issued_at: null,
    b01_auth_method: null,
    b01_gate: null,
    b01_entry_at: null,
    b01_exit_at: null,
    timeline: [
      {
        timestamp: makeVeDate(0, 10, 58),
        operator: 'システム',
        content: 'ブラックリスト照合完了（該当なし）',
      },
      {
        timestamp: makeVeDate(0, 10, 56),
        operator: 'システム',
        content: '個人情報・顔写真の登録確認完了',
      },
      {
        timestamp: makeVeDate(0, 10, 55),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-003',
    customer_name: '佐藤 健二',
    customer_name_kana: 'サトウ ケンジ',
    birth_date: '1988/12/03',
    phone: '090-3456-7890',
    email: 'sato.kenji@example.com',
    address: '東京都新宿区西新宿1-1-1',
    status: 'membership_applied',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT',
    store_name: 'JOYFIT新宿店',
    reserved_at: makeVeDate(0, 10, 30),
    visit_start_at: makeVeDate(0, 10, 35),
    visit_end_scheduled_at: makeVeDate(0, 11, 5),
    visit_end_actual_at: makeVeDate(0, 11, 20),
    id_document_type: '運転免許証',
    id_document_verified: true,
    permit_issued_at: makeVeDate(0, 10, 33),
    b01_auth_method: '顔認証',
    b01_gate: 'メインエントランス',
    b01_entry_at: makeVeDate(0, 10, 35),
    b01_exit_at: makeVeDate(0, 11, 20),
    timeline: [
      {
        timestamp: makeVeDate(0, 11, 25),
        operator: 'スタッフB',
        content: '入会申請フォームへ誘導',
      },
      {
        timestamp: makeVeDate(0, 11, 20),
        operator: 'システム',
        content: '見学終了（施設退館確認）',
      },
      {
        timestamp: makeVeDate(0, 10, 35),
        operator: 'システム',
        content: '施設入館（顔認証）— 30分見学開始',
      },
      {
        timestamp: makeVeDate(0, 10, 33),
        operator: '管理者A',
        content: '見学許可を発行（30分間の時間制限入館）',
      },
      {
        timestamp: makeVeDate(0, 10, 30),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-004',
    customer_name: '田中 美咲',
    customer_name_kana: 'タナカ ミサキ',
    birth_date: '2000/01/10',
    phone: '070-2345-6789',
    email: 'tanaka.misaki@example.com',
    address: '埼玉県越谷市大沢1-1',
    status: 'cancelled',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT24',
    store_name: 'JOYFIT24池袋店',
    reserved_at: makeVeDate(0, 13, 0),
    visit_start_at: null,
    visit_end_scheduled_at: makeVeDate(0, 13, 30),
    visit_end_actual_at: null,
    id_document_type: 'パスポート',
    id_document_verified: true,
    permit_issued_at: null,
    b01_auth_method: null,
    b01_gate: null,
    b01_entry_at: null,
    b01_exit_at: null,
    timeline: [
      {
        timestamp: makeVeDate(0, 12, 55),
        operator: 'システム',
        content: '予約キャンセル（本人申請）',
      },
      {
        timestamp: makeVeDate(0, 13, 0),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-005',
    customer_name: '伊藤 拓也',
    customer_name_kana: 'イトウ タクヤ',
    birth_date: '1985/07/22',
    phone: '080-4567-8901',
    email: 'ito.takuya@example.com',
    address: '東京都渋谷区広尾3-2-1',
    status: 'visiting',
    bl_match: true,
    bl_match_reason: '氏名＋生年月日一致',
    brand_name: 'JOYFIT',
    store_name: 'JOYFIT渋谷店',
    reserved_at: makeVeDate(0, 14, 0),
    visit_start_at: makeVeDate(0, 14, 10),
    visit_end_scheduled_at: makeVeDate(0, 14, 40),
    visit_end_actual_at: null,
    id_document_type: '運転免許証',
    id_document_verified: true,
    permit_issued_at: makeVeDate(0, 14, 8),
    b01_auth_method: '顔認証',
    b01_gate: 'メインエントランス',
    b01_entry_at: makeVeDate(0, 14, 10),
    b01_exit_at: null,
    timeline: [
      {
        timestamp: makeVeDate(0, 14, 10),
        operator: 'システム',
        content: '施設入館（顔認証）— 30分見学開始',
      },
      {
        timestamp: makeVeDate(0, 14, 8),
        operator: '管理者A',
        content: 'リスク確認の上、見学許可を発行（BL一致あり）',
      },
      {
        timestamp: makeVeDate(0, 14, 3),
        operator: 'システム',
        content: 'ブラックリスト照合: 一致あり（氏名＋生年月日）',
      },
      {
        timestamp: makeVeDate(0, 14, 0),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-006',
    customer_name: '渡辺 奈々',
    customer_name_kana: 'ワタナベ ナナ',
    birth_date: '1998/11/03',
    phone: null,
    email: 'watanabe.nana@example.com',
    address: null,
    status: 'info_missing',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT YOGA',
    store_name: 'JOYFIT YOGA恵比寿店',
    reserved_at: makeVeDate(0, 15, 0),
    visit_start_at: null,
    visit_end_scheduled_at: makeVeDate(0, 15, 30),
    visit_end_actual_at: null,
    id_document_type: null,
    id_document_verified: false,
    permit_issued_at: null,
    b01_auth_method: null,
    b01_gate: null,
    b01_entry_at: null,
    b01_exit_at: null,
    timeline: [
      {
        timestamp: makeVeDate(0, 15, 1),
        operator: 'システム',
        content: '情報不足を検出: 電話番号・住所・本人確認書類が未登録',
      },
      {
        timestamp: makeVeDate(0, 15, 0),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-007',
    customer_name: '中村 さくら',
    customer_name_kana: 'ナカムラ サクラ',
    birth_date: '1993/03/18',
    phone: '090-5678-9012',
    email: 'nakamura.sakura@example.com',
    address: '東京都新宿区歌舞伎町1-1-1',
    status: 'bl_checking',
    bl_match: true,
    bl_match_reason: '氏名一致',
    brand_name: 'JOYFIT',
    store_name: 'JOYFIT新宿店',
    reserved_at: makeVeDate(0, 16, 0),
    visit_start_at: null,
    visit_end_scheduled_at: makeVeDate(0, 16, 30),
    visit_end_actual_at: null,
    id_document_type: 'マイナンバーカード',
    id_document_verified: true,
    permit_issued_at: null,
    b01_auth_method: null,
    b01_gate: null,
    b01_entry_at: null,
    b01_exit_at: null,
    timeline: [
      {
        timestamp: makeVeDate(0, 16, 3),
        operator: 'システム',
        content: 'ブラックリスト照合: 一致あり（氏名）— スタッフ判断待ち',
      },
      {
        timestamp: makeVeDate(0, 16, 1),
        operator: 'システム',
        content: '個人情報・顔写真の登録確認完了',
      },
      {
        timestamp: makeVeDate(0, 16, 0),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-008',
    customer_name: '小林 翔太',
    customer_name_kana: 'コバヤシ ショウタ',
    birth_date: '1992/06/30',
    phone: '080-6789-0123',
    email: 'kobayashi.shota@example.com',
    address: '東京都渋谷区代々木1-1-1',
    status: 'visit_completed',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT',
    store_name: 'JOYFIT渋谷店',
    reserved_at: makeVeDate(-1, 10, 0),
    visit_start_at: makeVeDate(-1, 10, 5),
    visit_end_scheduled_at: makeVeDate(-1, 10, 35),
    visit_end_actual_at: makeVeDate(-1, 10, 55),
    id_document_type: '運転免許証',
    id_document_verified: true,
    permit_issued_at: makeVeDate(-1, 10, 3),
    b01_auth_method: '顔認証',
    b01_gate: 'メインエントランス',
    b01_entry_at: makeVeDate(-1, 10, 5),
    b01_exit_at: makeVeDate(-1, 10, 55),
    timeline: [
      {
        timestamp: makeVeDate(-1, 10, 55),
        operator: 'システム',
        content: '見学終了（施設退館確認）',
      },
      {
        timestamp: makeVeDate(-1, 10, 5),
        operator: 'システム',
        content: '施設入館（顔認証）— 30分見学開始',
      },
      {
        timestamp: makeVeDate(-1, 10, 3),
        operator: '管理者A',
        content: '見学許可を発行（30分間の時間制限入館）',
      },
      {
        timestamp: makeVeDate(-1, 10, 0),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-009',
    customer_name: '加藤 陽子',
    customer_name_kana: 'カトウ ヨウコ',
    birth_date: '1991/02/14',
    phone: '070-7890-1234',
    email: 'kato.yoko@example.com',
    address: '埼玉県さいたま市大宮区1-1',
    status: 'membership_applied',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT24',
    store_name: 'JOYFIT24池袋店',
    reserved_at: makeVeDate(-1, 13, 30),
    visit_start_at: makeVeDate(-1, 13, 35),
    visit_end_scheduled_at: makeVeDate(-1, 14, 5),
    visit_end_actual_at: makeVeDate(-1, 14, 25),
    id_document_type: 'マイナンバーカード',
    id_document_verified: true,
    permit_issued_at: makeVeDate(-1, 13, 33),
    b01_auth_method: '顔認証',
    b01_gate: 'メインエントランス',
    b01_entry_at: makeVeDate(-1, 13, 35),
    b01_exit_at: makeVeDate(-1, 14, 25),
    timeline: [
      {
        timestamp: makeVeDate(-1, 14, 30),
        operator: 'スタッフB',
        content: '入会申請フォームへ誘導',
      },
      {
        timestamp: makeVeDate(-1, 14, 25),
        operator: 'システム',
        content: '見学終了（施設退館確認）',
      },
      {
        timestamp: makeVeDate(-1, 13, 35),
        operator: 'システム',
        content: '施設入館（顔認証）— 30分見学開始',
      },
      {
        timestamp: makeVeDate(-1, 13, 33),
        operator: '管理者A',
        content: '見学許可を発行（30分間の時間制限入館）',
      },
      {
        timestamp: makeVeDate(-1, 13, 30),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-010',
    customer_name: '吉田 博',
    customer_name_kana: 'ヨシダ ヒロシ',
    birth_date: '1975/09/05',
    phone: '090-8901-2345',
    email: 'yoshida.hiroshi@example.com',
    address: '東京都渋谷区恵比寿1-1-1',
    status: 'cancelled',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT',
    store_name: 'JOYFIT渋谷店',
    reserved_at: makeVeDate(-1, 11, 0),
    visit_start_at: null,
    visit_end_scheduled_at: makeVeDate(-1, 11, 30),
    visit_end_actual_at: null,
    id_document_type: '運転免許証',
    id_document_verified: true,
    permit_issued_at: null,
    b01_auth_method: null,
    b01_gate: null,
    b01_entry_at: null,
    b01_exit_at: null,
    timeline: [
      {
        timestamp: makeVeDate(-1, 10, 50),
        operator: 'システム',
        content: '予約キャンセル（本人申請）',
      },
      {
        timestamp: makeVeDate(-1, 11, 0),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-011',
    customer_name: '山本 由美',
    customer_name_kana: 'ヤマモト ユミ',
    birth_date: '1987/05/20',
    phone: '080-9012-3456',
    email: 'yamamoto.yumi@example.com',
    address: '東京都目黒区自由が丘1-1',
    status: 'visit_completed',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT YOGA',
    store_name: 'JOYFIT YOGA恵比寿店',
    reserved_at: makeVeDate(-2, 9, 0),
    visit_start_at: makeVeDate(-2, 9, 10),
    visit_end_scheduled_at: makeVeDate(-2, 9, 40),
    visit_end_actual_at: makeVeDate(-2, 9, 58),
    id_document_type: 'パスポート',
    id_document_verified: true,
    permit_issued_at: makeVeDate(-2, 9, 8),
    b01_auth_method: '顔認証',
    b01_gate: 'メインエントランス',
    b01_entry_at: makeVeDate(-2, 9, 10),
    b01_exit_at: makeVeDate(-2, 9, 58),
    timeline: [
      {
        timestamp: makeVeDate(-2, 9, 58),
        operator: 'システム',
        content: '見学終了（施設退館確認）',
      },
      {
        timestamp: makeVeDate(-2, 9, 10),
        operator: 'システム',
        content: '施設入館（顔認証）— 30分見学開始',
      },
      {
        timestamp: makeVeDate(-2, 9, 8),
        operator: '管理者A',
        content: '見学許可を発行（30分間の時間制限入館）',
      },
      {
        timestamp: makeVeDate(-2, 9, 0),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-012',
    customer_name: '松本 浩二',
    customer_name_kana: 'マツモト コウジ',
    birth_date: '1983/10/28',
    phone: '090-0123-4567',
    email: 'matsumoto.koji@example.com',
    address: '東京都世田谷区三軒茶屋1-1',
    status: 'membership_applied',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT',
    store_name: 'JOYFIT新宿店',
    reserved_at: makeVeDate(-2, 14, 0),
    visit_start_at: makeVeDate(-2, 14, 8),
    visit_end_scheduled_at: makeVeDate(-2, 14, 38),
    visit_end_actual_at: makeVeDate(-2, 14, 50),
    id_document_type: '運転免許証',
    id_document_verified: true,
    permit_issued_at: makeVeDate(-2, 14, 6),
    b01_auth_method: '顔認証',
    b01_gate: 'メインエントランス',
    b01_entry_at: makeVeDate(-2, 14, 8),
    b01_exit_at: makeVeDate(-2, 14, 50),
    timeline: [
      {
        timestamp: makeVeDate(-2, 14, 55),
        operator: 'スタッフB',
        content: '入会申請フォームへ誘導',
      },
      {
        timestamp: makeVeDate(-2, 14, 50),
        operator: 'システム',
        content: '見学終了（施設退館確認）',
      },
      {
        timestamp: makeVeDate(-2, 14, 8),
        operator: 'システム',
        content: '施設入館（顔認証）— 30分見学開始',
      },
      {
        timestamp: makeVeDate(-2, 14, 6),
        operator: '管理者A',
        content: '見学許可を発行（30分間の時間制限入館）',
      },
      {
        timestamp: makeVeDate(-2, 14, 0),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-013',
    customer_name: '井上 千夏',
    customer_name_kana: 'イノウエ チナツ',
    birth_date: '1996/04/01',
    phone: '080-1234-0987',
    email: 'inoue.chinatsu@example.com',
    address: '埼玉県八潮市大曽根550',
    status: 'visit_completed',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT24',
    store_name: 'JOYFIT24池袋店',
    reserved_at: makeVeDate(-5, 10, 0),
    visit_start_at: makeVeDate(-5, 10, 3),
    visit_end_scheduled_at: makeVeDate(-5, 10, 33),
    visit_end_actual_at: makeVeDate(-5, 10, 58),
    id_document_type: 'マイナンバーカード',
    id_document_verified: true,
    permit_issued_at: makeVeDate(-5, 10, 2),
    b01_auth_method: '顔認証',
    b01_gate: 'メインエントランス',
    b01_entry_at: makeVeDate(-5, 10, 3),
    b01_exit_at: makeVeDate(-5, 10, 58),
    timeline: [
      {
        timestamp: makeVeDate(-5, 10, 58),
        operator: 'システム',
        content: '見学終了（施設退館確認）',
      },
      {
        timestamp: makeVeDate(-5, 10, 3),
        operator: 'システム',
        content: '施設入館（顔認証）— 30分見学開始',
      },
      {
        timestamp: makeVeDate(-5, 10, 2),
        operator: '管理者A',
        content: '見学許可を発行（30分間の時間制限入館）',
      },
      {
        timestamp: makeVeDate(-5, 10, 0),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-014',
    customer_name: '木村 悠斗',
    customer_name_kana: 'キムラ ユウト',
    birth_date: '1980/12/15',
    phone: '090-2345-1098',
    email: 'kimura.yuto@example.com',
    address: '東京都港区赤坂1-1-1',
    status: 'cancelled',
    bl_match: true,
    bl_match_reason: '氏名＋生年月日一致',
    brand_name: 'JOYFIT',
    store_name: 'JOYFIT渋谷店',
    reserved_at: makeVeDate(-5, 15, 30),
    visit_start_at: null,
    visit_end_scheduled_at: makeVeDate(-5, 16, 0),
    visit_end_actual_at: null,
    id_document_type: '運転免許証',
    id_document_verified: true,
    permit_issued_at: null,
    b01_auth_method: null,
    b01_gate: null,
    b01_entry_at: null,
    b01_exit_at: null,
    timeline: [
      {
        timestamp: makeVeDate(-5, 15, 35),
        operator: '管理者A',
        content: 'BL一致のため見学を許可せずキャンセル処理',
      },
      {
        timestamp: makeVeDate(-5, 15, 33),
        operator: 'システム',
        content: 'ブラックリスト照合: 一致あり（氏名＋生年月日）',
      },
      {
        timestamp: makeVeDate(-5, 15, 30),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-015',
    customer_name: '林 美穂',
    customer_name_kana: 'ハヤシ ミホ',
    birth_date: '1994/07/11',
    phone: '070-3456-2109',
    email: 'hayashi.miho@example.com',
    address: '東京都豊島区池袋1-1-1',
    status: 'membership_applied',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT YOGA',
    store_name: 'JOYFIT YOGA恵比寿店',
    reserved_at: makeVeDate(-8, 11, 0),
    visit_start_at: makeVeDate(-8, 11, 5),
    visit_end_scheduled_at: makeVeDate(-8, 11, 35),
    visit_end_actual_at: makeVeDate(-8, 11, 55),
    id_document_type: 'パスポート',
    id_document_verified: true,
    permit_issued_at: makeVeDate(-8, 11, 3),
    b01_auth_method: '顔認証',
    b01_gate: 'メインエントランス',
    b01_entry_at: makeVeDate(-8, 11, 5),
    b01_exit_at: makeVeDate(-8, 11, 55),
    timeline: [
      {
        timestamp: makeVeDate(-8, 12, 0),
        operator: 'スタッフB',
        content: '入会申請フォームへ誘導',
      },
      {
        timestamp: makeVeDate(-8, 11, 55),
        operator: 'システム',
        content: '見学終了（施設退館確認）',
      },
      {
        timestamp: makeVeDate(-8, 11, 5),
        operator: 'システム',
        content: '施設入館（顔認証）— 30分見学開始',
      },
      {
        timestamp: makeVeDate(-8, 11, 3),
        operator: '管理者A',
        content: '見学許可を発行（30分間の時間制限入館）',
      },
      {
        timestamp: makeVeDate(-8, 11, 0),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-016',
    customer_name: '清水 大輔',
    customer_name_kana: 'シミズ ダイスケ',
    birth_date: '1989/08/19',
    phone: '080-4567-3210',
    email: 'shimizu.daisuke@example.com',
    address: '東京都新宿区西新宿2-2-2',
    status: 'visit_completed',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT',
    store_name: 'JOYFIT新宿店',
    reserved_at: makeVeDate(-8, 14, 0),
    visit_start_at: makeVeDate(-8, 14, 10),
    visit_end_scheduled_at: makeVeDate(-8, 14, 40),
    visit_end_actual_at: makeVeDate(-8, 14, 59),
    id_document_type: '運転免許証',
    id_document_verified: true,
    permit_issued_at: makeVeDate(-8, 14, 8),
    b01_auth_method: '顔認証',
    b01_gate: 'メインエントランス',
    b01_entry_at: makeVeDate(-8, 14, 10),
    b01_exit_at: makeVeDate(-8, 14, 59),
    timeline: [
      {
        timestamp: makeVeDate(-8, 14, 59),
        operator: 'システム',
        content: '見学終了（施設退館確認）',
      },
      {
        timestamp: makeVeDate(-8, 14, 10),
        operator: 'システム',
        content: '施設入館（顔認証）— 30分見学開始',
      },
      {
        timestamp: makeVeDate(-8, 14, 8),
        operator: '管理者A',
        content: '見学許可を発行（30分間の時間制限入館）',
      },
      {
        timestamp: makeVeDate(-8, 14, 0),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-017',
    customer_name: '山口 彩香',
    customer_name_kana: 'ヤマグチ アヤカ',
    birth_date: '1997/03/25',
    phone: '090-5678-4321',
    email: 'yamaguchi.ayaka@example.com',
    address: '東京都中央区銀座2-2-2',
    status: 'application_received',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT+',
    store_name: 'JOYFIT+銀座店',
    reserved_at: makeVeDate(0, 17, 30),
    visit_start_at: null,
    visit_end_scheduled_at: makeVeDate(0, 18, 0),
    visit_end_actual_at: null,
    id_document_type: 'マイナンバーカード',
    id_document_verified: true,
    permit_issued_at: null,
    b01_auth_method: null,
    b01_gate: null,
    b01_entry_at: null,
    b01_exit_at: null,
    timeline: [
      {
        timestamp: makeVeDate(0, 17, 28),
        operator: 'システム',
        content: 'ブラックリスト照合完了（該当なし）',
      },
      {
        timestamp: makeVeDate(0, 17, 27),
        operator: 'システム',
        content: '個人情報・顔写真の登録確認完了',
      },
      {
        timestamp: makeVeDate(0, 17, 26),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
  {
    id: 'VE-018',
    customer_name: '前田 竜也',
    customer_name_kana: 'マエダ タツヤ',
    birth_date: '1986/11/30',
    phone: '080-6789-5432',
    email: 'maeda.tatsuya@example.com',
    address: '東京都中央区銀座3-3-3',
    status: 'visiting',
    bl_match: false,
    bl_match_reason: null,
    brand_name: 'JOYFIT+',
    store_name: 'JOYFIT+銀座店',
    reserved_at: makeVeDate(0, 16, 30),
    visit_start_at: makeVeDate(0, 16, 35),
    visit_end_scheduled_at: makeVeDate(0, 17, 5),
    visit_end_actual_at: null,
    id_document_type: '運転免許証',
    id_document_verified: true,
    permit_issued_at: makeVeDate(0, 16, 33),
    b01_auth_method: '顔認証',
    b01_gate: 'メインエントランス',
    b01_entry_at: makeVeDate(0, 16, 35),
    b01_exit_at: null,
    timeline: [
      {
        timestamp: makeVeDate(0, 16, 35),
        operator: 'システム',
        content: '施設入館（顔認証）— 30分見学開始',
      },
      {
        timestamp: makeVeDate(0, 16, 33),
        operator: '管理者A',
        content: '見学許可を発行（30分間の時間制限入館）',
      },
      {
        timestamp: makeVeDate(0, 16, 30),
        operator: 'システム',
        content: '見学申込受信（アプリ経由）',
      },
    ],
  },
];
