// Auto-generated route types
// Do not edit this file manually
import type { routeKeys, routePatterns, routes } from './routes.config';

export type RouteKey = (typeof routeKeys)[number];

export type RoutePattern = (typeof routePatterns)[number];

export type RouteConfig = {
  router: string | ((...args: (string | number)[]) => string);
  filePath: string;
  pattern: string;
  private: boolean | undefined;
};

// Router function types for type safety
export type RouterFunction<T extends RouteKey> = (typeof routes)[T]['router'];

// Extract parameter types from router functions
export type RouteParams<T extends RouteKey> =
  RouterFunction<T> extends (...args: infer P) => string ? P : [];

// Helper type to check if route requires parameters
export type RouteRequiresParams<T extends RouteKey> =
  RouterFunction<T> extends string ? false : true;
