// Auto-generated route utilities
// Do not edit this file manually
import { routeKeys, routes } from './routes.config';
import type { RouteConfig, RouteKey, RoutePattern, RouterFunction } from './routes.type';

type QueryParams = Record<string, string | number | boolean | null | undefined>;

/**
 * Get route configuration by key
 */
export function getRoute(key: RouteKey): RouteConfig {
  return routes[key];
}

/**
 * Navigate to a route with type-safe parameters
 *
 * @example
 * // Static route
 * navigate('/home') // '/home'
 *
 * // Dynamic route with parameters
 * navigate('/user/[id]', 123) // '/user/123'
 *
 * // Catch-all route
 * navigate('/blog/[...slug]', 'category', 'post-title') // '/blog/category/post-title'
 *
 * // Route with query params
 * navigate('/users', { name: 'Henry' }) // '/users?name=Henry'
 */
export function navigate<T extends RouteKey>(
  key: T,
  ...params: [...(RouterFunction<T> extends (...args: infer P) => string ? P : []), QueryParams?]
): string {
  const route = routes[key] as RouteConfig;
  const maybeQuery = params.at(-1);
  const queryParams =
    typeof maybeQuery === 'object' && maybeQuery !== null && !Array.isArray(maybeQuery)
      ? (params.pop() as QueryParams)
      : undefined;

  const basePath =
    typeof route.router === 'function'
      ? (route.router as (...args: (string | number)[]) => string)(
          ...(params as (string | number)[]),
        )
      : (route.router as string);

  if (!queryParams) {
    return basePath;
  }

  const queryString = new URLSearchParams(
    Object.entries(queryParams)
      .filter(([, value]) => value !== undefined && value !== null)
      .map(([queryKey, value]) => [queryKey, String(value)]),
  ).toString();

  if (!queryString) {
    return basePath;
  }

  return `${basePath}?${queryString}`;
}

/**
 * Check if a route is private
 */
export function isPrivateRoute(key: RouteKey): boolean {
  const route = routes[key] as RouteConfig;
  return route.private === true;
}

/**
 * Check if a route is public
 */
export function isPublicRoute(key: RouteKey): boolean {
  const route = routes[key] as RouteConfig;
  return route.private === false;
}

/**
 * Check if a route is shared
 */
export function isSharedRoute(key: RouteKey): boolean {
  const route = routes[key] as RouteConfig;
  return route.private === undefined;
}

/**
 * Get all routes by type
 */
export function getRoutesByType(type: 'private' | 'public' | 'shared'): RouteKey[] {
  const targetValue = type === 'private' ? true : type === 'public' ? false : undefined;
  return Object.keys(routes).filter((key) => {
    const route = routes[key as RouteKey] as RouteConfig;
    return route.private === targetValue;
  }) as RouteKey[];
}

/**
 * Get route pattern for matching
 */
export function getRoutePattern(key: RouteKey): RoutePattern {
  return routes[key].pattern as RoutePattern;
}

/**
 * Get route file path
 */
export function getRouteFilePath(key: RouteKey): string {
  return routes[key].filePath;
}

/**
 * Generate a regex for a route pattern
 */
export function generateRouteRegex(key: RouteKey): RegExp {
  return new RegExp('^' + getRoutePattern(key).replace(/:[^/]+/g, '[^/]+') + '$');
}

/**
 * Check if a route pattern matches a path
 */
export function checkRoutePattern(key: RouteKey, path: string): boolean {
  const routeRegex = generateRouteRegex(key);
  return routeRegex.test(path);
}

/**
 * Find a route pattern by path
 */
export function findPatternByPath(path: string): RoutePattern | undefined {
  const key = routeKeys.find((key) => {
    return generateRouteRegex(key).test(path);
  }) as RouteKey | undefined;
  return key ? getRoutePattern(key) : undefined;
}
