/**
 * - `PAGE_PERMISSIONS`: maps each route pattern to the Permission required to view it.
 *   Omitting a route means ALL authenticated roles can access it.
 *
 * - `ROLE_PERMISSIONS`: the full set of Permission values granted to each role.
 *   Includes both page-view permissions (used for routing) and action permissions
 *   (used by RoleGatedButton / RoleGatedMenuItem).
 */
import type { RoutePattern } from '@/lib/routes/routes.type';

import { Permission, UserRole } from '@/types/permission.type';

// ---------------------------------------------------------------------------
// Page-level access (route pattern → required Permission)
// ---------------------------------------------------------------------------
export const PAGE_PERMISSIONS: Partial<Record<RoutePattern, Permission>> = {
  // Staffs
  '/staffs': Permission.StaffsView,
  '/staffs/:id': Permission.StaffsView,
  '/staffs/:id/edit': Permission.StaffsEdit,

  // Stores
  '/stores': Permission.StoresView,
  '/stores/:id': Permission.StoresView,
  '/stores/:id/edit': Permission.StoresEdit,
  '/stores/create': Permission.StoresCreate,

  // Positions
  '/positions': Permission.PositionsView,

  // Members
  '/members': Permission.MembersView,
  '/members/:id': Permission.MembersView,
  '/members/:id/edit': Permission.MembersEdit,
  '/members/create': Permission.MembersCreate,
  '/members/blacklist': Permission.MembersBlacklistView,
  '/members/blacklist/:id': Permission.MembersBlacklistView,
  '/members/leaves': Permission.MembersLeavesView,
  '/members/leaves/:id': Permission.MembersLeavesView,
  '/members/transfers': Permission.MembersTransfersView,
  '/members/transfers/:id': Permission.MembersTransfersView,

  // Membership applications
  '/membership-applications': Permission.MembershipApplicationsView,
  '/membership-applications/:id': Permission.MembershipApplicationsView,
  '/membership-applications/create': Permission.MembershipApplicationsCreate,

  // Visit / experience management
  '/visit-experiences': Permission.VisitExperiencesView,
  '/visit-experiences/:id': Permission.VisitExperiencesView,

  // Family registrations
  '/family-registrations': Permission.FamilyRegistrationsView,
  '/family-registrations/:id': Permission.FamilyRegistrationsView,
  '/family-registrations/dashboard': Permission.FamilyRegistrationsDashboardView,

  // Contracts
  '/contracts': Permission.ContractsView,
  '/contracts/:id': Permission.ContractsView,
  '/contracts/create': Permission.ContractsCreate,
  '/contracts/:id/edit': Permission.ContractsEdit,

  // Campaigns
  '/campaigns': Permission.CampaignsView,
  '/campaigns/:id': Permission.CampaignsView,
  '/campaigns/create': Permission.CampaignsCreate,
  '/campaigns/:id/edit': Permission.CampaignsEdit,

  // Franchise companies
  '/franchise-companies': Permission.FCCompaniesView,
  '/franchise-companies/:id': Permission.FCCompaniesView,
  '/franchise-companies/create': Permission.FCCompaniesCreate,
  '/franchise-companies/:id/edit': Permission.FCCompaniesEdit,

  // Options
  '/options': Permission.OptionsView,
  '/options/:id': Permission.OptionsView,
  '/options/create': Permission.OptionsCreate,
  '/options/:id/edit': Permission.OptionsEdit,

  // Surveys
  '/surveys': Permission.SurveysView,
  '/surveys/:id': Permission.SurveysView,
  '/surveys/create': Permission.SurveysCreate,
  '/surveys/:id/edit': Permission.SurveysEdit,
  '/surveys/responses': Permission.SurveysView,
  '/surveys/responses/:responseId': Permission.SurveysView,
  '/surveys/analytics': Permission.SurveysView,

  // Manual notifications (I-03)
  '/manual-notifications': Permission.ManualNotificationsView,
  '/manual-notifications/:id': Permission.ManualNotificationsView,
  '/manual-notifications/create': Permission.ManualNotificationsCreate,
  '/manual-notifications/:id/edit': Permission.ManualNotificationsEdit,

  // Option discounts
  '/option-discount': Permission.OptionDiscountsView,
  '/option-discount/:id': Permission.OptionDiscountsView,
  '/option-discount/create': Permission.OptionDiscountsCreate,
  '/option-discount/:id/edit': Permission.OptionDiscountsEdit,

  // Brands
  '/brands': Permission.BrandsView,
  '/brands/:id': Permission.BrandsView,

  // Lockers
  '/lockers': Permission.LockersView,
  '/lockers/:id': Permission.LockersView,
  '/lockers/create': Permission.LockersCreate,
  '/lockers/:id/edit': Permission.LockersEdit,
  '/lockers/contracts': Permission.LockersContractsView,
  '/lockers/contracts/:id': Permission.LockersContractsView,
  '/lockers/contracts/create': Permission.LockersContractsCreate,
  '/lockers/contracts/:id/edit': Permission.LockersContractsEdit,
  '/lockers/pending': Permission.LockersPendingView,

  // Lessons / Reservations (D-01)
  // View is open to every authenticated role (incl. Observer); creating a
  // schedule requires the schedule-manage permission (denies Observer).
  '/lesson-schedules': Permission.LessonsView,
  '/lesson-schedules/create': Permission.LessonsScheduleManage,

  // Lesson Content Management (D-02)
  // Viewing the list + detail is open to every authenticated role; creating a
  // master (incl. duplicate) is restricted to Headquarter/System.
  '/lessons': Permission.LessonContentsView,
  '/lessons/:id': Permission.LessonContentsView,
  '/lessons/:id/edit': Permission.LessonContentsEdit,
  '/lessons/:id/duplicate': Permission.LessonContentsCreate,
  '/lessons/create': Permission.LessonContentsCreate,

  // Equipment
  '/equipment': Permission.EquipmentView,
  '/equipment/:id': Permission.EquipmentView,
  '/equipment/create': Permission.EquipmentCreate,
  '/equipment/:id/edit': Permission.EquipmentEdit,

  // Controllers
  '/controllers': Permission.ControllerView,
  '/controllers/:id': Permission.ControllerView,
  '/controllers/create': Permission.ControllerCreate,
  '/controllers/:id/edit': Permission.ControllerEdit,

  // Studios (D-03)
  '/studios': Permission.StudiosView,
  '/studios/:id': Permission.StudiosView,
  '/studios/:id/edit': Permission.StudiosEdit,
  '/studios/create': Permission.StudiosCreate,

  // Training equipment
  '/training-equipment': Permission.TrainingEquipmentView,
  '/training-equipment/:id': Permission.TrainingEquipmentView,
  '/training-equipment/create': Permission.TrainingEquipmentCreate,
  '/training-equipment/:id/edit': Permission.TrainingEquipmentEdit,

  // Terms
  '/terms': Permission.TermsView,
  '/terms/:id': Permission.TermsView,
  '/terms/create': Permission.TermsCreate,
  '/terms/:id/edit': Permission.TermsEdit,
};

// ---------------------------------------------------------------------------
// Role → full Permission set  (view + action)
// ---------------------------------------------------------------------------
export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  [UserRole.System]: Object.values(Permission),

  [UserRole.Headquarter]: [
    Permission.StaffsView,
    Permission.StaffsCreate,
    Permission.StaffsEdit,
    Permission.StaffsDelete,
    Permission.StaffsInvite,
    Permission.StoresView,
    Permission.StoresCreate,
    Permission.StoresEdit,
    Permission.StoresDelete,
    Permission.StoresConfigContract,
    Permission.StoresConfigAccess,
    Permission.StoresConfigBusiness,
    Permission.PositionsView,
    Permission.PositionsCreate,
    Permission.PositionsEdit,
    Permission.PositionsDelete,
    Permission.MembersView,
    Permission.MembersCreate,
    Permission.MembersEdit,
    Permission.MembersDelete,
    Permission.MembersPersonalDataEdit,
    Permission.MembersPersonalDataDelete,
    Permission.MembersReEnroll,
    Permission.MembersSuspend,
    Permission.MembersWithdraw,
    Permission.MembersTransfer,
    Permission.MembersGateStop,
    Permission.MembersForceWithdraw,
    Permission.MembersBlacklistView,
    Permission.BlacklistCreate,
    Permission.BlacklistDelete,
    Permission.MembersLeavesView,
    Permission.LeavesApprove,
    Permission.MembersTransfersView,
    Permission.TransfersApprove,
    Permission.MembershipApplicationsView,
    Permission.MembershipApplicationsCreate,
    Permission.MembershipApplicationsApprove,
    Permission.VisitExperiencesView,
    Permission.FamilyRegistrationsView,
    Permission.FamilyRegistrationsDashboardView,
    Permission.FamilyRegistrationsApprove,
    Permission.ContractsView,
    Permission.CampaignsView,
    Permission.CampaignsCreate,
    Permission.CampaignsEdit,
    Permission.CampaignsPromoCodeEdit,
    Permission.CampaignsPromoCodeCreate,
    Permission.CampaignsPromoCodeDelete,
    Permission.CampaignsPromoCodeExport,
    Permission.FCCompaniesView,
    Permission.FCCompaniesCreate,
    Permission.FCCompaniesEdit,
    Permission.FCCompaniesDelete,
    Permission.ContractsEdit,
    Permission.ContractsDelete,
    Permission.ContractsCreate,
    Permission.OptionsView,
    Permission.OptionsCreate,
    Permission.OptionsEdit,
    Permission.OptionsDelete,
    Permission.SurveysView,
    Permission.SurveysCreate,
    Permission.SurveysEdit,
    Permission.SurveysDelete,
    Permission.OptionDiscountsView,
    Permission.OptionDiscountsCreate,
    Permission.OptionDiscountsEdit,
    Permission.OptionDiscountsDelete,
    Permission.BrandsView,
    Permission.BrandsCreate,
    Permission.BrandsEdit,
    Permission.LockersView,
    Permission.LockersCreate,
    Permission.LockersEdit,
    Permission.LockersDelete,
    Permission.LockersExport,
    Permission.LockersPendingView,
    Permission.LockersPendingExport,
    Permission.LockersContractsView,
    Permission.LockersContractsCreate,
    Permission.LockersContractsEdit,
    Permission.LockersContractsExport,
    Permission.LessonsView,
    Permission.LessonsScheduleManage,
    Permission.LessonsReservationManage,
    Permission.LessonsAttendanceManage,
    Permission.LessonsMemoManage,
    Permission.LessonsPenaltyRelease,
    Permission.LessonContentsView,
    Permission.LessonContentsCreate,
    Permission.LessonContentsEdit,
    Permission.LessonContentsDelete,
    Permission.LessonContentsHistoryView,
    Permission.EquipmentView,
    Permission.EquipmentCreate,
    Permission.EquipmentEdit,
    Permission.EquipmentDelete,
    Permission.EquipmentExport,
    Permission.ControllerView,
    Permission.ControllerCreate,
    Permission.ControllerEdit,
    Permission.ControllerDelete,
    Permission.ControllerExport,
    Permission.StudiosView,
    Permission.StudiosCreate,
    Permission.StudiosEdit,
    Permission.StudiosDelete,
    Permission.TrainingEquipmentView,
    Permission.TrainingEquipmentCreate,
    Permission.TrainingEquipmentEdit,
    Permission.TrainingEquipmentDelete,
    Permission.TrainingEquipmentExport,
    Permission.TrainingEquipmentExerciseLinks,
    Permission.TermsView,
    Permission.TermsCreate,
    Permission.TermsEdit,
    Permission.TermsDelete,
    Permission.ManualNotificationsView,
    Permission.ManualNotificationsCreate,
    Permission.ManualNotificationsEdit,
    Permission.ManualNotificationsDelete,
    Permission.ManualNotificationsApprove,
  ],

  [UserRole.Manager]: [
    Permission.StaffsView,
    Permission.StoresView,
    Permission.MembersView,
    Permission.MembersCreate,
    Permission.MembersEdit,
    Permission.MembersReEnroll,
    Permission.MembersSuspend,
    Permission.MembersWithdraw,
    Permission.MembersTransfer,
    Permission.MembersGateStop,
    Permission.MembersLeavesView,
    Permission.MembersTransfersView,
    Permission.MembershipApplicationsView,
    Permission.MembershipApplicationsCreate,
    Permission.VisitExperiencesView,
    Permission.FamilyRegistrationsView,
    Permission.FamilyRegistrationsDashboardView,
    Permission.ContractsView,
    Permission.CampaignsView,
    Permission.CampaignsPromoCodeEdit,
    Permission.CampaignsPromoCodeCreate,
    Permission.CampaignsPromoCodeDelete,
    Permission.CampaignsPromoCodeExport,
    Permission.FCCompaniesView,
    Permission.OptionsView,
    Permission.BrandsView,
    Permission.LockersView,
    Permission.LockersCreate,
    Permission.LockersEdit,
    Permission.LockersDelete,
    Permission.LockersExport,
    Permission.LockersPendingView,
    Permission.LockersPendingExport,
    Permission.LockersContractsView,
    Permission.LockersContractsCreate,
    Permission.LockersContractsEdit,
    Permission.LockersContractsExport,
    Permission.SurveysView,
    Permission.LessonsView,
    Permission.LessonsScheduleManage,
    Permission.LessonsReservationManage,
    Permission.LessonsAttendanceManage,
    Permission.LessonsMemoManage,
    Permission.LessonsPenaltyRelease,
    Permission.LessonContentsView,
    Permission.EquipmentView,
    Permission.EquipmentCreate,
    Permission.EquipmentEdit,
    Permission.EquipmentDelete,
    Permission.EquipmentExport,
    Permission.ControllerView,
    Permission.ControllerCreate,
    Permission.ControllerEdit,
    Permission.ControllerDelete,
    Permission.ControllerExport,
    Permission.StudiosView,
    Permission.StudiosCreate,
    Permission.StudiosEdit,
    Permission.StudiosDelete,
    Permission.TermsView,
    Permission.ManualNotificationsView,
    Permission.ManualNotificationsCreate,
    Permission.ManualNotificationsEdit,
    Permission.ManualNotificationsDelete,
  ],

  [UserRole.Staff]: [
    Permission.StaffsView,
    Permission.StaffsEdit,
    Permission.StoresView,
    Permission.StoresCreate,
    Permission.StoresEdit,
    Permission.StoresConfigBusiness,
    Permission.MembersView,
    Permission.MembersCreate,
    Permission.MembersEdit,
    Permission.MembersReEnroll,
    Permission.MembersSuspend,
    Permission.MembersWithdraw,
    Permission.MembersTransfer,
    Permission.MembersGateStop,
    Permission.MembersLeavesView,
    Permission.MembersTransfersView,
    Permission.MembershipApplicationsView,
    Permission.MembershipApplicationsCreate,
    Permission.VisitExperiencesView,
    Permission.FamilyRegistrationsView,
    Permission.FamilyRegistrationsDashboardView,
    Permission.ContractsView,
    Permission.CampaignsView,
    Permission.CampaignsPromoCodeEdit,
    Permission.CampaignsPromoCodeCreate,
    Permission.CampaignsPromoCodeDelete,
    Permission.CampaignsPromoCodeExport,
    Permission.OptionsView,
    Permission.BrandsView,
    Permission.LockersView,
    Permission.LockersCreate,
    Permission.LockersEdit,
    Permission.LockersDelete,
    Permission.LockersExport,
    Permission.LockersPendingView,
    Permission.LockersPendingExport,
    Permission.LockersContractsView,
    Permission.LockersContractsCreate,
    Permission.LockersContractsEdit,
    Permission.LockersContractsExport,
    Permission.SurveysView,
    Permission.LessonsView,
    Permission.LessonsScheduleManage,
    Permission.LessonsReservationManage,
    Permission.LessonsAttendanceManage,
    Permission.LessonsMemoManage,
    Permission.LessonsPenaltyRelease,
    Permission.LessonContentsView,
    Permission.EquipmentView,
    Permission.EquipmentCreate,
    Permission.EquipmentEdit,
    Permission.EquipmentDelete,
    Permission.EquipmentExport,
    Permission.ControllerView,
    Permission.ControllerCreate,
    Permission.ControllerEdit,
    Permission.ControllerDelete,
    Permission.ControllerExport,
    Permission.StudiosView,
    Permission.StudiosCreate,
    Permission.StudiosEdit,
    Permission.TrainingEquipmentView,
    Permission.TrainingEquipmentCreate,
    Permission.TrainingEquipmentEdit,
    Permission.TrainingEquipmentExport,
    Permission.TermsView,
    Permission.ManualNotificationsView,
    Permission.ManualNotificationsCreate,
    Permission.ManualNotificationsEdit,
    Permission.ManualNotificationsDelete,
  ],

  // Trainer: own-session scope. Can manage their schedules/reservations/
  // attendance/memos but NOT release penalties (D-01 matrix).
  [UserRole.Trainer]: [
    Permission.MembersView,
    Permission.LessonsView,
    Permission.LessonsScheduleManage,
    Permission.LessonsReservationManage,
    Permission.LessonsAttendanceManage,
    Permission.LessonsMemoManage,
    Permission.LessonContentsView,
    Permission.StudiosView,
  ],

  // Observer: read-only. May view schedules but performs no mutations.
  [UserRole.Observer]: [
    Permission.MembersView,
    Permission.MembersLeavesView,
    Permission.MembersTransfersView,
    Permission.MembershipApplicationsView,
    Permission.VisitExperiencesView,
    Permission.FamilyRegistrationsView,
    Permission.FamilyRegistrationsDashboardView,
    Permission.LockersView,
    Permission.LockersPendingView,
    Permission.LockersPendingExport,
    Permission.LessonsView,
    Permission.LessonContentsView,
    Permission.EquipmentView,
    Permission.EquipmentExport,
    Permission.ControllerExport,
    Permission.StudiosView,
    Permission.ControllerView,
    Permission.TrainingEquipmentView,
    Permission.TrainingEquipmentExport,
    Permission.TermsView,
    Permission.ManualNotificationsView,
  ],
};
