/**
 * - `PAGE_PERMISSIONS`: maps each route pattern to the Permission required to view it.
 *   Omitting a route means ALL authenticated roles can access it.
 *
 * - `ROLE_PERMISSIONS`: the full set of Permission values granted to each role.
 *   Includes both page-view permissions (used for routing) and action permissions
 *   (used by RoleGatedButton / RoleGatedMenuItem).
 */
import type { RoutePattern } from '@/lib/routes/routes.type';

import { Permission, UserRole } from '@/types/permission.type';

// ---------------------------------------------------------------------------
// Page-level access (route pattern → required Permission)
// ---------------------------------------------------------------------------
export const PAGE_PERMISSIONS: Partial<Record<RoutePattern, Permission>> = {
  // Staffs
  '/staffs': Permission.StaffsView,
  '/staffs/:id': Permission.StaffsView,
  '/staffs/:id/edit': Permission.StaffsEdit,
  '/staffs/create': Permission.StaffsCreate,

  // Stores
  '/stores': Permission.StoresView,
  '/stores/:id': Permission.StoresView,
  '/stores/:id/edit': Permission.StoresEdit,
  '/stores/create': Permission.StoresCreate,

  // Positions
  '/positions': Permission.PositionsView,
  '/positions/create': Permission.PositionsCreate,
  '/positions/:id/edit': Permission.PositionsEdit,

  // Members
  '/members': Permission.MembersView,
  '/members/:id': Permission.MembersView,
  '/members/:id/edit': Permission.MembersEdit,
  '/members/blacklist': Permission.MembersBlacklistView,
  '/members/blacklist/:id': Permission.MembersBlacklistView,
  '/members/leaves': Permission.MembersLeavesView,
  '/members/leaves/:id': Permission.MembersLeavesView,
  '/members/transfers': Permission.MembersTransfersView,
  '/members/transfers/:id': Permission.MembersTransfersView,

  // Membership applications
  '/membership-applications': Permission.MembershipApplicationsView,
  '/membership-applications/:id': Permission.MembershipApplicationsView,
  '/membership-applications/create': Permission.MembershipApplicationsCreate,

  // Visit / experience management
  '/visit-experiences': Permission.VisitExperiencesView,
  '/visit-experiences/:id': Permission.VisitExperiencesView,

  // Family registrations
  '/family-registrations': Permission.FamilyRegistrationsView,
  '/family-registrations/:id': Permission.FamilyRegistrationsView,
  '/family-registrations/dashboard': Permission.FamilyRegistrationsDashboardView,

  // Contracts
  '/contracts': Permission.ContractsView,
  '/contracts/:id': Permission.ContractsView,
  '/contracts/create': Permission.ContractsCreate,
  '/contracts/:id/edit': Permission.ContractsEdit,

  // Campaigns
  '/campaigns': Permission.CampaignsView,
  '/campaigns/:id': Permission.CampaignsView,
  '/campaigns/create': Permission.CampaignsCreate,
  '/campaigns/:id/edit': Permission.CampaignsEdit,

  // Franchise companies
  '/franchise-companies': Permission.FCCompaniesView,
  '/franchise-companies/:id': Permission.FCCompaniesView,
  '/franchise-companies/create': Permission.FCCompaniesCreate,
  '/franchise-companies/:id/edit': Permission.FCCompaniesEdit,

  // Options
  '/options': Permission.OptionsView,
  '/options/:id': Permission.OptionsView,
  '/options/create': Permission.OptionsCreate,
  '/options/:id/edit': Permission.OptionsEdit,

  // Surveys
  '/surveys': Permission.SurveysView,
  '/surveys/:id': Permission.SurveysView,
  '/surveys/create': Permission.SurveysCreate,
  '/surveys/:id/edit': Permission.SurveysEdit,
  '/surveys/responses': Permission.SurveysView,
  '/surveys/responses/:responseId': Permission.SurveysView,
  '/surveys/analytics': Permission.SurveysView,

  // Manual notifications (I-03)
  '/manual-notifications': Permission.ManualNotificationsView,
  '/manual-notifications/:id': Permission.ManualNotificationsView,
  '/manual-notifications/create': Permission.ManualNotificationsCreate,
  '/manual-notifications/:id/edit': Permission.ManualNotificationsEdit,

  // Banners
  '/banners': Permission.BannersView,
  '/banners/create': Permission.BannersCreate,
  '/banners/:id/edit': Permission.BannersEdit,

  // Option discounts
  '/option-discount': Permission.OptionDiscountsView,
  '/option-discount/:id': Permission.OptionDiscountsView,
  '/option-discount/create': Permission.OptionDiscountsCreate,
  '/option-discount/:id/edit': Permission.OptionDiscountsEdit,

  // Brands
  '/brands': Permission.BrandsView,
  '/brands/:id': Permission.BrandsView,

  // Lockers
  '/lockers': Permission.LockersView,
  '/lockers/:id': Permission.LockersView,
  '/lockers/create': Permission.LockersCreate,
  '/lockers/:id/edit': Permission.LockersEdit,
  '/lockers/contracts': Permission.LockersContractsView,
  '/lockers/contracts/:id': Permission.LockersContractsView,
  '/lockers/contracts/:id/edit': Permission.LockersContractsEdit,
  '/lockers/pending': Permission.LockersPendingView,

  // Lessons / Reservations (D-01)
  // View is open to every authenticated role (incl. Observer); creating a
  // schedule requires the schedule-manage permission (denies Observer).
  '/lesson-schedules': Permission.LessonsView,
  '/lesson-schedules/create': Permission.LessonsScheduleManage,

  // Lesson Content Management (D-02)
  // Viewing the list + detail is open to every authenticated role; creating a
  // master (incl. duplicate) is restricted to Headquarter/System.
  '/lessons': Permission.LessonContentsView,
  '/lessons/:id': Permission.LessonContentsView,
  '/lessons/:id/edit': Permission.LessonContentsEdit,
  '/lessons/:id/duplicate': Permission.LessonContentsCreate,
  '/lessons/create': Permission.LessonContentsCreate,

  // Exercises
  '/exercises': Permission.ExercisesView,
  '/exercises/:id': Permission.ExercisesView,
  '/exercises/create': Permission.ExercisesCreate,
  '/exercises/:id/edit': Permission.ExercisesEdit,
  '/exercise-master': Permission.ExercisesCreate,

  // Equipment
  '/equipment': Permission.EquipmentView,
  '/equipment/:id': Permission.EquipmentView,
  '/equipment/create': Permission.EquipmentCreate,
  '/equipment/:id/edit': Permission.EquipmentEdit,

  // Controllers
  '/controllers': Permission.ControllerView,
  '/controllers/:id': Permission.ControllerView,
  '/controllers/create': Permission.ControllerCreate,
  '/controllers/:id/edit': Permission.ControllerEdit,

  // Studios (D-03)
  '/studios': Permission.StudiosView,
  '/studios/:id': Permission.StudiosView,
  '/studios/:id/edit': Permission.StudiosEdit,
  '/studios/create': Permission.StudiosCreate,

  // Training equipment
  '/training-equipment': Permission.TrainingEquipmentView,
  '/training-equipment/:id': Permission.TrainingEquipmentView,
  '/training-equipment/create': Permission.TrainingEquipmentCreate,
  '/training-equipment/:id/edit': Permission.TrainingEquipmentEdit,

  // Instructors (D-04)
  // View is open to every authenticated role (Trainer/Observer scoped server-side);
  // creating a profile requires InstructorsCreate (denies Trainer/Observer). Edit is
  // intentionally NOT page-gated here because a Trainer may edit their own profile —
  // that exception is enforced server-side and via RoleGatedButton's allowedRoles.
  '/instructors': Permission.InstructorsView,
  '/instructors/:id': Permission.InstructorsView,
  '/instructors/create': Permission.InstructorsCreate,

  // Entry / Exit management
  '/entry-exit': Permission.EntryExitView,
  '/entry-exit/history': Permission.EntryExitHistoryView,

  // Article categories
  '/article-categories': Permission.ArticleCategoriesView,
  '/article-categories/create': Permission.ArticleCategoriesCreate,
  '/article-categories/:id/edit': Permission.ArticleCategoriesEdit,

  // App Version Management (Y-05)
  '/app-versions': Permission.AppVersionsView,
  '/app-versions/:id': Permission.AppVersionsView,
  '/app-versions/create': Permission.AppVersionsCreate,
  '/app-versions/:id/edit': Permission.AppVersionsEdit,

  // App Maintenance
  '/app-maintenance': Permission.AppMaintenanceView,
  '/app-maintenance/create': Permission.AppMaintenanceCreate,
  '/app-maintenance/:id/edit': Permission.AppMaintenanceEdit,

  // Terms Document Master Management (Y-04) — Trainer has no access at all (FR-006);
  // Manager/Staff/Observer are view-only (brand-scoped server-side); create/edit/
  // new-version require Headquarter/System (FR-017)
  '/terms': Permission.TermsView,
  '/terms/:id': Permission.TermsView,
  '/terms/create': Permission.TermsCreate,
  '/terms/:id/edit': Permission.TermsEdit,
  '/terms/:id/new-version': Permission.TermsCreate,

  // Sales Management (F-01)
  '/sales': Permission.SalesView,
  '/sales/:id': Permission.SalesView,
  '/sales/register': Permission.SalesView,

  // Sales — Transaction History, Receivables, Refund Management (F-01-01/02/03)
  // Refund queue viewing is open to HQ/Manager/Staff (FR-014); only the approve/reject
  // action itself is gated by SalesRefundApprove + canApproveRefund (research.md §5).
  '/sales/transactions': Permission.SalesTransactionsView,
  '/sales/receivables': Permission.SalesReceivablesView,
  '/sales/refunds': Permission.SalesRefundsView,

  // Routines (Y-09) — Headquarter / System only
  '/routines': Permission.RoutinesView,
  '/routines/:id': Permission.RoutinesView,
  '/routines/create': Permission.RoutinesCreate,
  '/routines/:id/edit': Permission.RoutinesEdit,

  // CRM Maintenance (Y-10) — list/detail: System + Headquarter; create/edit: System only
  '/crm-maintenance': Permission.CrmMaintenanceView,
  '/crm-maintenance/:id': Permission.CrmMaintenanceView,
  '/crm-maintenance/create': Permission.CrmMaintenanceCreate,
  '/crm-maintenance/:id/edit': Permission.CrmMaintenanceEdit,
};

// ---------------------------------------------------------------------------
// Role → full Permission set  (view + action)
// ---------------------------------------------------------------------------
export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  [UserRole.System]: Object.values(Permission),

  [UserRole.Headquarter]: [
    Permission.StaffsView,
    Permission.StaffsCreate,
    Permission.StaffsEdit,
    Permission.StaffsDelete,
    Permission.StaffsInvite,
    Permission.StoresView,
    Permission.StoresCreate,
    Permission.StoresEdit,
    Permission.StoresDelete,
    Permission.StoresConfigContract,
    Permission.StoresConfigAccess,
    Permission.StoresConfigBusiness,
    Permission.PositionsView,
    Permission.PositionsCreate,
    Permission.PositionsEdit,
    Permission.PositionsDelete,
    Permission.MembersView,
    Permission.MembersEdit,
    Permission.MembersDelete,
    Permission.MembersPersonalDataDelete,
    Permission.MembersReEnroll,
    Permission.MembersSuspend,
    Permission.MembersWithdraw,
    Permission.MembersTransfer,
    Permission.MembersGateStop,
    Permission.MembersForceWithdraw,
    Permission.MembersOptionContractOperate,
    Permission.MembersBlacklistView,
    Permission.BlacklistCreate,
    Permission.BlacklistDelete,
    Permission.MembersLeavesView,
    Permission.MembersTransfersView,
    Permission.MembersTransfersApprove,
    Permission.MembersTransfersBulkApprove,
    Permission.MembersTransfersUnlock,
    Permission.MembershipApplicationsView,
    Permission.MembershipApplicationsCreate,
    Permission.MembershipApplicationsApprove,
    Permission.MembershipApplicationsCancel,
    Permission.VisitExperiencesView,
    Permission.FamilyRegistrationsView,
    Permission.FamilyRegistrationsDashboardView,
    Permission.FamilyRegistrationsApprove,
    Permission.ContractsView,
    Permission.CampaignsView,
    Permission.CampaignsCreate,
    Permission.CampaignsEdit,
    Permission.CampaignsPromoCodeEdit,
    Permission.CampaignsPromoCodeCreate,
    Permission.CampaignsPromoCodeDelete,
    Permission.CampaignsPromoCodeExport,
    Permission.FCCompaniesView,
    Permission.FCCompaniesCreate,
    Permission.FCCompaniesEdit,
    Permission.FCCompaniesDelete,
    Permission.ContractsEdit,
    Permission.ContractsDelete,
    Permission.ContractsCreate,
    Permission.OptionsView,
    Permission.OptionsCreate,
    Permission.OptionsEdit,
    Permission.OptionsDelete,
    Permission.SurveysView,
    Permission.SurveysCreate,
    Permission.SurveysEdit,
    Permission.SurveysDelete,
    Permission.BannersView,
    Permission.BannersCreate,
    Permission.BannersEdit,
    Permission.BannersDelete,
    Permission.BannersReorder,
    Permission.OptionDiscountsView,
    Permission.OptionDiscountsCreate,
    Permission.OptionDiscountsEdit,
    Permission.OptionDiscountsDelete,
    Permission.BrandsView,
    Permission.BrandsCreate,
    Permission.BrandsEdit,
    Permission.LockersView,
    Permission.LockersCreate,
    Permission.LockersEdit,
    Permission.LockersDelete,
    Permission.LockersExport,
    Permission.LockersPendingView,
    Permission.LockersPendingExport,
    Permission.LockersContractsView,
    Permission.LockersContractsEdit,
    Permission.LockersContractsExport,
    Permission.LessonsView,
    Permission.LessonsScheduleManage,
    Permission.LessonsReservationManage,
    Permission.LessonsAttendanceManage,
    Permission.LessonsMemoManage,
    Permission.LessonsPenaltyRelease,
    Permission.LessonContentsView,
    Permission.LessonContentsCreate,
    Permission.LessonContentsEdit,
    Permission.LessonContentsDelete,
    Permission.LessonContentsHistoryView,
    Permission.ExercisesView,
    Permission.ExercisesCreate,
    Permission.ExercisesEdit,
    Permission.ExercisesDelete,
    Permission.ExercisesPublish,
    Permission.EquipmentView,
    Permission.EquipmentCreate,
    Permission.EquipmentEdit,
    Permission.EquipmentDelete,
    Permission.EquipmentExport,
    Permission.ControllerView,
    Permission.ControllerCreate,
    Permission.ControllerEdit,
    Permission.ControllerDelete,
    Permission.ControllerExport,
    Permission.StudiosView,
    Permission.StudiosCreate,
    Permission.StudiosEdit,
    Permission.StudiosDelete,
    Permission.TrainingEquipmentView,
    Permission.TrainingEquipmentCreate,
    Permission.TrainingEquipmentEdit,
    Permission.TrainingEquipmentDelete,
    Permission.TrainingEquipmentExport,
    Permission.TrainingEquipmentExerciseLinks,
    Permission.InstructorsView,
    Permission.InstructorsCreate,
    Permission.InstructorsEdit,
    Permission.InstructorsDelete,
    Permission.EntryExitView,
    Permission.EntryExitHistoryView,
    Permission.EntryExitHistoryExport,
    Permission.ArticleCategoriesView,
    Permission.ArticleCategoriesCreate,
    Permission.ArticleCategoriesEdit,
    Permission.ArticleCategoriesDelete,
    Permission.AppVersionsView,
    Permission.AppVersionsCreate,
    Permission.AppVersionsEdit,
    Permission.AppVersionsDelete,
    Permission.AppMaintenanceView,
    Permission.TermsView,
    Permission.TermsCreate,
    Permission.TermsEdit,
    Permission.TermsDelete,
    Permission.ManualNotificationsView,
    Permission.ManualNotificationsCreate,
    Permission.ManualNotificationsEdit,
    Permission.ManualNotificationsDelete,
    Permission.ManualNotificationsApprove,
    Permission.CrmMaintenanceView,
    Permission.SalesView,
    Permission.SalesConfirm,
    Permission.SalesRefundInitiate,
    Permission.SalesLineItemAdd,
    Permission.SalesFeeAdjust,
    Permission.SalesManualRegister,
    Permission.SalesExport,
    Permission.SalesTransactionsView,
    Permission.SalesReceivablesView,
    Permission.SalesRefundsView,
    Permission.SalesBadDebtExclude,
    Permission.SalesConvenienceIssue,
    Permission.SalesUpcomingBillingConfirm,
    Permission.SalesRefundApprove,
    Permission.SalesRefundExport,
    Permission.AppMaintenanceCreate,
    Permission.AppMaintenanceEdit,
    Permission.AppMaintenanceDelete,
    Permission.RoutinesView,
    Permission.RoutinesCreate,
    Permission.RoutinesEdit,
    Permission.RoutinesDelete,
    Permission.RoutinesPublish,
  ],

  [UserRole.Manager]: [
    Permission.StaffsView,
    // Page-level only: grants navigation to /staffs/:id/edit. Manager may edit only
    // "Staff"-role accounts in their managed store (FR-003) — that per-resource scoping
    // is enforced server-side (GET/PATCH /crm/staffs/{id}), not by this flag.
    Permission.StaffsEdit,
    Permission.StoresView,
    Permission.MembersView,
    Permission.MembersReEnroll,
    Permission.MembersSuspend,
    Permission.MembersWithdraw,
    Permission.MembersTransfer,
    Permission.MembersGateStop,
    Permission.MembersOptionContractOperate,
    Permission.MembersLeavesView,
    Permission.MembersTransfersView,
    // A-02: Manager holds the full transfer toolkit, but only within their 所轄店舗 scope.
    Permission.MembersTransfersApprove,
    Permission.MembersTransfersBulkApprove,
    Permission.MembersTransfersUnlock,
    Permission.MembershipApplicationsView,
    Permission.MembershipApplicationsCreate,
    Permission.MembershipApplicationsApprove,
    Permission.MembershipApplicationsCancel,
    Permission.VisitExperiencesView,
    Permission.FamilyRegistrationsView,
    Permission.FamilyRegistrationsDashboardView,
    Permission.ContractsView,
    Permission.CampaignsView,
    Permission.CampaignsPromoCodeEdit,
    Permission.CampaignsPromoCodeCreate,
    Permission.CampaignsPromoCodeDelete,
    Permission.CampaignsPromoCodeExport,
    Permission.OptionsView,
    Permission.BrandsView,
    Permission.LockersView,
    Permission.LockersCreate,
    Permission.LockersEdit,
    Permission.LockersDelete,
    Permission.LockersExport,
    Permission.LockersPendingView,
    Permission.LockersPendingExport,
    Permission.LockersContractsView,
    Permission.LockersContractsEdit,
    Permission.LockersContractsExport,
    Permission.SurveysView,
    Permission.BannersView,
    Permission.LessonsView,
    Permission.LessonsScheduleManage,
    Permission.LessonsReservationManage,
    Permission.LessonsAttendanceManage,
    Permission.LessonsMemoManage,
    Permission.LessonsPenaltyRelease,
    Permission.LessonContentsView,
    Permission.EquipmentView,
    Permission.EquipmentCreate,
    Permission.EquipmentEdit,
    Permission.EquipmentDelete,
    Permission.EquipmentExport,
    Permission.ControllerView,
    Permission.ControllerCreate,
    Permission.ControllerEdit,
    Permission.ControllerDelete,
    Permission.ControllerExport,
    Permission.StudiosView,
    Permission.StudiosCreate,
    Permission.StudiosEdit,
    Permission.StudiosDelete,
    Permission.InstructorsView,
    Permission.InstructorsCreate,
    Permission.InstructorsEdit,
    Permission.InstructorsDelete,
    Permission.EntryExitView,
    Permission.EntryExitHistoryView,
    Permission.EntryExitHistoryExport,
    Permission.ArticleCategoriesView,
    Permission.SalesView,
    Permission.SalesConfirm,
    Permission.SalesRefundInitiate,
    Permission.SalesLineItemAdd,
    Permission.SalesFeeAdjust,
    Permission.SalesManualRegister,
    Permission.SalesExport,
    Permission.SalesTransactionsView,
    Permission.SalesReceivablesView,
    Permission.SalesRefundsView,
    Permission.SalesBadDebtExclude,
    Permission.SalesConvenienceIssue,
    Permission.SalesUpcomingBillingConfirm,
    Permission.SalesRefundApprove,
    Permission.SalesRefundExport,
    Permission.AppMaintenanceView,
    Permission.TermsView,
    Permission.AppVersionsView,
    Permission.ManualNotificationsView,
    Permission.ManualNotificationsCreate,
    Permission.ManualNotificationsEdit,
    Permission.ManualNotificationsDelete,
  ],

  [UserRole.Staff]: [
    // Y-01 permission matrix: スタッフ一覧・参照 = ○ 自分のみ (self only). StaffsView
    // must stay granted so /staffs and /staffs/:id don't 403 — server-side scoping
    // (GET /crm/staffs, GET /crm/staffs/{id}) narrows the actual rows to the caller's
    // own record. StaffsEdit stays denied: Staff may only reference their own account,
    // not edit it via this screen (FR-013).
    Permission.StaffsView,
    // Permission.StaffsEdit,
    Permission.StoresView,
    Permission.StoresCreate,
    Permission.StoresEdit,
    Permission.StoresConfigBusiness,
    Permission.MembersView,
    Permission.MembersReEnroll,
    Permission.MembersSuspend,
    Permission.MembersWithdraw,
    Permission.MembersTransfer,
    Permission.MembersGateStop,
    Permission.MembersOptionContractOperate,
    Permission.MembersLeavesView,
    Permission.MembersTransfersView,
    // A-02: Staff may approve/reject, but only their own store's side at the current stage —
    // enforced row-by-row by `canActOnTransfer`. No bulk approve, no 手動解除.
    Permission.MembersTransfersApprove,
    Permission.MembershipApplicationsView,
    // C-01: 承認・否認/管理画面入会 are 職位に依る — deferred until per-position permissioning exists.
    // Permission.MembershipApplicationsCreate,
    // Permission.MembershipApplicationsApprove,
    // 入会取り消し is separate and unconditional for Staff (store-scoped).
    Permission.MembershipApplicationsCancel,
    Permission.VisitExperiencesView,
    Permission.FamilyRegistrationsView,
    Permission.FamilyRegistrationsDashboardView,
    Permission.ContractsView,
    Permission.CampaignsView,
    Permission.CampaignsPromoCodeEdit,
    Permission.CampaignsPromoCodeCreate,
    Permission.CampaignsPromoCodeDelete,
    Permission.FCCompaniesView,
    Permission.OptionsView,
    Permission.BrandsView,
    Permission.LockersView,
    Permission.LockersCreate,
    Permission.LockersEdit,
    Permission.LockersDelete,
    Permission.LockersExport,
    Permission.LockersPendingView,
    Permission.LockersPendingExport,
    Permission.LockersContractsView,
    Permission.LockersContractsEdit,
    Permission.LockersContractsExport,
    Permission.SurveysView,
    Permission.BannersView,
    Permission.LessonsView,
    Permission.LessonsScheduleManage,
    Permission.LessonsReservationManage,
    Permission.LessonsAttendanceManage,
    Permission.LessonsMemoManage,
    Permission.LessonsPenaltyRelease,
    Permission.LessonContentsView,
    Permission.EquipmentView,
    Permission.EquipmentCreate,
    Permission.EquipmentEdit,
    Permission.EquipmentDelete,
    Permission.EquipmentExport,
    Permission.ControllerView,
    Permission.ControllerCreate,
    Permission.ControllerEdit,
    Permission.ControllerDelete,
    Permission.ControllerExport,
    Permission.StudiosView,
    Permission.StudiosCreate,
    Permission.StudiosEdit,
    Permission.TrainingEquipmentView,
    Permission.TrainingEquipmentCreate,
    Permission.TrainingEquipmentEdit,
    Permission.TrainingEquipmentExport,
    Permission.InstructorsView,
    Permission.InstructorsCreate,
    Permission.InstructorsEdit,
    Permission.InstructorsDelete,
    Permission.EntryExitView,
    Permission.ArticleCategoriesView,
    Permission.TermsView,
    Permission.ManualNotificationsView,
    Permission.ManualNotificationsCreate,
    Permission.ManualNotificationsEdit,
    Permission.ManualNotificationsDelete,
    Permission.AppVersionsView,
    Permission.SalesView,
    // Permission.SalesConfirm,
    Permission.SalesRefundInitiate,
    Permission.SalesLineItemAdd,
    // Permission.SalesFeeAdjust,
    Permission.SalesManualRegister,
    Permission.SalesTransactionsView,
    Permission.SalesReceivablesView,
    Permission.SalesRefundsView,
    Permission.SalesConvenienceIssue,
    // Permission.SalesUpcomingBillingConfirm,
    Permission.AppMaintenanceView,
  ],

  // Trainer: own-session scope. Can manage their schedules/reservations/
  // attendance/memos but NOT release penalties (D-01 matrix). Instructor
  // self-edit is granted dynamically via RoleGatedButton's allowedRoles,
  // not this static permission (InstructorsEdit stays HQ/Manager/Staff-only).
  [UserRole.Trainer]: [
    Permission.LessonsView,
    Permission.LessonsScheduleManage,
    Permission.LessonsReservationManage,
    Permission.LessonsAttendanceManage,
    Permission.LessonsMemoManage,
    Permission.LessonContentsView,
    Permission.StudiosView,
    Permission.BannersView,
    Permission.InstructorsView,
  ],

  // Observer: read-only. May view schedules but performs no mutations.
  [UserRole.Observer]: [
    Permission.MembersView,
    Permission.MembersLeavesView,
    Permission.MembersTransfersView,
    Permission.MembershipApplicationsView,
    Permission.VisitExperiencesView,
    Permission.FamilyRegistrationsView,
    Permission.FamilyRegistrationsDashboardView,
    Permission.LockersView,
    Permission.LockersPendingView,
    Permission.LockersPendingExport,
    Permission.LessonsView,
    Permission.LessonContentsView,
    Permission.EquipmentView,
    Permission.EquipmentExport,
    Permission.ControllerExport,
    Permission.StudiosView,
    Permission.ControllerView,
    Permission.TrainingEquipmentView,
    Permission.TrainingEquipmentExport,
    Permission.BannersView,
    Permission.EntryExitView,
    Permission.EntryExitHistoryView,
    Permission.ArticleCategoriesView,
    Permission.AppMaintenanceView,
    Permission.InstructorsView,
    Permission.TermsView,
    Permission.AppVersionsView,
    Permission.ManualNotificationsView,
  ],
};
