import type {
  MainContractChangeHistoryItem,
  MainContractDetail,
  MainContractListItem,
} from '@/app/api/_schemas/main-contract.schema';

export function createBrandTables() {
  return {
    mainContracts: {
      _rows: [] as MainContractListItem[],
      _seeded: false,
      _seed(): void {
        if (this._seeded) return;
        this._seeded = true;
        this._rows.push(
          {
            id: 'MC001',
            name: 'レギュラー会員',
            code: 'REG-001',
            old_code: 'OLD-REG-001',
            contract_type: 'general',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 7700,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 1250,
            other_store_usage: 'all',
            companion_benefit_enabled: true,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC001-A',
            name: 'レギュラー会員（学生）',
            code: 'REG-001S',
            old_code: 'OLD-REG-001S',
            contract_type: 'general',
            brand: 'joyfit',
            parent_contract_name: 'レギュラー会員',
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 5500,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 180,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC002',
            name: 'デイタイム会員',
            code: 'DAY-001',
            old_code: 'OLD-DAY-001',
            contract_type: 'general',
            brand: 'fit365',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 6600,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 820,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC003',
            name: 'ナイト会員',
            code: 'NIT-001',
            old_code: null,
            contract_type: 'general',
            brand: 'joyfit24',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 5500,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 450,
            other_store_usage: 'direct',
            companion_benefit_enabled: false,
            enabled_stores: 1,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC004',
            name: 'ウィークエンド会員',
            code: 'WKD-001',
            old_code: null,
            contract_type: 'general',
            brand: 'fit365',
            parent_contract_name: null,
            start_date: '2024/06/01',
            target_store_name: null,
            price_including_tax: 4400,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 320,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC005',
            name: '1Day利用',
            code: '1DAY-001',
            old_code: null,
            contract_type: 'oneDay',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 1650,
            suspension_fee: 0,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '―',
            cancellable_months: '―',
            active_contracts: 0,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC006',
            name: 'ファミリー会員（親）',
            code: 'FAM-001',
            old_code: 'OLD-FAM-001',
            contract_type: 'family',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 7700,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 210,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC006-A',
            name: 'ファミリー会員（子・大人）',
            code: 'FAM-001A',
            old_code: null,
            contract_type: 'family',
            brand: 'joyfit',
            parent_contract_name: 'ファミリー会員（親）',
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 4400,
            suspension_fee: 550,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 85,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC006-B',
            name: 'ファミリー会員（子・学生）',
            code: 'FAM-001B',
            old_code: null,
            contract_type: 'family',
            brand: 'joyfit',
            parent_contract_name: 'ファミリー会員（親）',
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 3300,
            suspension_fee: 550,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 45,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC007',
            name: '法人会員',
            code: 'CORP-001',
            old_code: 'OLD-CORP-001',
            contract_type: 'corporate',
            brand: 'fit365',
            parent_contract_name: null,
            start_date: '2024/07/01',
            target_store_name: null,
            price_including_tax: 6600,
            suspension_fee: 0,
            monthly_limit: 8,
            tax_rate: 10,
            suspendable_months: '―',
            cancellable_months: '毎月',
            active_contracts: 35,
            other_store_usage: 'none',
            companion_benefit_enabled: false,
            enabled_stores: 1,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC008',
            name: '体験利用',
            code: 'TRIAL-001',
            old_code: null,
            contract_type: 'oneDay',
            brand: 'joyfit24',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 0,
            suspension_fee: 0,
            monthly_limit: 1,
            tax_rate: 10,
            suspendable_months: '―',
            cancellable_months: '―',
            active_contracts: 0,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC009',
            name: 'プレミアム会員',
            code: 'PRM-001',
            old_code: null,
            contract_type: 'special',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2025/01/01',
            target_store_name: null,
            price_including_tax: 11000,
            suspension_fee: 2200,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '毎月',
            cancellable_months: '毎月',
            active_contracts: 0,
            other_store_usage: 'all',
            companion_benefit_enabled: true,
            enabled_stores: 0,
            total_stores: 12,
            status: 'inactive',
          },
          {
            id: 'MC010',
            name: 'スタッフ会員（当店限定）',
            code: 'SPC-010',
            old_code: null,
            contract_type: 'special',
            brand: 'joyfit24',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: 'JOYFIT24新宿店',
            price_including_tax: 0,
            suspension_fee: 0,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '―',
            cancellable_months: '毎月',
            active_contracts: 18,
            other_store_usage: 'direct',
            companion_benefit_enabled: true,
            enabled_stores: 1,
            total_stores: 12,
            status: 'inactive',
          },
          {
            id: 'MC011',
            name: 'ファミリー会員',
            code: 'FAM-010',
            old_code: null,
            contract_type: 'family',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 8800,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 276,
            other_store_usage: 'all',
            companion_benefit_enabled: true,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC012',
            name: 'キッズ会員',
            code: 'KID-001',
            old_code: null,
            contract_type: 'kids',
            brand: 'fit365',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 4400,
            suspension_fee: 550,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 140,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC013',
            name: '法人スタンダード',
            code: 'CORP-STD',
            old_code: null,
            contract_type: 'corporate',
            brand: 'joyfit24',
            parent_contract_name: null,
            start_date: '2024/07/01',
            target_store_name: null,
            price_including_tax: 9900,
            suspension_fee: 0,
            monthly_limit: 12,
            tax_rate: 10,
            suspendable_months: '―',
            cancellable_months: '毎月',
            active_contracts: 52,
            other_store_usage: 'none',
            companion_benefit_enabled: false,
            enabled_stores: 2,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC014',
            name: '福利厚生プラン',
            code: 'WEL-001',
            old_code: null,
            contract_type: 'welfare',
            brand: 'fit365',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 7150,
            suspension_fee: 550,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 98,
            other_store_usage: 'direct',
            companion_benefit_enabled: false,
            enabled_stores: 4,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC015',
            name: 'プリペイド30',
            code: 'PRE-030',
            old_code: null,
            contract_type: 'prepaid',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 3300,
            suspension_fee: 0,
            monthly_limit: 30,
            tax_rate: 10,
            suspendable_months: '―',
            cancellable_months: '毎月',
            active_contracts: 72,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC016',
            name: '朝活会員',
            code: 'MOR-001',
            old_code: null,
            contract_type: 'general',
            brand: 'joyfit_yoga',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 6050,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 64,
            other_store_usage: 'direct',
            companion_benefit_enabled: false,
            enabled_stores: 2,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC017',
            name: '平日デイ会員',
            code: 'WKD-DAY',
            old_code: null,
            contract_type: 'general',
            brand: 'joyfit_plus',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 6600,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 128,
            other_store_usage: 'direct',
            companion_benefit_enabled: false,
            enabled_stores: 3,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC018',
            name: 'シニア午前会員',
            code: 'SPC-SEN',
            old_code: null,
            contract_type: 'special',
            brand: 'joyfit24',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: 'JOYFIT24 新宿店',
            price_including_tax: 3850,
            suspension_fee: 550,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 54,
            other_store_usage: 'direct',
            companion_benefit_enabled: false,
            enabled_stores: 1,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC019',
            name: '学生ナイト会員',
            code: 'STD-NIT',
            old_code: null,
            contract_type: 'student',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 4950,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 96,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC020',
            name: 'Weekend会員',
            code: 'WEN-001',
            old_code: null,
            contract_type: 'general',
            brand: 'fit365',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 5720,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 288,
            other_store_usage: 'all',
            companion_benefit_enabled: true,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
        );
      },
      getList(): MainContractListItem[] {
        this._seed();
        return [...this._rows];
      },
      _details: {} as Record<string, MainContractDetail>,
      _changeHistory: {} as Record<string, MainContractChangeHistoryItem[]>,
      getById(id: string): MainContractDetail | undefined {
        this._seed();
        if (Object.keys(this._details).length === 0) {
          const detailExtras: Record<string, Partial<MainContractDetail>> = {
            MC001: {
              changeability: '可能',
              previous_contract: null,
              billing_enabled: true,
              modifiable: '可能',
              initial_payment_months: 1,
              same_day_cancellation: false,
              family_contract_allowed: false,
              suspension_monthly_limit: null,
              usage_schedule: '終日（24時間）',
              company: null,
              regulation: null,
              public_name: 'レギュラー（全時間利用可）',
              public_description:
                '全時間帯利用可能な標準的な会員プラン。24時間いつでも全店舗のトレーニング施設を利用できます。初心者から上級者まで幅広い会員層に対応。',
              memo: null,
              usage_hours_by_day: [
                { day: '月', from: '06:00', to: '23:00', all_day: false },
                { day: '火', from: '06:00', to: '23:00', all_day: false },
                { day: '水', from: '06:00', to: '23:00', all_day: false },
                { day: '木', from: '06:00', to: '23:00', all_day: false },
                { day: '金', from: '06:00', to: '23:00', all_day: false },
                { day: '土', from: '08:00', to: '21:00', all_day: false },
                { day: '日', from: '08:00', to: '21:00', all_day: false },
              ],
              accounting_code: 'ACC-101',
              age_restriction: '16歳以上',
              gender_restriction: '制限なし',
              store_range: '全店舗（12店舗）',
              thumbnail_url: null,
              description:
                '全時間帯利用可能な標準的な会員プラン。24時間いつでも全店舗のトレーニング施設を利用できます。初心者から上級者まで幅広い会員層に対応。',
              created_at: '2024/03/15 10:00',
              updated_at: '2026/02/28 14:30',
              parent_contract_id: 'MC000',
              parent_contract_name: 'スタンダード会員',
              child_contracts: [
                { id: 'MC001-A', name: 'レギュラー会員（学生）' },
                { id: 'MC001-B', name: 'レギュラー会員（シニア）' },
              ],
            },
            MC009: {
              changeability: '可能',
              previous_contract: null,
              billing_enabled: true,
              modifiable: '可能',
              initial_payment_months: 1,
              same_day_cancellation: false,
              family_contract_allowed: false,
              suspension_monthly_limit: null,
              usage_schedule: '終日（24時間）',
              company: null,
              regulation: null,
              public_name: 'プレミアム（全時間利用可・特典付）',
              public_description:
                'プレミアム会員専用の最上位プラン。全時間帯利用可・同伴特典あり。',
              memo: null,
              usage_hours_by_day: [
                { day: '月', from: '00:00', to: '23:59', all_day: true },
                { day: '火', from: '00:00', to: '23:59', all_day: true },
                { day: '水', from: '00:00', to: '23:59', all_day: true },
                { day: '木', from: '00:00', to: '23:59', all_day: true },
                { day: '金', from: '00:00', to: '23:59', all_day: true },
                { day: '土', from: '00:00', to: '23:59', all_day: true },
                { day: '日', from: '00:00', to: '23:59', all_day: true },
              ],
              accounting_code: 'ACC-901',
              age_restriction: '16歳以上',
              gender_restriction: '制限なし',
              store_range: '全店舗（12店舗）',
              thumbnail_url: null,
              description: 'プレミアム会員専用の最上位プラン。全時間帯利用可・同伴特典あり。',
              created_at: '2024/12/15 10:00',
              updated_at: '2026/01/10 14:30',
              parent_contract_id: null,
              parent_contract_name: null,
              child_contracts: [],
            },
          };
          for (const row of this._rows) {
            const extras = detailExtras[row.id] ?? {
              changeability: '可能',
              previous_contract: null,
              billing_enabled: true,
              modifiable: '可能',
              initial_payment_months: 1,
              same_day_cancellation: false,
              family_contract_allowed: false,
              suspension_monthly_limit: null,
              usage_schedule: '終日（24時間）',
              company: null,
              regulation: null,
              public_name: row.name,
              public_description: '',
              memo: null,
              usage_hours_by_day: [
                { day: '月', from: '06:00', to: '23:00', all_day: false },
                { day: '火', from: '06:00', to: '23:00', all_day: false },
                { day: '水', from: '06:00', to: '23:00', all_day: false },
                { day: '木', from: '06:00', to: '23:00', all_day: false },
                { day: '金', from: '06:00', to: '23:00', all_day: false },
                { day: '土', from: '08:00', to: '21:00', all_day: false },
                { day: '日', from: '08:00', to: '21:00', all_day: false },
              ],
              accounting_code: 'ACC-000',
              age_restriction: '16歳以上',
              gender_restriction: '制限なし',
              store_range: `全店舗（${row.total_stores}店舗）`,
              thumbnail_url: null,
              description: '',
              created_at: '2024/04/01 10:00',
              updated_at: '2024/04/01 10:00',
              parent_contract_id: row.parent_contract_name ? 'MC000' : null,
              parent_contract_name: row.parent_contract_name ?? null,
              child_contracts: [],
            };
            this._details[row.id] = { ...row, ...extras } as MainContractDetail;
          }
        }
        return this._details[id];
      },
      getChangeHistory(id: string): MainContractChangeHistoryItem[] {
        const defaultHistory: MainContractChangeHistoryItem[] = [
          {
            date: '2026/02/28 14:30',
            user: '管理者A',
            field: '説明文',
            from: '全時間帯利用可能な標準的な会員プラン。',
            to: '全時間帯利用可能な標準的な会員プラン。24時間いつでも全店舗のトレーニング施設を利用できます...',
          },
          {
            date: '2025/10/01 09:00',
            user: '管理者B',
            field: '料金（税込）',
            from: '¥7,150',
            to: '¥7,700',
          },
          {
            date: '2025/07/01 10:00',
            user: '管理者C',
            field: '最低契約期間',
            from: '1ヶ月',
            to: '3ヶ月',
          },
          {
            date: '2025/04/01 10:00',
            user: '管理者A',
            field: 'ステータス',
            from: '無効',
            to: '有効',
          },
          { date: '2024/03/15 10:00', user: '管理者A', field: null, from: null, to: '新規作成' },
        ];
        if (!this._changeHistory[id]) {
          this._changeHistory[id] = defaultHistory;
        }
        return this._changeHistory[id];
      },
      delete(id: string): boolean {
        this._seed();
        const idx = this._rows.findIndex((r) => r.id === id);
        if (idx === -1) return false;
        this._rows.splice(idx, 1);
        delete this._details[id];
        delete this._changeHistory[id];
        return true;
      },
      add(contract: MainContractDetail): void {
        this._seed();
        const listItem: MainContractListItem = {
          id: contract.id,
          name: contract.name,
          code: contract.code,
          old_code: contract.old_code,
          contract_type: contract.contract_type,
          brand: contract.brand,
          parent_contract_name: contract.parent_contract_name,
          start_date: contract.start_date,
          target_store_name: contract.target_store_name,
          price_including_tax: contract.price_including_tax,
          suspension_fee: contract.suspension_fee,
          monthly_limit: contract.monthly_limit,
          tax_rate: contract.tax_rate,
          suspendable_months: contract.suspendable_months,
          cancellable_months: contract.cancellable_months,
          active_contracts: contract.active_contracts,
          other_store_usage: contract.other_store_usage,
          companion_benefit_enabled: contract.companion_benefit_enabled,
          enabled_stores: contract.enabled_stores,
          total_stores: contract.total_stores,
          status: contract.status,
        };
        this._rows.push(listItem);
        this._details[contract.id] = contract;
      },
      update(id: string, data: Partial<MainContractDetail>): MainContractDetail | undefined {
        this._seed();
        const existing = this._details[id];
        if (!existing) return undefined;
        const updated = { ...existing, ...data, id, updated_at: new Date().toISOString() };
        this._details[id] = updated;
        const idx = this._rows.findIndex((r) => r.id === id);
        if (idx !== -1) {
          this._rows[idx] = {
            ...this._rows[idx],
            name: updated.name,
            code: updated.code,
            old_code: updated.old_code,
            contract_type: updated.contract_type,
            brand: updated.brand,
            status: updated.status,
            companion_benefit_enabled: updated.companion_benefit_enabled,
            other_store_usage: updated.other_store_usage,
            price_including_tax: updated.price_including_tax,
            suspension_fee: updated.suspension_fee,
            monthly_limit: updated.monthly_limit,
            tax_rate: updated.tax_rate,
            start_date: updated.start_date,
            suspendable_months: updated.suspendable_months,
            cancellable_months: updated.cancellable_months,
            parent_contract_name: updated.parent_contract_name,
          };
        }
        return updated;
      },
    },
  };
}
