import type {
  CampaignChangeHistoryItem,
  CampaignDetail,
  CampaignListItem,
} from '@/app/api/_schemas/campaign.schema';
import type {
  MainContractChangeHistoryItem,
  MainContractDetail,
  MainContractListItem,
} from '@/app/api/_schemas/main-contract.schema';
import type { Position } from '@/app/api/_schemas/position.schema';
import type { PromoCodeRecord, PromoCodeUpsertBody } from '@/app/api/_schemas/promo-code.schema';

import type { DbType } from '../_db.types';
import { SEED_POSITION_ROWS } from '../seeds/position.seed';

export function createBrandTables(getDb: () => DbType) {
  return {
    positions: {
      _rows: [] as Position[],
      _seeded: false,
      _seed(): void {
        if (this._seeded) return;
        this._seeded = true;
        this._rows.push(...SEED_POSITION_ROWS);
      },
      getList(): Position[] {
        this._seed();
        return [...this._rows];
      },
      getById(id: number): Position | undefined {
        this._seed();
        return this._rows.find((p) => p.id === id);
      },
    },

    mainContracts: {
      _rows: [] as MainContractListItem[],
      _seeded: false,
      _seed(): void {
        if (this._seeded) return;
        this._seeded = true;
        this._rows.push(
          {
            id: 'MC001',
            name: 'レギュラー会員',
            code: 'REG-001',
            old_code: 'OLD-REG-001',
            contract_type: 'general',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 7700,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 1250,
            other_store_usage: 'all',
            companion_benefit_enabled: true,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC001-A',
            name: 'レギュラー会員（学生）',
            code: 'REG-001S',
            old_code: 'OLD-REG-001S',
            contract_type: 'general',
            brand: 'joyfit',
            parent_contract_name: 'レギュラー会員',
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 5500,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 180,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC002',
            name: 'デイタイム会員',
            code: 'DAY-001',
            old_code: 'OLD-DAY-001',
            contract_type: 'general',
            brand: 'fit365',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 6600,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 820,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC003',
            name: 'ナイト会員',
            code: 'NIT-001',
            old_code: null,
            contract_type: 'general',
            brand: 'joyfit24',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 5500,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 450,
            other_store_usage: 'direct',
            companion_benefit_enabled: false,
            enabled_stores: 1,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC004',
            name: 'ウィークエンド会員',
            code: 'WKD-001',
            old_code: null,
            contract_type: 'general',
            brand: 'fit365',
            parent_contract_name: null,
            start_date: '2024/06/01',
            target_store_name: null,
            price_including_tax: 4400,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 320,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC005',
            name: '1Day利用',
            code: '1DAY-001',
            old_code: null,
            contract_type: 'oneDay',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 1650,
            suspension_fee: 0,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '―',
            cancellable_months: '―',
            active_contracts: 0,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC006',
            name: 'ファミリー会員（親）',
            code: 'FAM-001',
            old_code: 'OLD-FAM-001',
            contract_type: 'family',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 7700,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 210,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC006-A',
            name: 'ファミリー会員（子・大人）',
            code: 'FAM-001A',
            old_code: null,
            contract_type: 'family',
            brand: 'joyfit',
            parent_contract_name: 'ファミリー会員（親）',
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 4400,
            suspension_fee: 550,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 85,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC006-B',
            name: 'ファミリー会員（子・学生）',
            code: 'FAM-001B',
            old_code: null,
            contract_type: 'family',
            brand: 'joyfit',
            parent_contract_name: 'ファミリー会員（親）',
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 3300,
            suspension_fee: 550,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 45,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC007',
            name: '法人会員',
            code: 'CORP-001',
            old_code: 'OLD-CORP-001',
            contract_type: 'corporate',
            brand: 'fit365',
            parent_contract_name: null,
            start_date: '2024/07/01',
            target_store_name: null,
            price_including_tax: 6600,
            suspension_fee: 0,
            monthly_limit: 8,
            tax_rate: 10,
            suspendable_months: '―',
            cancellable_months: '毎月',
            active_contracts: 35,
            other_store_usage: 'none',
            companion_benefit_enabled: false,
            enabled_stores: 1,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC008',
            name: '体験利用',
            code: 'TRIAL-001',
            old_code: null,
            contract_type: 'oneDay',
            brand: 'joyfit24',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 0,
            suspension_fee: 0,
            monthly_limit: 1,
            tax_rate: 10,
            suspendable_months: '―',
            cancellable_months: '―',
            active_contracts: 0,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC009',
            name: 'プレミアム会員',
            code: 'PRM-001',
            old_code: null,
            contract_type: 'special',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2025/01/01',
            target_store_name: null,
            price_including_tax: 11000,
            suspension_fee: 2200,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '毎月',
            cancellable_months: '毎月',
            active_contracts: 0,
            other_store_usage: 'all',
            companion_benefit_enabled: true,
            enabled_stores: 0,
            total_stores: 12,
            status: 'inactive',
          },
          {
            id: 'MC010',
            name: 'スタッフ会員（当店限定）',
            code: 'SPC-010',
            old_code: null,
            contract_type: 'special',
            brand: 'joyfit24',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: 'JOYFIT24新宿店',
            price_including_tax: 0,
            suspension_fee: 0,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '―',
            cancellable_months: '毎月',
            active_contracts: 18,
            other_store_usage: 'direct',
            companion_benefit_enabled: true,
            enabled_stores: 1,
            total_stores: 12,
            status: 'inactive',
          },
          {
            id: 'MC011',
            name: 'ファミリー会員',
            code: 'FAM-010',
            old_code: null,
            contract_type: 'family',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 8800,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 276,
            other_store_usage: 'all',
            companion_benefit_enabled: true,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC012',
            name: 'キッズ会員',
            code: 'KID-001',
            old_code: null,
            contract_type: 'kids',
            brand: 'fit365',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 4400,
            suspension_fee: 550,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 140,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC013',
            name: '法人スタンダード',
            code: 'CORP-STD',
            old_code: null,
            contract_type: 'corporate',
            brand: 'joyfit24',
            parent_contract_name: null,
            start_date: '2024/07/01',
            target_store_name: null,
            price_including_tax: 9900,
            suspension_fee: 0,
            monthly_limit: 12,
            tax_rate: 10,
            suspendable_months: '―',
            cancellable_months: '毎月',
            active_contracts: 52,
            other_store_usage: 'none',
            companion_benefit_enabled: false,
            enabled_stores: 2,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC014',
            name: '福利厚生プラン',
            code: 'WEL-001',
            old_code: null,
            contract_type: 'welfare',
            brand: 'fit365',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 7150,
            suspension_fee: 550,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 98,
            other_store_usage: 'direct',
            companion_benefit_enabled: false,
            enabled_stores: 4,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC015',
            name: 'プリペイド30',
            code: 'PRE-030',
            old_code: null,
            contract_type: 'prepaid',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 3300,
            suspension_fee: 0,
            monthly_limit: 30,
            tax_rate: 10,
            suspendable_months: '―',
            cancellable_months: '毎月',
            active_contracts: 72,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC016',
            name: '朝活会員',
            code: 'MOR-001',
            old_code: null,
            contract_type: 'general',
            brand: 'joyfit_yoga',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 6050,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 64,
            other_store_usage: 'direct',
            companion_benefit_enabled: false,
            enabled_stores: 2,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC017',
            name: '平日デイ会員',
            code: 'WKD-DAY',
            old_code: null,
            contract_type: 'general',
            brand: 'joyfit_plus',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 6600,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 128,
            other_store_usage: 'direct',
            companion_benefit_enabled: false,
            enabled_stores: 3,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC018',
            name: 'シニア午前会員',
            code: 'SPC-SEN',
            old_code: null,
            contract_type: 'special',
            brand: 'joyfit24',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: 'JOYFIT24 新宿店',
            price_including_tax: 3850,
            suspension_fee: 550,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 54,
            other_store_usage: 'direct',
            companion_benefit_enabled: false,
            enabled_stores: 1,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC019',
            name: '学生ナイト会員',
            code: 'STD-NIT',
            old_code: null,
            contract_type: 'student',
            brand: 'joyfit',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 4950,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 96,
            other_store_usage: 'all',
            companion_benefit_enabled: false,
            enabled_stores: 10,
            total_stores: 12,
            status: 'active',
          },
          {
            id: 'MC020',
            name: 'Weekend会員',
            code: 'WEN-001',
            old_code: null,
            contract_type: 'general',
            brand: 'fit365',
            parent_contract_name: null,
            start_date: '2024/04/01',
            target_store_name: null,
            price_including_tax: 5720,
            suspension_fee: 1100,
            monthly_limit: null,
            tax_rate: 10,
            suspendable_months: '1〜3月',
            cancellable_months: '毎月',
            active_contracts: 288,
            other_store_usage: 'all',
            companion_benefit_enabled: true,
            enabled_stores: 12,
            total_stores: 12,
            status: 'active',
          },
        );
      },
      getList(): MainContractListItem[] {
        this._seed();
        return [...this._rows];
      },
      _details: {} as Record<string, MainContractDetail>,
      _changeHistory: {} as Record<string, MainContractChangeHistoryItem[]>,
      getById(id: string): MainContractDetail | undefined {
        this._seed();
        if (Object.keys(this._details).length === 0) {
          const detailExtras: Record<string, Partial<MainContractDetail>> = {
            MC001: {
              changeability: '可能',
              previous_contract: null,
              billing_enabled: true,
              modifiable: '可能',
              initial_payment_months: 1,
              same_day_cancellation: false,
              family_contract_allowed: false,
              suspension_monthly_limit: null,
              usage_schedule: '終日（24時間）',
              company: null,
              regulation: null,
              public_name: 'レギュラー（全時間利用可）',
              public_description:
                '全時間帯利用可能な標準的な会員プラン。24時間いつでも全店舗のトレーニング施設を利用できます。初心者から上級者まで幅広い会員層に対応。',
              memo: null,
              usage_hours_by_day: [
                { day: '月', from: '06:00', to: '23:00', all_day: false },
                { day: '火', from: '06:00', to: '23:00', all_day: false },
                { day: '水', from: '06:00', to: '23:00', all_day: false },
                { day: '木', from: '06:00', to: '23:00', all_day: false },
                { day: '金', from: '06:00', to: '23:00', all_day: false },
                { day: '土', from: '08:00', to: '21:00', all_day: false },
                { day: '日', from: '08:00', to: '21:00', all_day: false },
              ],
              accounting_code: 'ACC-101',
              age_restriction: '16歳以上',
              gender_restriction: '制限なし',
              store_range: '全店舗（12店舗）',
              thumbnail_url: null,
              description:
                '全時間帯利用可能な標準的な会員プラン。24時間いつでも全店舗のトレーニング施設を利用できます。初心者から上級者まで幅広い会員層に対応。',
              created_at: '2024/03/15 10:00',
              updated_at: '2026/02/28 14:30',
              parent_contract_id: 'MC000',
              parent_contract_name: 'スタンダード会員',
              child_contracts: [
                { id: 'MC001-A', name: 'レギュラー会員（学生）' },
                { id: 'MC001-B', name: 'レギュラー会員（シニア）' },
              ],
            },
            MC009: {
              changeability: '可能',
              previous_contract: null,
              billing_enabled: true,
              modifiable: '可能',
              initial_payment_months: 1,
              same_day_cancellation: false,
              family_contract_allowed: false,
              suspension_monthly_limit: null,
              usage_schedule: '終日（24時間）',
              company: null,
              regulation: null,
              public_name: 'プレミアム（全時間利用可・特典付）',
              public_description:
                'プレミアム会員専用の最上位プラン。全時間帯利用可・同伴特典あり。',
              memo: null,
              usage_hours_by_day: [
                { day: '月', from: '00:00', to: '23:59', all_day: true },
                { day: '火', from: '00:00', to: '23:59', all_day: true },
                { day: '水', from: '00:00', to: '23:59', all_day: true },
                { day: '木', from: '00:00', to: '23:59', all_day: true },
                { day: '金', from: '00:00', to: '23:59', all_day: true },
                { day: '土', from: '00:00', to: '23:59', all_day: true },
                { day: '日', from: '00:00', to: '23:59', all_day: true },
              ],
              accounting_code: 'ACC-901',
              age_restriction: '16歳以上',
              gender_restriction: '制限なし',
              store_range: '全店舗（12店舗）',
              thumbnail_url: null,
              description: 'プレミアム会員専用の最上位プラン。全時間帯利用可・同伴特典あり。',
              created_at: '2024/12/15 10:00',
              updated_at: '2026/01/10 14:30',
              parent_contract_id: null,
              parent_contract_name: null,
              child_contracts: [],
            },
          };
          for (const row of this._rows) {
            const extras = detailExtras[row.id] ?? {
              changeability: '可能',
              previous_contract: null,
              billing_enabled: true,
              modifiable: '可能',
              initial_payment_months: 1,
              same_day_cancellation: false,
              family_contract_allowed: false,
              suspension_monthly_limit: null,
              usage_schedule: '終日（24時間）',
              company: null,
              regulation: null,
              public_name: row.name,
              public_description: '',
              memo: null,
              usage_hours_by_day: [
                { day: '月', from: '06:00', to: '23:00', all_day: false },
                { day: '火', from: '06:00', to: '23:00', all_day: false },
                { day: '水', from: '06:00', to: '23:00', all_day: false },
                { day: '木', from: '06:00', to: '23:00', all_day: false },
                { day: '金', from: '06:00', to: '23:00', all_day: false },
                { day: '土', from: '08:00', to: '21:00', all_day: false },
                { day: '日', from: '08:00', to: '21:00', all_day: false },
              ],
              accounting_code: 'ACC-000',
              age_restriction: '16歳以上',
              gender_restriction: '制限なし',
              store_range: `全店舗（${row.total_stores}店舗）`,
              thumbnail_url: null,
              description: '',
              created_at: '2024/04/01 10:00',
              updated_at: '2024/04/01 10:00',
              parent_contract_id: row.parent_contract_name ? 'MC000' : null,
              parent_contract_name: row.parent_contract_name ?? null,
              child_contracts: [],
            };
            this._details[row.id] = { ...row, ...extras } as MainContractDetail;
          }
        }
        return this._details[id];
      },
      getChangeHistory(id: string): MainContractChangeHistoryItem[] {
        const defaultHistory: MainContractChangeHistoryItem[] = [
          {
            date: '2026/02/28 14:30',
            user: '管理者A',
            field: '説明文',
            from: '全時間帯利用可能な標準的な会員プラン。',
            to: '全時間帯利用可能な標準的な会員プラン。24時間いつでも全店舗のトレーニング施設を利用できます...',
          },
          {
            date: '2025/10/01 09:00',
            user: '管理者B',
            field: '料金（税込）',
            from: '¥7,150',
            to: '¥7,700',
          },
          {
            date: '2025/07/01 10:00',
            user: '管理者C',
            field: '最低契約期間',
            from: '1ヶ月',
            to: '3ヶ月',
          },
          {
            date: '2025/04/01 10:00',
            user: '管理者A',
            field: 'ステータス',
            from: '無効',
            to: '有効',
          },
          { date: '2024/03/15 10:00', user: '管理者A', field: null, from: null, to: '新規作成' },
        ];
        if (!this._changeHistory[id]) {
          this._changeHistory[id] = defaultHistory;
        }
        return this._changeHistory[id];
      },
      delete(id: string): boolean {
        this._seed();
        const idx = this._rows.findIndex((r) => r.id === id);
        if (idx === -1) return false;
        this._rows.splice(idx, 1);
        delete this._details[id];
        delete this._changeHistory[id];
        return true;
      },
      add(contract: MainContractDetail): void {
        this._seed();
        const listItem: MainContractListItem = {
          id: contract.id,
          name: contract.name,
          code: contract.code,
          old_code: contract.old_code,
          contract_type: contract.contract_type,
          brand: contract.brand,
          parent_contract_name: contract.parent_contract_name,
          start_date: contract.start_date,
          target_store_name: contract.target_store_name,
          price_including_tax: contract.price_including_tax,
          suspension_fee: contract.suspension_fee,
          monthly_limit: contract.monthly_limit,
          tax_rate: contract.tax_rate,
          suspendable_months: contract.suspendable_months,
          cancellable_months: contract.cancellable_months,
          active_contracts: contract.active_contracts,
          other_store_usage: contract.other_store_usage,
          companion_benefit_enabled: contract.companion_benefit_enabled,
          enabled_stores: contract.enabled_stores,
          total_stores: contract.total_stores,
          status: contract.status,
        };
        this._rows.push(listItem);
        this._details[contract.id] = contract;
      },
      update(id: string, data: Partial<MainContractDetail>): MainContractDetail | undefined {
        this._seed();
        const existing = this._details[id];
        if (!existing) return undefined;
        const updated = { ...existing, ...data, id, updated_at: new Date().toISOString() };
        this._details[id] = updated;
        const idx = this._rows.findIndex((r) => r.id === id);
        if (idx !== -1) {
          this._rows[idx] = {
            ...this._rows[idx],
            name: updated.name,
            code: updated.code,
            old_code: updated.old_code,
            contract_type: updated.contract_type,
            brand: updated.brand,
            status: updated.status,
            companion_benefit_enabled: updated.companion_benefit_enabled,
            other_store_usage: updated.other_store_usage,
            price_including_tax: updated.price_including_tax,
            suspension_fee: updated.suspension_fee,
            monthly_limit: updated.monthly_limit,
            tax_rate: updated.tax_rate,
            start_date: updated.start_date,
            suspendable_months: updated.suspendable_months,
            cancellable_months: updated.cancellable_months,
            parent_contract_name: updated.parent_contract_name,
          };
        }
        return updated;
      },
    },

    campaigns: {
      _rows: [] as CampaignListItem[],
      _details: {} as Record<string, CampaignDetail>,
      _changeHistory: {} as Record<string, CampaignChangeHistoryItem[]>,
      _seeded: false,
      _seed(): void {
        if (this._seeded) return;
        this._seeded = true;
        this._rows.push(
          {
            id: 'CP001',
            name: '春の入会キャンペーン',
            code: 'STR01A1B2C',
            brand: 'joyfit',
            recruitment_period_start: '2026/03/01',
            recruitment_period_end: '2026/04/30',
            accept_status: 'active',
            main_contract_name: 'レギュラー会員',
          },
          {
            id: 'CP002',
            name: '友達紹介キャンペーン',
            code: 'ALL2026A1B2C',
            brand: 'joyfit',
            recruitment_period_start: '2026/01/01',
            recruitment_period_end: '2026/12/31',
            accept_status: 'active',
            main_contract_name: '全契約共通',
          },
          {
            id: 'CP003',
            name: '法人割引キャンペーン',
            code: 'STR02E5F6G',
            brand: 'fit365',
            recruitment_period_start: '2026/04/01',
            recruitment_period_end: '2026/09/30',
            accept_status: 'active',
            main_contract_name: '法人会員',
          },
          {
            id: 'CP004',
            name: '新店オープン記念',
            code: 'OPEN2025A1B2C',
            brand: 'joyfit',
            recruitment_period_start: '2025/10/01',
            recruitment_period_end: '2025/12/31',
            accept_status: 'inactive',
            main_contract_name: '全契約共通',
          },
          {
            id: 'CP005',
            name: '夏のボディメイクキャンペーン',
            code: 'SUMMER26A1B2C',
            brand: 'joyfit',
            recruitment_period_start: '2026/06/01',
            recruitment_period_end: '2026/08/31',
            accept_status: 'inactive',
            main_contract_name: 'プレミアム会員',
          },
          {
            id: 'CP006',
            name: '年末特別割引',
            code: 'STR01K1L2M',
            brand: 'fit365',
            recruitment_period_start: '2026/10/01',
            recruitment_period_end: '2026/12/31',
            accept_status: 'active',
            main_contract_name: '全契約共通',
          },
        );

        const rowsById = Object.fromEntries(this._rows.map((row) => [row.id, row]));
        const defaultMainContractIdByName: Record<string, string> = {
          レギュラー会員: 'MC001',
          デイタイム会員: 'MC002',
          プレミアム会員: 'MC003',
          法人会員: 'MC004',
          全契約共通: 'MC001',
        };
        const makeDetail = (
          id: string,
          detail: Omit<CampaignDetail, keyof CampaignListItem>,
        ): CampaignDetail => {
          const row = rowsById[id]!;
          const {
            note,
            status,
            accept_status_message,
            accept_status_action_label,
            main_contract_id,
            usage_period_start,
            usage_period_end,
            application_period_start,
            application_period_end,
            application_start_month_type,
            application_custom_month,
            application_duration_months,
            discount,
            periods,
            auto_grant,
            stats,
            metadata,
            promo_code_previews,
            ...detailRest
          } = detail;
          const defaultDiscount: CampaignDetail['discount'] = {
            title: '割引設定',
            description: '割引なし',
            value_text: '割引なし',
            first_month_enabled: false,
            second_month_enabled: false,
            amount: null,
            rate: null,
          };
          const defaultAutoGrant: CampaignDetail['auto_grant'] = {
            enabled: false,
            title: '自動付与設定',
            timing_text: '手動適用',
            target_text: '全員',
            description: '自動付与は設定されていません。',
            target_type: 'all',
            gender_conditions: [],
            option_ids: [],
            option_names: [],
          };
          return {
            ...row,
            note: note ?? null,
            status: status ?? row.accept_status,
            accept_status_message:
              accept_status_message ??
              (row.accept_status === 'active'
                ? '受付中です。募集期間内の新規申請を受け付けています。'
                : '受付停止中です。現在は新規受付を行っていません。'),
            accept_status_action_label:
              accept_status_action_label ??
              (row.accept_status === 'active' ? '受付を停止する' : '受付を再開する'),
            main_contract_id:
              main_contract_id ?? defaultMainContractIdByName[row.main_contract_name] ?? 'MC001',
            usage_period_start: usage_period_start ?? row.recruitment_period_start,
            usage_period_end: usage_period_end ?? row.recruitment_period_end,
            application_period_start: application_period_start ?? row.recruitment_period_start,
            application_period_end: application_period_end ?? row.recruitment_period_end,
            application_start_month_type: application_start_month_type ?? 'first_month',
            application_custom_month: application_custom_month ?? null,
            application_duration_months: application_duration_months ?? 2,
            periods: periods ?? [
              {
                period_type: 'recruitment',
                label: '募集期間',
                start_date: row.recruitment_period_start,
                end_date: row.recruitment_period_end,
              },
              {
                period_type: 'usage',
                label: '利用開始期間',
                start_date: row.recruitment_period_start,
                end_date: row.recruitment_period_end,
              },
              {
                period_type: 'application',
                label: 'キャンペーン適用期間',
                start_date: row.recruitment_period_start,
                end_date: row.recruitment_period_end,
              },
            ],
            stats: stats ?? {
              applied_member_count: 0,
              application_count: 0,
              monthly_new_application_count: 0,
            },
            metadata: metadata ?? {
              created_at: '2026/01/01 00:00',
              created_by: '本部管理者',
              updated_at: '2026/01/01 00:00',
              updated_by: '本部管理者',
            },
            promo_code_previews: promo_code_previews ?? [],
            ...detailRest,
            discount: { ...defaultDiscount, ...discount },
            auto_grant: { ...defaultAutoGrant, ...auto_grant },
          };
        };

        this._details = {
          CP001: makeDetail('CP001', {
            note: '新生活シーズン向けの入会促進施策',
            status: 'active',
            accept_status_message: '受付中です。募集期間内の新規申請を受け付けています。',
            accept_status_action_label: '受付を停止する',
            usage_period_start: '2026/03/15',
            usage_period_end: '2026/05/31',
            application_period_start: '2026/03/01',
            application_period_end: '2026/04/30',
            main_contract_id: 'MC001',
            application_start_month_type: 'first_month',
            application_custom_month: null,
            application_duration_months: 2,
            discount: {
              title: '春の入会特典',
              description: '入会金 0円 / 事務手数料 50% OFF',
              value_text: '初月会費 1,100円引き',
              first_month_enabled: true,
              second_month_enabled: false,
              amount: 1100,
              rate: null,
            },
            periods: [
              {
                period_type: 'recruitment',
                label: '募集期間',
                start_date: '2026/03/01',
                end_date: '2026/04/30',
              },
              {
                period_type: 'usage',
                label: '利用開始期間',
                start_date: '2026/03/15',
                end_date: '2026/05/31',
              },
              {
                period_type: 'application',
                label: 'キャンペーン適用期間',
                start_date: '2026/03/01',
                end_date: '2026/04/30',
              },
            ],
            auto_grant: {
              enabled: true,
              title: '自動付与設定',
              timing_text: '会員登録完了後 3日以内',
              target_text: 'レギュラー会員',
              description: '条件を満たした会員に対して自動でキャンペーン適用を行います。',
              target_type: 'conditional',
              gender_conditions: ['male', 'female'],
              option_ids: ['OP001', 'OP002'],
              option_names: ['ドリンクバー（月額）', '水素水'],
            },
            stats: {
              applied_member_count: 128,
              application_count: 45,
              monthly_new_application_count: 12,
            },
            metadata: {
              created_at: '2026/01/10 09:30',
              created_by: '本部管理者',
              updated_at: '2026/05/31 14:20',
              updated_by: '本部管理者',
            },
            promo_code_previews: [
              {
                code: 'STR01-7HGK2',
                description: '春の入会キャンペーン用',
                valid_from: '2026/03/01',
                valid_to: '2026/04/30',
                status: 'active',
              },
              {
                code: 'STR01-KP4M8',
                description: 'オフライン配布分',
                valid_from: '2026/03/15',
                valid_to: '2026/04/15',
                status: 'expired',
              },
            ],
          }),
          CP002: makeDetail('CP002', {
            note: '紹介経由の新規会員獲得キャンペーン',
            status: 'active',
            accept_status_message: '受付中です。年間を通して適用可能です。',
            accept_status_action_label: '受付を停止する',
            usage_period_start: '2026/01/01',
            usage_period_end: '2026/12/31',
            application_period_start: '2026/01/01',
            application_period_end: '2026/12/31',
            main_contract_id: 'MC001',
            application_start_month_type: 'first_month',
            application_custom_month: null,
            application_duration_months: 2,
            discount: {
              title: '友達紹介特典',
              description: '紹介者と新規入会者の双方に特典を付与',
              value_text: '双方に 2,000円相当の特典',
              first_month_enabled: true,
              second_month_enabled: true,
              amount: 2000,
              rate: null,
            },
            periods: [
              {
                period_type: 'recruitment',
                label: '募集期間',
                start_date: '2026/01/01',
                end_date: '2026/12/31',
              },
              {
                period_type: 'usage',
                label: '利用開始期間',
                start_date: '2026/01/01',
                end_date: '2026/12/31',
              },
              {
                period_type: 'application',
                label: 'キャンペーン適用期間',
                start_date: '2026/01/01',
                end_date: '2026/12/31',
              },
            ],
            auto_grant: {
              enabled: true,
              title: '自動付与設定',
              timing_text: '申請承認後 即時',
              target_text: '全契約共通',
              description: '紹介成立時に自動で特典を付与します。',
              target_type: 'all',
              gender_conditions: [],
              option_ids: ['OP003'],
              option_names: ['タオルセット'],
            },
            stats: {
              applied_member_count: 286,
              application_count: 132,
              monthly_new_application_count: 24,
            },
            metadata: {
              created_at: '2026/01/01 08:00',
              created_by: '本部管理者',
              updated_at: '2026/05/20 11:10',
              updated_by: '本部管理者',
            },
            promo_code_previews: [
              {
                code: 'ALL2026A1B2C',
                description: '通年紹介施策',
                valid_from: '2026/01/01',
                valid_to: '2026/12/31',
                status: 'active',
              },
            ],
          }),
          CP003: makeDetail('CP003', {
            note: '法人契約向けの期間限定施策',
            status: 'active',
            accept_status_message: '受付中です。法人会員向けに公開されています。',
            accept_status_action_label: '受付を停止する',
            usage_period_start: '2026/04/15',
            usage_period_end: '2026/10/31',
            application_period_start: '2026/04/01',
            application_period_end: '2026/09/30',
            main_contract_id: 'MC004',
            application_start_month_type: 'next_month',
            application_custom_month: null,
            application_duration_months: 3,
            discount: {
              title: '法人割引',
              description: '法人契約の月会費を 10% OFF',
              value_text: '月会費 10% OFF',
              first_month_enabled: false,
              second_month_enabled: true,
              amount: null,
              rate: 10,
            },
            periods: [
              {
                period_type: 'recruitment',
                label: '募集期間',
                start_date: '2026/04/01',
                end_date: '2026/09/30',
              },
              {
                period_type: 'usage',
                label: '利用開始期間',
                start_date: '2026/04/15',
                end_date: '2026/10/31',
              },
              {
                period_type: 'application',
                label: 'キャンペーン適用期間',
                start_date: '2026/04/01',
                end_date: '2026/09/30',
              },
            ],
            auto_grant: {
              enabled: false,
              title: '自動付与設定',
              timing_text: '手動適用',
              target_text: '法人会員',
              description: '担当者がキャンペーン適用を手動で実施します。',
              target_type: 'conditional',
              gender_conditions: [],
              option_ids: [],
              option_names: [],
            },
            stats: {
              applied_member_count: 64,
              application_count: 21,
              monthly_new_application_count: 7,
            },
            metadata: {
              created_at: '2026/03/18 16:45',
              created_by: '田中 花子',
              updated_at: '2026/05/12 10:05',
              updated_by: '田中 花子',
            },
            promo_code_previews: [
              {
                code: 'STR02-CORP1',
                description: '法人提携先向け',
                valid_from: '2026/04/01',
                valid_to: '2026/09/30',
                status: 'active',
              },
              {
                code: 'STR02-CORP2',
                description: '先着配布分',
                valid_from: '2026/04/15',
                valid_to: '2026/08/31',
                status: 'limit_reached',
              },
            ],
          }),
          CP004: makeDetail('CP004', {
            note: '新店オープン記念施策',
            status: 'inactive',
            accept_status_message: '受付停止中です。現在は新規受付を行っていません。',
            accept_status_action_label: '受付を再開する',
            usage_period_start: '2025/10/15',
            usage_period_end: '2026/01/31',
            application_period_start: '2025/10/01',
            application_period_end: '2025/12/31',
            main_contract_id: 'MC001',
            application_start_month_type: 'first_month',
            application_custom_month: null,
            application_duration_months: 1,
            discount: {
              title: 'オープン記念特典',
              description: '入会金無料 / 初回月会費割引',
              value_text: '初月会費 50% OFF',
              first_month_enabled: true,
              second_month_enabled: false,
              amount: null,
              rate: 50,
            },
            periods: [
              {
                period_type: 'recruitment',
                label: '募集期間',
                start_date: '2025/10/01',
                end_date: '2025/12/31',
              },
              {
                period_type: 'usage',
                label: '利用開始期間',
                start_date: '2025/10/15',
                end_date: '2026/01/31',
              },
              {
                period_type: 'application',
                label: 'キャンペーン適用期間',
                start_date: '2025/10/01',
                end_date: '2025/12/31',
              },
            ],
            auto_grant: {
              enabled: false,
              title: '自動付与設定',
              timing_text: '手動適用',
              target_text: '全契約共通',
              description: '受付停止中のため自動付与設定は参照のみです。',
              target_type: 'all',
              gender_conditions: [],
              option_ids: [],
              option_names: [],
            },
            stats: {
              applied_member_count: 19,
              application_count: 5,
              monthly_new_application_count: 0,
            },
            metadata: {
              created_at: '2025/10/01 08:00',
              created_by: '店舗開店準備室',
              updated_at: '2025/12/20 17:30',
              updated_by: '店舗開店準備室',
            },
            promo_code_previews: [
              {
                code: 'OPEN25-GRAND',
                description: 'オープン記念配布分',
                valid_from: '2025/10/01',
                valid_to: '2025/12/31',
                status: 'inactive',
              },
            ],
          }),
          CP005: makeDetail('CP005', {
            note: '夏季の入会強化キャンペーン',
            status: 'inactive',
            accept_status_message: '受付停止中です。現在は受付を止めています。',
            accept_status_action_label: '受付を再開する',
            usage_period_start: '2026/06/15',
            usage_period_end: '2026/09/30',
            application_period_start: '2026/06/01',
            application_period_end: '2026/08/31',
            main_contract_id: 'MC003',
            application_start_month_type: 'custom_month',
            application_custom_month: 3,
            application_duration_months: 2,
            discount: {
              title: '夏のボディメイク特典',
              description: 'パーソナルトレーニング初回無料',
              value_text: '初回PT 1回無料',
              first_month_enabled: true,
              second_month_enabled: false,
              amount: 5500,
              rate: null,
            },
            periods: [
              {
                period_type: 'recruitment',
                label: '募集期間',
                start_date: '2026/06/01',
                end_date: '2026/08/31',
              },
              {
                period_type: 'usage',
                label: '利用開始期間',
                start_date: '2026/06/15',
                end_date: '2026/09/30',
              },
              {
                period_type: 'application',
                label: 'キャンペーン適用期間',
                start_date: '2026/06/01',
                end_date: '2026/08/31',
              },
            ],
            auto_grant: {
              enabled: true,
              title: '自動付与設定',
              timing_text: '会員登録完了後 1日以内',
              target_text: 'プレミアム会員',
              description: 'プレミアム会員向けに自動でキャンペーンを適用します。',
              target_type: 'conditional',
              gender_conditions: ['female'],
              option_ids: ['OP004'],
              option_names: ['パーソナルロッカー（S）'],
            },
            stats: {
              applied_member_count: 42,
              application_count: 8,
              monthly_new_application_count: 2,
            },
            metadata: {
              created_at: '2026/05/10 12:00',
              created_by: 'マーケティング担当',
              updated_at: '2026/06/01 09:20',
              updated_by: 'マーケティング担当',
            },
            promo_code_previews: [],
          }),
          CP006: makeDetail('CP006', {
            note: '年末商戦向けの特別割引施策',
            status: 'active',
            accept_status_message: '受付中です。年末に向けて公開中です。',
            accept_status_action_label: '受付を停止する',
            usage_period_start: '2026/10/15',
            usage_period_end: '2027/01/31',
            application_period_start: '2026/10/01',
            application_period_end: '2026/12/31',
            main_contract_id: 'MC001',
            application_start_month_type: 'next_month',
            application_custom_month: null,
            application_duration_months: 2,
            discount: {
              title: '年末特別割引',
              description: '入会時の初期費用を特別価格に設定',
              value_text: '初期費用 3,300円引き',
              first_month_enabled: false,
              second_month_enabled: true,
              amount: 3300,
              rate: null,
            },
            periods: [
              {
                period_type: 'recruitment',
                label: '募集期間',
                start_date: '2026/10/01',
                end_date: '2026/12/31',
              },
              {
                period_type: 'usage',
                label: '利用開始期間',
                start_date: '2026/10/15',
                end_date: '2027/01/31',
              },
              {
                period_type: 'application',
                label: 'キャンペーン適用期間',
                start_date: '2026/10/01',
                end_date: '2026/12/31',
              },
            ],
            auto_grant: {
              enabled: false,
              title: '自動付与設定',
              timing_text: '手動適用',
              target_text: '全契約共通',
              description: '年末商戦向けの特別割引は管理者が手動適用します。',
              target_type: 'all',
              gender_conditions: [],
              option_ids: [],
              option_names: [],
            },
            stats: {
              applied_member_count: 9,
              application_count: 3,
              monthly_new_application_count: 1,
            },
            metadata: {
              created_at: '2026/09/20 13:15',
              created_by: '本部管理者',
              updated_at: '2026/10/05 11:40',
              updated_by: '本部管理者',
            },
            promo_code_previews: [
              {
                code: 'STR01-YE26A',
                description: '年末キャンペーン先行配布分',
                valid_from: '2026/10/01',
                valid_to: '2026/12/31',
                status: 'active',
              },
            ],
          }),
        };

        this._changeHistory = {
          CP001: [
            {
              date: '2026/03/10 14:20',
              user: '田中 花子',
              field: '月額割引',
              from: '初月30%OFF',
              to: '初月50%OFF',
            },
            {
              date: '2026/03/05 09:15',
              user: '田中 花子',
              field: '対象契約',
              from: 'レギュラー会員のみ',
              to: 'レギュラー会員, デイタイム会員',
            },
            {
              date: '2026/02/15 10:30',
              user: '山田 太郎',
              field: null,
              from: null,
              to: '新規作成',
            },
          ],
          CP002: [
            {
              date: '2026/05/20 11:10',
              user: '本部管理者',
              field: '備考',
              from: '紹介経由の施策',
              to: '紹介経由の新規会員獲得キャンペーン',
            },
          ],
          CP003: [
            {
              date: '2026/05/12 10:05',
              user: '田中 花子',
              field: '適用主契約',
              from: '一般会員',
              to: '法人会員',
            },
            {
              date: '2026/04/01 08:30',
              user: '田中 花子',
              field: null,
              from: null,
              to: '新規作成',
            },
          ],
          CP004: [
            {
              date: '2025/12/20 17:30',
              user: '店舗開店準備室',
              field: 'ステータス',
              from: '有効',
              to: '無効',
            },
          ],
          CP005: [],
          CP006: [
            {
              date: '2026/10/05 11:40',
              user: '本部管理者',
              field: '受付可否',
              from: '下書き',
              to: '有効',
            },
          ],
        };
      },
      getList(): CampaignListItem[] {
        this._seed();
        return [...this._rows];
      },
      getById(id: string): CampaignDetail | undefined {
        this._seed();
        return this._details[id];
      },
      getChangeHistory(id: string): CampaignChangeHistoryItem[] {
        this._seed();
        return this._changeHistory[id] ?? [];
      },
      add(campaign: CampaignDetail): void {
        this._seed();
        this._rows.push({
          id: campaign.id,
          name: campaign.name,
          code: campaign.code,
          brand: campaign.brand,
          recruitment_period_start: campaign.recruitment_period_start,
          recruitment_period_end: campaign.recruitment_period_end,
          accept_status: campaign.accept_status,
          main_contract_name: campaign.main_contract_name,
        });
        this._details[campaign.id] = campaign;
        this._changeHistory[campaign.id] = [
          {
            date: campaign.metadata.updated_at,
            user: campaign.metadata.updated_by,
            field: null,
            from: null,
            to: '新規作成',
          },
        ];
      },
      update(id: string, data: Partial<CampaignDetail>): CampaignDetail | undefined {
        this._seed();
        const existing = this._details[id];
        if (!existing) return undefined;
        const updated = {
          ...existing,
          ...data,
          id,
          discount: { ...existing.discount, ...(data.discount ?? {}) },
          auto_grant: { ...existing.auto_grant, ...(data.auto_grant ?? {}) },
          metadata: { ...existing.metadata, ...(data.metadata ?? {}) },
        } satisfies CampaignDetail;
        this._details[id] = updated;
        const idx = this._rows.findIndex((row) => row.id === id);
        if (idx !== -1) {
          this._rows[idx] = {
            ...this._rows[idx],
            name: updated.name,
            code: updated.code,
            brand: updated.brand,
            recruitment_period_start: updated.recruitment_period_start,
            recruitment_period_end: updated.recruitment_period_end,
            accept_status: updated.accept_status,
            main_contract_name: updated.main_contract_name,
          };
        }
        this._changeHistory[id] = [
          {
            date: updated.metadata.updated_at,
            user: updated.metadata.updated_by,
            field: null,
            from: null,
            to: '更新',
          },
          ...(this._changeHistory[id] ?? []),
        ];
        return updated;
      },
    },

    promoCodes: {
      _rows: [] as PromoCodeRecord[],
      _seeded: false,
      _seed(): void {
        if (this._seeded) return;
        this._seeded = true;
        const db = getDb();
        const createdAt = '2026/04/01 00:00';
        const updatedAt = '2026/04/01 00:00';
        const records = db.campaigns.getList().flatMap((campaign) =>
          (db.campaigns.getById(campaign.id)?.promo_code_previews ?? []).map(
            (preview, index): PromoCodeRecord => ({
              id: `${campaign.id}-PC${String(index + 1).padStart(3, '0')}`,
              campaign_id: campaign.id,
              campaign_name: campaign.name,
              code: preview.code,
              description: preview.description ?? null,
              valid_from: preview.valid_from,
              valid_to: preview.valid_to,
              usage_count: 0,
              usage_cap: null,
              usage_cap_label: '—',
              store_scope_label: '—',
              issued_by_label: '本部',
              discount_total_label: '—',
              status: preview.status,
              disabled_reason: null,
              created_at: createdAt,
              updated_at: updatedAt,
            }),
          ),
        );
        this._rows.push(...records);
      },
      getList(): PromoCodeRecord[] {
        this._seed();
        return this._rows;
      },
      getListByCampaignId(campaignId: string): PromoCodeRecord[] {
        this._seed();
        return this._rows.filter((row) => row.campaign_id === campaignId);
      },
      getByCode(code: string): PromoCodeRecord | undefined {
        this._seed();
        return this._rows.find((row) => row.code === code);
      },
      add(data: PromoCodeUpsertBody): PromoCodeRecord {
        this._seed();
        const now = new Date().toLocaleString('ja-JP', {
          year: 'numeric',
          month: '2-digit',
          day: '2-digit',
          hour: '2-digit',
          minute: '2-digit',
          hour12: false,
        });
        const record: PromoCodeRecord = {
          id: `PC${String(this._rows.length + 1).padStart(3, '0')}`,
          campaign_id: data.campaignId,
          campaign_name: data.campaignName,
          code: data.code,
          description: data.description ?? null,
          valid_from: data.validFrom,
          valid_to: data.validTo,
          usage_count: data.usageCount,
          usage_cap: data.usageCap,
          usage_cap_label:
            data.usageCap === null ? '無制限' : `${data.usageCap.toLocaleString()}回`,
          store_scope_label:
            data.storeScope === 'all'
              ? 'タイプA: 全店舗で使用可能'
              : 'タイプB: 発行店舗のみで使用可能',
          issued_by_label: data.issuedByLabel,
          discount_total_label: '—',
          status: data.status,
          disabled_reason: null,
          created_at: now,
          updated_at: now,
        };
        this._rows.push(record);
        return record;
      },
      updateByCode(code: string, patch: Partial<PromoCodeRecord>): PromoCodeRecord | undefined {
        this._seed();
        const index = this._rows.findIndex((row) => row.code === code);
        if (index === -1) return undefined;
        const now = new Date().toLocaleString('ja-JP', {
          year: 'numeric',
          month: '2-digit',
          day: '2-digit',
          hour: '2-digit',
          minute: '2-digit',
          hour12: false,
        });
        const next = { ...this._rows[index]!, ...patch, updated_at: patch.updated_at ?? now };
        this._rows[index] = next;
        return next;
      },
    },
  };
}
